# Množenje matrica

$$
\begin{bmatrix}    
1& 2& 3\\
  4 &5 &6\\
  7 &8& 9
\end{bmatrix}
\begin{bmatrix}
   1&  2&  0\\
   4&  3&  2\\
   1& -1&  1
 \end{bmatrix}=\\
 \begin{bmatrix}
   (1\cdot 1 + 2\cdot 4+3\cdot 1) & 1\cdot 2+2\cdot 3+3\cdot(-1))&  
    (1\cdot 0 + 2\cdot 2 + 3\cdot 1)\\
   (4\cdot 1+5\cdot 5+6\cdot 1) & (4\cdot 2+5\cdot 3+6\cdot (-1)) &  
   (4\cdot 0+5\cdot 2+6\cdot 1)\\
   (7\cdot 1+8\cdot 5+9\cdot 1) & (7\cdot 2+8\cdot 3+9\cdot (-1)) &  
   (7\cdot 0+8\cdot 2+9\cdot 1)
 \end{bmatrix}
$$

$$
\begin{bmatrix}    
  1& 2& 3\\
  4 &5 &6\\
  7 &8& 9
\end{bmatrix}
\begin{bmatrix}
   1&  2&  0\\
   4&  3&  2\\
   1& -1&  1
 \end{bmatrix}=\\
 \begin{bmatrix} 1\\ 4\\ 7 \end{bmatrix}
 \begin{bmatrix} 1&2&0 \end{bmatrix} + 
 \begin{bmatrix} 2\\ 5\\ 8 \end{bmatrix}
 \begin{bmatrix} 4&3&2 \end{bmatrix} + 
 \begin{bmatrix} 3\\ 6\\ 9 \end{bmatrix}
 \begin{bmatrix} 1&-1&1 \end{bmatrix}
$$

$$
\begin{bmatrix}    
  1& 2& 3\\
  4 &5 &6\\
  7 &8& 9
\end{bmatrix}
\begin{bmatrix}
   1&  2&  0\\
   4&  3&  2\\
   1& -1&  1
 \end{bmatrix}=\\
 \begin{bmatrix}
   1 \begin{bmatrix} 1\\ 4\\ 7\end{bmatrix}+
   4 \begin{bmatrix} 2\\ 5\\ 8\end{bmatrix}+
   1 \begin{bmatrix} 3\\ 6\\ 9\end{bmatrix} &
   2 \begin{bmatrix} 1\\ 4\\ 7\end{bmatrix}+
   3 \begin{bmatrix} 2\\ 5\\ 8\end{bmatrix}+
   (-1) \begin{bmatrix} 3\\ 6\\ 9\end{bmatrix} &
   0 \begin{bmatrix} 1\\ 4\\ 7\end{bmatrix}+
   2 \begin{bmatrix} 2\\ 5\\ 8\end{bmatrix}+
   1 \begin{bmatrix} 3\\ 6\\ 9\end{bmatrix}
 \end{bmatrix}
$$


In [1]:
n=5
A=ones(5,5)
B=ones(5,5)
C=zeros(n,n)
for i=1:n
    for j=1:n
        for k=1:n
            C[i,j]=C[i,j]+A[i,k]*A[k,j]
        end
    end
end
C

5x5 Array{Float64,2}:
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0

In [2]:
# _dot
for i=1:n
    for j=1:n
        @show C[i,j]=(A[i,:]*B[:,j])[]
    end
end

C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0


In [3]:
# _syrk
C=zeros(n,n)
for i=1:n
    @show C=C+A[:,i]*A[i,:]
end

C = C + A[:,i] * A[i,:] => [1.0 1.0 1.0 1.0 1.0
 1.0 1.0 1.0 1.0 1.0
 1.0 1.0 1.0 1.0 1.0
 1.0 1.0 1.0 1.0 1.0
 1.0 1.0 1.0 1.0 1.0]
C = C + A[:,i] * A[i,:] => [2.0 2.0 2.0 2.0 2.0
 2.0 2.0 2.0 2.0 2.0
 2.0 2.0 2.0 2.0 2.0
 2.0 2.0 2.0 2.0 2.0
 2.0 2.0 2.0 2.0 2.0]
C = C + A[:,i] * A[i,:] => [3.0 3.0 3.0 3.0 3.0
 3.0 3.0 3.0 3.0 3.0
 3.0 3.0 3.0 3.0 3.0
 3.0 3.0 3.0 3.0 3.0
 3.0 3.0 3.0 3.0 3.0]
C = C + A[:,i] * A[i,:] => [4.0 4.0 4.0 4.0 4.0
 4.0 4.0 4.0 4.0 4.0
 4.0 4.0 4.0 4.0 4.0
 4.0 4.0 4.0 4.0 4.0
 4.0 4.0 4.0 4.0 4.0]
C = C + A[:,i] * A[i,:] => [5.0 5.0 5.0 5.0 5.0
 5.0 5.0 5.0 5.0 5.0
 5.0 5.0 5.0 5.0 5.0
 5.0 5.0 5.0 5.0 5.0
 5.0 5.0 5.0 5.0 5.0]


In [4]:
# _axpy
C=zeros(n,n)
for i=1:n
    for k=1:n
        C[:,i]=C[:,i]+A[:,k]*B[k,i]
    end
    @show c
end

LoadError: c not defined
while loading In[4], in expression starting on line 3

## Basic Linear Algrbea Subroutines - BLAS

Na primjer, `ddot.f` from _NetLib_

Uočite _loop unrolling_

```
DOUBLE PRECISION FUNCTION DDOT(N,DX,INCX,DY,INCY)
*     .. Scalar Arguments ..
      INTEGER INCX,INCY,N
*     ..
*     .. Array Arguments ..
      DOUBLE PRECISION DX(*),DY(*)
*     ..
*
*  Purpose
*  =======
*
*     forms the dot product of two vectors.
*     uses unrolled loops for increments equal to one.
*     jack dongarra, linpack, 3/11/78.
*     modified 12/3/93, array(1) declarations changed to array(*)
*
*
*     .. Local Scalars ..
      DOUBLE PRECISION DTEMP
      INTEGER I,IX,IY,M,MP1
*     ..
*     .. Intrinsic Functions ..
      INTRINSIC MOD
*     ..
      DDOT = 0.0d0
      DTEMP = 0.0d0
      IF (N.LE.0) RETURN
      IF (INCX.EQ.1 .AND. INCY.EQ.1) GO TO 20
*
*        code for unequal increments or equal increments
*          not equal to 1
*
      IX = 1
      IY = 1
      IF (INCX.LT.0) IX = (-N+1)*INCX + 1
      IF (INCY.LT.0) IY = (-N+1)*INCY + 1
      DO 10 I = 1,N
          DTEMP = DTEMP + DX(IX)*DY(IY)
          IX = IX + INCX
          IY = IY + INCY
   10 CONTINUE
      DDOT = DTEMP
      RETURN
*
*        code for both increments equal to 1
*
*
*        clean-up loop
*
   20 M = MOD(N,5)
      IF (M.EQ.0) GO TO 40
      DO 30 I = 1,M
          DTEMP = DTEMP + DX(I)*DY(I)
   30 CONTINUE
      IF (N.LT.5) GO TO 60
   40 MP1 = M + 1
      DO 50 I = MP1,N,5
          DTEMP = DTEMP + DX(I)*DY(I) + DX(I+1)*DY(I+1) +
     +            DX(I+2)*DY(I+2) + DX(I+3)*DY(I+3) + DX(I+4)*DY(I+4)
   50 CONTINUE
   60 DDOT = DTEMP
      RETURN
      END
```


## Brzina

In [5]:
function AB{T}(A::Array{T},B::Array{T})
    n=maximum(size(A))
    C=zeros(n,n)
    # C=[zeros(A[1,1]) for i=1:n, j=1:n]
    for i=1:n
        for j=1:n
            for k=1:n
                C[i,j]=C[i,j]+(A[i,k]*B[k,j])[]
            end
        end
    end
    C
end

AB (generic function with 1 method)

In [6]:
n=512
A=rand(n,n)
B=rand(n,n)

512x512 Array{Float64,2}:
 0.619109   0.313246     0.93604     …  0.53129     0.421121   0.420753 
 0.747055   0.629113     0.320077       0.450326    0.62608    0.809576 
 0.487758   0.820158     0.0706713      0.00998676  0.740457   0.316047 
 0.310908   0.487621     0.208364       0.992689    0.66095    0.363393 
 0.467693   0.998017     0.00588614     0.48809     0.913668   0.314835 
 0.859842   0.840589     0.692514    …  0.315594    0.990131   0.517917 
 0.518192   0.761072     0.212609       0.542992    0.836111   0.0632955
 0.915996   0.584422     0.378242       0.888151    0.66567    0.0126165
 0.508712   0.665877     0.26151        0.551832    0.373641   0.370325 
 0.507627   0.205059     0.384647       0.777553    0.312787   0.872638 
 0.9224     0.938891     0.791071    …  0.495284    0.127705   0.316063 
 0.655447   0.690923     0.609272       0.590995    0.845371   0.238382 
 0.559193   0.971902     0.456887       0.33255     0.326991   0.139664 
 ⋮                       

In [7]:
@time C=A*B

elapsed time: 0.010381535 seconds (2115752 bytes allocated)


512x512 Array{Float64,2}:
 129.026  134.428  127.363  131.34   …  124.454  126.256  125.529  127.728
 118.992  126.281  121.201  124.599     118.437  123.099  117.637  120.702
 132.741  137.534  128.284  134.691     128.443  132.067  128.863  133.689
 127.828  130.154  125.173  133.52      122.458  127.314  120.923  123.924
 125.115  132.013  129.048  131.107     124.406  124.16   126.285  127.978
 129.671  133.582  129.563  132.16   …  124.073  124.727  130.26   127.047
 130.393  130.642  126.397  135.0       122.543  130.804  128.263  123.72 
 128.417  134.431  131.452  134.017     130.482  135.003  131.795  127.873
 122.7    128.184  127.617  128.251     123.543  125.335  126.317  124.682
 121.615  128.556  123.106  130.055     119.24   121.257  120.818  123.425
 125.184  129.563  125.955  130.915  …  123.577  124.174  127.497  128.136
 124.606  125.375  120.556  127.624     116.19   121.575  120.675  119.84 
 129.017  133.963  132.19   132.804     128.515  131.363  128.62   130.358

In [8]:
operacija_u_sekundi=(2*n^3)/0.012

2.2369621333333332e10

In [9]:
# Izvedite 2 puta, releventno je drugo mjerenje. Izvodjenje je znacajno sporije!! 
@time AB(A,B);

elapsed time: 0.514995001 seconds (2478960 bytes allocated)


### Blok varijanta

In [10]:
function AB{T}(A::Array{T},B::Array{T})
    n=maximum(size(A))
    # C=zeros(n,n)
    C=[zeros(A[1,1]) for i=1:n, j=1:n]
    for i=1:n
        for j=1:n
            for k=1:n
                C[i,j]=C[i,j]+(A[i,k]*B[k,j])[]
            end
        end
    end
    C
end

AB (generic function with 1 method)

In [11]:
# Probajte k,l=32,16 i k,l=64,8
k,l=32,16
Ab=[rand(k,k) for i=1:l, j=1:l]
Bb=[rand(k,k) for i=1:l, j=1:l];

In [12]:
# Ovo je bitno brze
@time C=AB(Ab,Bb);

elapsed time: 0.129986815 seconds (74463412 bytes allocated, 29.85% gc time)


## Točnost

__Apsloutna pogreška__
$$|fl(x\cdot y)-x\cdot y|\leq O(n\varepsilon) |x|\cdot |y| \tag{*}$$

__Relativna pogreška__
$$\frac{|fl(x\cdot y)-x\cdot y|}{|x\cdot y|}\leq O(n\varepsilon) \frac{|x|\cdot |y|}{|x\cdot y|}$$


In [13]:
n=1000000
x=rand(n)
j=int(rand(n)-0.5.<0.0)
y=rand(n)-0.5

1000000-element Array{Float64,1}:
  0.40561   
 -0.133103  
 -0.253234  
  0.0826457 
 -0.234422  
 -0.00204108
  0.100865  
 -0.089523  
  0.155396  
  0.210401  
  0.351543  
  0.467457  
  0.280367  
  ⋮         
  0.142787  
 -0.015859  
 -0.038242  
  0.347742  
 -0.269625  
 -0.405545  
  0.219671  
 -0.0714571 
 -0.295893  
 -0.462101  
 -0.297915  
 -0.441782  

In [14]:
d=x⋅y

161.4449713539065

In [15]:
ab=abs(x)⋅abs(y)

124817.62268820172

In [16]:
xb=[BigFloat(x[k]) for k=1:n]
yb=[BigFloat(y[k]) for k=1:n]

1000000-element Array{Any,1}:
  4.05609685367772865305369123234413564205169677734375e-01 
 -1.3310294945562173296593755367211997509002685546875e-01  
 -2.5323391546141937880065597710199654102325439453125e-01  
  8.26457476629764986597592724137939512729644775390625e-02 
 -2.34421655682503615736322899465449154376983642578125e-01 
 -2.041078415051966743476441479288041591644287109375e-03   
  1.008648600779513682113019967800937592983245849609375e-01
 -8.952296005665072442525342921726405620574951171875e-02   
  1.553956934131530687182021210901439189910888671875e-01   
  2.10401069184164679626292127068154513835906982421875e-01 
  3.515426883995356188705727618071250617504119873046875e-01
  4.674567366052924111130550954840146005153656005859375e-01
  2.803672076293448611750136478804051876068115234375e-01   
  ⋮                                                        
  1.42786838191574450007692576036788523197174072265625e-01 
 -1.58589598090446148859200548031367361545562744140625e-02 
 -3.824197

In [17]:
db=xb⋅yb

1.614449713539056087684383498933985069123726244275824664561251424454990655021902e+02 with 256 bits of precision

In [18]:
abserr=abs(d-db)

9.013346772292199657127531547193224175335438748575545009344978097942657768726349e-13 with 256 bits of precision

In [19]:
relerr=abserr/d

5.582921968212856477050151967252149071765105316164514909596486816132165129668321e-15 with 256 bits of precision

### Za matrice

Iz formule (*) za matrice slijedi
    $$ |fl(A\cdot B) -A\cdot B| \leq O(n\varepsilon) |A|\cdot |B|$$ 

In [20]:
n=256
A=rand(n,n)
B=rand(n,n).-0.5

256x256 Array{Float64,2}:
  0.342422   -0.468015   -0.20384     0.432939   …   0.157201     0.317064 
  0.0412422   0.45129     0.473402   -0.253994       0.13915      0.369969 
  0.387856    0.0757862   0.134087    0.139974       0.292525     0.288062 
  0.0731955  -0.241291    0.336531    0.0221068     -0.39275     -0.158393 
 -0.242777   -0.16913     0.377398   -0.404782      -0.419197     0.269819 
 -0.257283   -0.180429   -0.490359    0.433267   …  -0.104062    -0.255692 
  0.0299934   0.277847   -0.322775   -0.153075       0.0553197    0.306944 
  0.241589   -0.0390976  -0.338563   -0.39996        0.3748       0.277777 
  0.0198818   0.457702   -0.312153    0.437532      -0.170468    -0.425281 
 -0.0326278  -0.0177639   0.40374     0.341974       0.479243     0.222871 
 -0.314732   -0.475481   -0.0770544   0.252358   …   0.362354     0.381931 
 -0.0397515  -0.353052    0.330831   -0.431471      -0.282929    -0.0918762
 -0.294011    0.450525   -0.364944    0.197552       0.343139 

In [21]:
Ab=[BigFloat(A[i,j]) for i=1:n, j=1:n]
Bb=[BigFloat(B[i,j]) for i=1:n, j=1:n]

256x256 Array{Any,2}:
  3.424217520470300701873611615155823528766632080078125e-01  …   3.170635575800597738549413406872190535068511962890625e-01
  4.12421574050145789414045793819241225719451904296875e-02       3.699686335058680608511849641217850148677825927734375e-01
  3.878555869919224630137932763318531215190887451171875e-01      2.880620167858811697669807472266256809234619140625e-01   
  7.319548871509429233128685154952108860015869140625e-02        -1.58392587979291565858375179232098162174224853515625e-01 
 -2.427766751389499599866894641309045255184173583984375e-01      2.6981882772855581009707748307846486568450927734375e-01  
 -2.572831923067731008103464773739688098430633544921875e-01  …  -2.556924723204276883592456215410493314266204833984375e-01
  2.99933778452032839823004906065762042999267578125e-02          3.069436845344408748559317245963029563426971435546875e-01
  2.4158892284920607806952830287627875804901123046875e-01        2.7777723670883869289127687807194888591766357421875e

In [22]:
C=A*B
# ovo traje malo duze
Cb=Ab*Bb
abserr=abs(C-float64(Cb))

256x256 Array{Float64,2}:
 2.22045e-15  3.88578e-16  6.93889e-16  …  1.22125e-15  2.66454e-15
 8.88178e-16  1.77636e-15  9.22873e-16     0.0          8.88178e-16
 4.44089e-16  8.88178e-16  1.33227e-15     4.44089e-16  1.77636e-15
 4.44089e-16  2.22045e-16  1.11022e-15     1.33227e-15  0.0        
 8.88178e-16  4.44089e-16  8.88178e-16     2.44249e-15  2.66454e-15
 2.22045e-15  8.88178e-16  4.44089e-16  …  1.77636e-15  8.88178e-16
 0.0          4.44089e-16  1.44329e-15     1.9984e-15   1.77636e-15
 8.88178e-16  2.22045e-15  8.88178e-16     4.44089e-16  1.77636e-15
 0.0          1.77636e-15  3.10862e-15     5.55112e-16  0.0        
 4.44089e-16  4.44089e-16  9.99201e-16     0.0          4.44089e-16
 0.0          1.77636e-15  8.88178e-16  …  1.77636e-15  1.77636e-15
 8.88178e-16  1.05471e-15  2.66454e-15     2.22045e-16  4.44089e-16
 8.88178e-16  4.16334e-16  8.88178e-16     5.55112e-16  2.66454e-15
 ⋮                                      ⋱               ⋮          
 4.44089e-16  4.44089e

In [23]:
abs(A)*abs(B)*n*eps()

256x256 Array{Float64,2}:
 1.70185e-12  1.84524e-12  1.81013e-12  …  1.66957e-12  1.78812e-12
 1.78547e-12  1.84478e-12  1.81761e-12     1.76586e-12  1.86034e-12
 1.85799e-12  2.00698e-12  1.9037e-12      1.85152e-12  1.93309e-12
 1.79259e-12  1.91591e-12  1.83336e-12     1.75626e-12  1.95561e-12
 1.76024e-12  1.85729e-12  1.87477e-12     1.74735e-12  1.83372e-12
 2.0438e-12   2.06023e-12  1.98874e-12  …  1.98884e-12  1.92955e-12
 1.78132e-12  1.85991e-12  1.78048e-12     1.73515e-12  1.83797e-12
 1.77852e-12  1.77941e-12  1.83589e-12     1.68604e-12  1.84947e-12
 1.9026e-12   1.90572e-12  1.85394e-12     1.906e-12    1.86598e-12
 1.81829e-12  1.73328e-12  1.81469e-12     1.73283e-12  1.79406e-12
 1.74913e-12  1.8937e-12   1.84876e-12  …  1.81718e-12  1.78634e-12
 1.76258e-12  1.92395e-12  1.76876e-12     1.74248e-12  1.80347e-12
 1.97141e-12  2.03201e-12  1.94252e-12     1.86383e-12  1.89186e-12
 ⋮                                      ⋱               ⋮          
 1.93001e-12  1.97927e

Ovdje nije lako razabrati relativnu pogrešku pa nam treba pogodnija mjera -> __matrične i vektorske norme__