# Množenje matrica

$$
\begin{bmatrix}    
1& 2& 3\\
  4 &5 &6\\
  7 &8& 9
\end{bmatrix}
\begin{bmatrix}
   1&  2&  0\\
   4&  3&  2\\
   1& -1&  1
 \end{bmatrix}=\\
 \begin{bmatrix}
   (1\cdot 1 + 2\cdot 4+3\cdot 1) & 1\cdot 2+2\cdot 3+3\cdot(-1))&  
    (1\cdot 0 + 2\cdot 2 + 3\cdot 1)\\
   (4\cdot 1+5\cdot 5+6\cdot 1) & (4\cdot 2+5\cdot 3+6\cdot (-1)) &  
   (4\cdot 0+5\cdot 2+6\cdot 1)\\
   (7\cdot 1+8\cdot 5+9\cdot 1) & (7\cdot 2+8\cdot 3+9\cdot (-1)) &  
   (7\cdot 0+8\cdot 2+9\cdot 1)
 \end{bmatrix}
$$

$$
\begin{bmatrix}    
  1& 2& 3\\
  4 &5 &6\\
  7 &8& 9
\end{bmatrix}
\begin{bmatrix}
   1&  2&  0\\
   4&  3&  2\\
   1& -1&  1
 \end{bmatrix}=\\
 \begin{bmatrix} 1\\ 4\\ 7 \end{bmatrix}
 \begin{bmatrix} 1&2&0 \end{bmatrix} + 
 \begin{bmatrix} 2\\ 5\\ 8 \end{bmatrix}
 \begin{bmatrix} 4&3&2 \end{bmatrix} + 
 \begin{bmatrix} 3\\ 6\\ 9 \end{bmatrix}
 \begin{bmatrix} 1&-1&1 \end{bmatrix}
$$

$$
\begin{bmatrix}    
  1& 2& 3\\
  4 &5 &6\\
  7 &8& 9
\end{bmatrix}
\begin{bmatrix}
   1&  2&  0\\
   4&  3&  2\\
   1& -1&  1
 \end{bmatrix}=\\
 \begin{bmatrix}
   1 \begin{bmatrix} 1\\ 4\\ 7\end{bmatrix}+
   4 \begin{bmatrix} 2\\ 5\\ 8\end{bmatrix}+
   1 \begin{bmatrix} 3\\ 6\\ 9\end{bmatrix} &
   2 \begin{bmatrix} 1\\ 4\\ 7\end{bmatrix}+
   3 \begin{bmatrix} 2\\ 5\\ 8\end{bmatrix}+
   (-1) \begin{bmatrix} 3\\ 6\\ 9\end{bmatrix} &
   0 \begin{bmatrix} 1\\ 4\\ 7\end{bmatrix}+
   2 \begin{bmatrix} 2\\ 5\\ 8\end{bmatrix}+
   1 \begin{bmatrix} 3\\ 6\\ 9\end{bmatrix}
 \end{bmatrix}
$$


In [1]:
n=5
A=ones(5,5)
B=ones(5,5)
C=zeros(n,n)
for i=1:n
    for j=1:n
        for k=1:n
            C[i,j]=C[i,j]+A[i,k]*A[k,j]
        end
    end
end
C

5x5 Array{Float64,2}:
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0

In [2]:
# Ili, krace: _dot
for i=1:n
    for j=1:n
        @show C[i,j]=(A[i,:]*B[:,j])[]
    end
end

C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0


In [3]:
C=zeros(n,n)
for k=1:n
    for j=1:n
        for i=1:n
            C[i,j]=C[i,j]+A[i,k]*A[k,j]
            @show i,j,C[i,j]
        end
    end
end

(i,j,C[i,j]) => (1,1,1.0)
(i,j,C[i,j]) => (2,1,1.0)
(i,j,C[i,j]) => (3,1,1.0)
(i,j,C[i,j]) => (4,1,1.0)
(i,j,C[i,j]) => (5,1,1.0)
(i,j,C[i,j]) => (1,2,1.0)
(i,j,C[i,j]) => (2,2,1.0)
(i,j,C[i,j]) => (3,2,1.0)
(i,j,C[i,j]) => (4,2,1.0)
(i,j,C[i,j]) => (5,2,1.0)
(i,j,C[i,j]) => (1,3,1.0)
(i,j,C[i,j]) => (2,3,1.0)
(i,j,C[i,j]) => (3,3,1.0)
(i,j,C[i,j]) => (4,3,1.0)
(i,j,C[i,j]) => (5,3,1.0)
(i,j,C[i,j]) => (1,4,1.0)
(i,j,C[i,j]) => (2,4,1.0)
(i,j,C[i,j]) => (3,4,1.0)
(i,j,C[i,j]) => (4,4,1.0)
(i,j,C[i,j]) => (5,4,1.0)
(i,j,C[i,j]) => (1,5,1.0)
(i,j,C[i,j]) => (2,5,1.0)
(i,j,C[i,j]) => (3,5,1.0)
(i,j,C[i,j]) => (4,5,1.0)
(i,j,C[i,j]) => (5,5,1.0)
(i,j,C[i,j]) => (1,1,2.0)
(i,j,C[i,j]) => (2,1,2.0)
(i,j,C[i,j]) => (3,1,2.0)
(i,j,C[i,j]) => (4,1,2.0)
(i,j,C[i,j]) => (5,1,2.0)
(i,j,C[i,j]) => (1,2,2.0)
(i,j,C[i,j]) => (2,2,2.0)
(i,j,C[i,j]) => (3,2,2.0)
(i,j,C[i,j]) => (4,2,2.0)
(i,j,C[i,j]) => (5,2,2.0)
(i,j,C[i,j]) => (1,3,2.0)
(i,j,C[i,j]) => (2,3,2.0)
(i,j,C[i,j]) => (3,3,2.0)
(i,j,C[i,j])

In [4]:
# Ili, krace: _syrk
C=zeros(n,n)
for i=1:n
    @show C=C+A[:,i]*A[i,:]
end

C = C + A[:,i] * A[i,:] => [1.0 1.0 1.0 1.0 1.0
 1.0 1.0 1.0 1.0 1.0
 1.0 1.0 1.0 1.0 1.0
 1.0 1.0 1.0 1.0 1.0
 1.0 1.0 1.0 1.0 1.0]
C = C + A[:,i] * A[i,:] => [2.0 2.0 2.0 2.0 2.0
 2.0 2.0 2.0 2.0 2.0
 2.0 2.0 2.0 2.0 2.0
 2.0 2.0 2.0 2.0 2.0
 2.0 2.0 2.0 2.0 2.0]
C = C + A[:,i] * A[i,:] => [3.0 3.0 3.0 3.0 3.0
 3.0 3.0 3.0 3.0 3.0
 3.0 3.0 3.0 3.0 3.0
 3.0 3.0 3.0 3.0 3.0
 3.0 3.0 3.0 3.0 3.0]
C = C + A[:,i] * A[i,:] => [4.0 4.0 4.0 4.0 4.0
 4.0 4.0 4.0 4.0 4.0
 4.0 4.0 4.0 4.0 4.0
 4.0 4.0 4.0 4.0 4.0
 4.0 4.0 4.0 4.0 4.0]
C = C + A[:,i] * A[i,:] => [5.0 5.0 5.0 5.0 5.0
 5.0 5.0 5.0 5.0 5.0
 5.0 5.0 5.0 5.0 5.0
 5.0 5.0 5.0 5.0 5.0
 5.0 5.0 5.0 5.0 5.0]


In [5]:
C=zeros(n,n)
for j=1:n
    for k=1:n
        for i=1:n
            C[i,j]=C[i,j]+A[i,k]*A[k,j]
            @show i,j,C[i,j]
        end
    end
end

(i,j,C[i,j]) => (1,1,1.0)
(i,j,C[i,j]) => (2,1,1.0)
(i,j,C[i,j]) => (3,1,1.0)
(i,j,C[i,j]) => (4,1,1.0)
(i,j,C[i,j]) => (5,1,1.0)
(i,j,C[i,j]) => (1,1,2.0)
(i,j,C[i,j]) => (2,1,2.0)
(i,j,C[i,j]) => (3,1,2.0)
(i,j,C[i,j]) => (4,1,2.0)
(i,j,C[i,j]) => (5,1,2.0)
(i,j,C[i,j]) => (1,1,3.0)
(i,j,C[i,j]) => (2,1,3.0)
(i,j,C[i,j]) => (3,1,3.0)
(i,j,C[i,j]) => (4,1,3.0)
(i,j,C[i,j]) => (5,1,3.0)
(i,j,C[i,j]) => (1,1,4.0)
(i,j,C[i,j]) => (2,1,4.0)
(i,j,C[i,j]) => (3,1,4.0)
(i,j,C[i,j]) => (4,1,4.0)
(i,j,C[i,j]) => (5,1,4.0)
(i,j,C[i,j]) => (1,1,5.0)
(i,j,C[i,j]) => (2,1,5.0)
(i,j,C[i,j]) => (3,1,5.0)
(i,j,C[i,j]) => (4,1,5.0)
(i,j,C[i,j]) => (5,1,5.0)
(i,j,C[i,j]) => (1,2,1.0)
(i,j,C[i,j]) => (2,2,1.0)
(i,j,C[i,j]) => (3,2,1.0)
(i,j,C[i,j]) => (4,2,1.0)
(i,j,C[i,j]) => (5,2,1.0)
(i,j,C[i,j]) => (1,2,2.0)
(i,j,C[i,j]) => (2,2,2.0)
(i,j,C[i,j]) => (3,2,2.0)
(i,j,C[i,j]) => (4,2,2.0)
(i,j,C[i,j]) => (5,2,2.0)
(i,j,C[i,j]) => (1,2,3.0)
(i,j,C[i,j]) => (2,2,3.0)
(i,j,C[i,j]) => (3,2,3.0)
(i,j,C[i,j])

In [6]:
# _axpy
C=zeros(n,n)
for i=1:n
    for k=1:n
        C[:,i]=C[:,i]+A[:,k]*B[k,i]
    end
    @show C
end

C => [5.0 0.0 0.0 0.0 0.0
 5.0 0.0 0.0 0.0 0.0
 5.0 0.0 0.0 0.0 0.0
 5.0 0.0 0.0 0.0 0.0
 5.0 0.0 0.0 0.0 0.0]
C => [5.0 5.0 0.0 0.0 0.0
 5.0 5.0 0.0 0.0 0.0
 5.0 5.0 0.0 0.0 0.0
 5.0 5.0 0.0 0.0 0.0
 5.0 5.0 0.0 0.0 0.0]
C => [5.0 5.0 5.0 0.0 0.0
 5.0 5.0 5.0 0.0 0.0
 5.0 5.0 5.0 0.0 0.0
 5.0 5.0 5.0 0.0 0.0
 5.0 5.0 5.0 0.0 0.0]
C => [5.0 5.0 5.0 5.0 0.0
 5.0 5.0 5.0 5.0 0.0
 5.0 5.0 5.0 5.0 0.0
 5.0 5.0 5.0 5.0 0.0
 5.0 5.0 5.0 5.0 0.0]
C => [5.0 5.0 5.0 5.0 5.0
 5.0 5.0 5.0 5.0 5.0
 5.0 5.0 5.0 5.0 5.0
 5.0 5.0 5.0 5.0 5.0
 5.0 5.0 5.0 5.0 5.0]


## Basic Linear Algrbea Subroutines - BLAS

Na primjer, `ddot.f` from _NetLib_

Uočite _loop unrolling_

```
DOUBLE PRECISION FUNCTION DDOT(N,DX,INCX,DY,INCY)
*     .. Scalar Arguments ..
      INTEGER INCX,INCY,N
*     ..
*     .. Array Arguments ..
      DOUBLE PRECISION DX(*),DY(*)
*     ..
*
*  Purpose
*  =======
*
*     forms the dot product of two vectors.
*     uses unrolled loops for increments equal to one.
*     jack dongarra, linpack, 3/11/78.
*     modified 12/3/93, array(1) declarations changed to array(*)
*
*
*     .. Local Scalars ..
      DOUBLE PRECISION DTEMP
      INTEGER I,IX,IY,M,MP1
*     ..
*     .. Intrinsic Functions ..
      INTRINSIC MOD
*     ..
      DDOT = 0.0d0
      DTEMP = 0.0d0
      IF (N.LE.0) RETURN
      IF (INCX.EQ.1 .AND. INCY.EQ.1) GO TO 20
*
*        code for unequal increments or equal increments
*          not equal to 1
*
      IX = 1
      IY = 1
      IF (INCX.LT.0) IX = (-N+1)*INCX + 1
      IF (INCY.LT.0) IY = (-N+1)*INCY + 1
      DO 10 I = 1,N
          DTEMP = DTEMP + DX(IX)*DY(IY)
          IX = IX + INCX
          IY = IY + INCY
   10 CONTINUE
      DDOT = DTEMP
      RETURN
*
*        code for both increments equal to 1
*
*
*        clean-up loop
*
   20 M = MOD(N,5)
      IF (M.EQ.0) GO TO 40
      DO 30 I = 1,M
          DTEMP = DTEMP + DX(I)*DY(I)
   30 CONTINUE
      IF (N.LT.5) GO TO 60
   40 MP1 = M + 1
      DO 50 I = MP1,N,5
          DTEMP = DTEMP + DX(I)*DY(I) + DX(I+1)*DY(I+1) +
     +            DX(I+2)*DY(I+2) + DX(I+3)*DY(I+3) + DX(I+4)*DY(I+4)
   50 CONTINUE
   60 DDOT = DTEMP
      RETURN
      END
```


## Brzina

In [7]:
function AB{T}(A::Array{T},B::Array{T})
    n=maximum(size(A))
    C=zeros(n,n)
    # C=[zeros(A[1,1]) for i=1:n, j=1:n]
    for i=1:n
        for j=1:n
            for k=1:n
                C[i,j]=C[i,j]+(A[i,k]*B[k,j])[]
            end
        end
    end
    C
end

AB (generic function with 1 method)

In [8]:
n=512
A=rand(n,n)
B=rand(n,n)

512x512 Array{Float64,2}:
 0.0286245  0.851682  0.00835743  …  0.322421   0.149096  0.414287 
 0.11106    0.555787  0.373973       0.586757   0.798138  0.615597 
 0.826836   0.62552   0.966163       0.312178   0.821586  0.884834 
 0.902962   0.452013  0.165905       0.224991   0.599845  0.264506 
 0.825636   0.685832  0.364313       0.968076   0.581474  0.446736 
 0.456142   0.952893  0.249522    …  0.630562   0.298359  0.799207 
 0.496692   0.626027  0.705269       0.271454   0.7835    0.894942 
 0.0969673  0.714162  0.0769741      0.788485   0.369842  0.852142 
 0.170869   0.820883  0.441961       0.289887   0.367163  0.931858 
 0.874703   0.421884  0.212268       0.743069   0.523061  0.0983342
 0.132244   0.423293  0.325723    …  0.693617   0.68266   0.489005 
 0.378262   0.363394  0.909998       0.063571   0.732455  0.926934 
 0.361572   0.267101  0.527246       0.531817   0.413514  0.25316  
 ⋮                                ⋱             ⋮                  
 0.896802   0.612455  

In [9]:
@time C=A*B

elapsed time: 0.019476802 seconds (2115752 bytes allocated)


512x512 Array{Float64,2}:
 122.07   131.201  124.42   124.215  …  129.376  129.392  133.218  133.624
 125.662  130.405  129.246  126.059     125.297  125.993  127.947  135.824
 116.151  124.934  122.682  122.22      123.944  120.614  124.042  124.784
 119.842  129.512  124.261  124.397     124.834  125.151  131.64   130.951
 121.993  130.005  126.036  124.554     129.907  129.663  128.713  130.984
 116.425  129.375  124.17   126.444  …  125.755  123.766  128.893  127.921
 123.266  131.284  128.751  125.656     129.899  126.696  131.673  133.04 
 114.329  119.001  120.546  116.452     119.473  117.325  120.348  123.529
 121.302  129.059  128.343  125.495     126.071  128.045  128.615  133.671
 122.049  132.232  126.851  127.303     129.262  128.753  132.386  130.411
 120.617  127.905  124.864  124.539  …  129.164  126.703  129.406  130.479
 126.221  136.891  132.021  130.471     132.426  132.626  135.012  138.857
 121.663  132.546  126.009  125.685     127.83   126.232  127.52   133.007

In [10]:
operacija_u_sekundi=(2*n^3)/0.012

2.2369621333333332e10

In [11]:
# Izvedite 2 puta, releventno je drugo mjerenje. Izvodjenje je znacajno sporije!! 
@time AB(A,B);

elapsed time: 0.520795625 seconds (2478960 bytes allocated)


### Blok varijanta

In [12]:
function AB{T}(A::Array{T},B::Array{T})
    n=maximum(size(A))
    # C=zeros(n,n)
    C=[zeros(A[1,1]) for i=1:n, j=1:n]
    for i=1:n
        for j=1:n
            for k=1:n
                C[i,j]=C[i,j]+(A[i,k]*B[k,j])[]
            end
        end
    end
    C
end

AB (generic function with 1 method)

In [13]:
# Probajte k,l=32,16 i k,l=64,8
k,l=32,16
Ab=[rand(k,k) for i=1:l, j=1:l]
Bb=[rand(k,k) for i=1:l, j=1:l];

In [14]:
# Ovo je bitno brze
@time C=AB(Ab,Bb);

elapsed time: 0.130225868 seconds (74464340 bytes allocated, 32.28% gc time)


## Točnost

__Apsloutna pogreška__
$$|fl(x\cdot y)-x\cdot y|\leq O(n\varepsilon) |x|\cdot |y| \tag{*}$$

__Relativna pogreška__
$$\frac{|fl(x\cdot y)-x\cdot y|}{|x\cdot y|}\leq O(n\varepsilon) \frac{|x|\cdot |y|}{|x\cdot y|}$$


In [15]:
n=1000000
x=rand(n)
j=int(rand(n)-0.5.<0.0)
y=rand(n)-0.5

1000000-element Array{Float64,1}:
 -0.459874 
 -0.0240005
  0.306202 
  0.356429 
  0.19688  
 -0.19248  
  0.323973 
 -0.149433 
 -0.25725  
 -0.16354  
  0.165276 
  0.235261 
  0.0607556
  ⋮        
 -0.0593589
 -0.035469 
 -0.221054 
 -0.457989 
 -0.32256  
  0.299973 
 -0.489367 
 -0.0384675
  0.303931 
  0.195008 
 -0.115242 
  0.17312  

In [16]:
d=x⋅y

43.01937514296222

In [17]:
ab=abs(x)⋅abs(y)

124962.83539433374

In [18]:
xb=[BigFloat(x[k]) for k=1:n]
yb=[BigFloat(y[k]) for k=1:n]

1000000-element Array{Any,1}:
 -4.598744403256753709996473844512365758419036865234375e-01
 -2.400046959704393856327442335896193981170654296875e-02   
  3.06202069141524813034038743353448808193206787109375e-01 
  3.5642945775191225976641362649388611316680908203125e-01  
  1.968802740677173535033261941862292587757110595703125e-01
 -1.9248027244158283366459727403707802295684814453125e-01  
  3.23972806955765246783585098455660045146942138671875e-01 
 -1.49432783573242300434458229574374854564666748046875e-01 
 -2.572501669407689650626025468227453529834747314453125e-01
 -1.635401664202789095980961064924485981464385986328125e-01
  1.65275664566951530076721610384993255138397216796875e-01 
  2.35260805493032965074462481425143778324127197265625e-01 
  6.07556171711960413261977009824477136135101318359375e-02 
  ⋮                                                        
 -5.9358948806622624516649011638946831226348876953125e-02  
 -3.546898430570966098684948519803583621978759765625e-02   
 -2.210540

In [19]:
db=xb⋅yb

4.301937514296145406428516300779310503588275671359355518774100811743577033041674e+01 with 256 bits of precision

In [20]:
abserr=abs(d-db)

7.641415813572852638598383848214114064448122589918825642296695832555997185409069e-13 with 256 bits of precision

In [21]:
relerr=abserr/d

1.776273083506875360891843729661662394716991638731120001558060700742008723364473e-14 with 256 bits of precision

### Za matrice

Iz formule (*) za matrice slijedi
    $$ |fl(A\cdot B) -A\cdot B| \leq O(n\varepsilon) |A|\cdot |B|$$ 

In [22]:
n=256
A=rand(n,n)
B=rand(n,n).-0.5

256x256 Array{Float64,2}:
  0.409132    0.129711    -0.301234    …   0.221953   -0.478105   -0.365101  
 -0.146315    0.301778     0.117815       -0.235072   -0.424132    0.214345  
 -0.360279    0.452048    -0.420288        0.233681    0.381476   -0.362083  
  0.490176    0.0313735   -0.114861       -0.357892   -0.396017   -0.356119  
  0.222126   -0.361928    -0.448892       -0.373574   -0.305579    0.418612  
 -0.19536     0.27501     -0.310569    …   0.207579    0.313524   -0.175232  
  0.0272064   0.33033      0.304466       -0.331125   -0.370599    0.179687  
  0.147989    0.385776     0.490494       -0.275065    0.367237    0.173862  
 -0.387742   -0.414095     0.413532        0.208387   -0.451815    0.0776552 
  0.214857   -0.450245    -0.186859       -0.419581   -0.0432979  -0.155268  
  0.135095    0.383351    -0.0826171   …  -0.19841     0.170144    0.340779  
 -0.27973    -0.0426329    0.125293       -0.402133    0.128794    0.236895  
 -0.157024    0.205961    -0.229797   

In [23]:
Ab=[BigFloat(A[i,j]) for i=1:n, j=1:n]
Bb=[BigFloat(B[i,j]) for i=1:n, j=1:n]

256x256 Array{Any,2}:
  4.091319056279940635789671432576142251491546630859375e-01  …  -3.65101253163717220928674578317441046237945556640625e-01 
 -1.46314862852467086895558168180286884307861328125e-01          2.14345413980407517584581000846810638904571533203125e-01 
 -3.602794769687573950278647316736169159412384033203125e-01     -3.620826544159851945181571863940916955471038818359375e-01
  4.901760413003375393969918150105513632297515869140625e-01     -3.561185365830994431490807983209379017353057861328125e-01
  2.221255552380398956557883138884790241718292236328125e-01      4.186124705253828626183576488983817398548126220703125e-01
 -1.953603253883604562446407726383768022060394287109375e-01  …  -1.752317647832695168830241527757607400417327880859375e-01
  2.72064007902257376514398856670595705509185791015625e-02       1.7968741522378817165872533223591744899749755859375e-01  
  1.479885736278394592346785429981537163257598876953125e-01      1.7386221481723840298627692391164600849151611328125e

In [24]:
C=A*B
# ovo traje malo duze
Cb=Ab*Bb
abserr=abs(C-float64(Cb))

256x256 Array{Float64,2}:
 3.10862e-15  1.33227e-15  1.44329e-15  …  8.88178e-16  8.88178e-16
 8.88178e-16  1.77636e-15  1.9984e-15      1.92554e-16  8.88178e-15
 1.77636e-15  3.10862e-15  7.77156e-16     1.33227e-15  0.0        
 0.0          2.66454e-15  4.44089e-16     6.66134e-16  1.33227e-15
 8.88178e-16  4.44089e-16  0.0             5.55112e-16  4.44089e-15
 8.88178e-16  1.00267e-15  1.33227e-15  …  4.44089e-16  4.44089e-16
 4.44089e-16  1.77636e-15  8.88178e-16     1.33227e-15  2.66454e-15
 3.88578e-16  2.66454e-15  1.11022e-15     1.11022e-15  7.10543e-15
 8.88178e-16  3.55271e-15  8.88178e-16     0.0          8.88178e-16
 0.0          2.66454e-15  6.66134e-16     4.44089e-16  2.66454e-15
 3.55271e-15  2.66454e-15  2.22045e-16  …  1.77636e-15  1.77636e-15
 3.33067e-16  2.22045e-15  4.44089e-16     1.55431e-15  8.88178e-16
 4.44089e-16  0.0          6.66134e-16     1.11022e-16  1.77636e-15
 ⋮                                      ⋱               ⋮          
 1.77636e-15  2.22045e

In [25]:
abs(A)*abs(B)*n*eps()

256x256 Array{Float64,2}:
 1.77126e-12  1.78101e-12  1.71108e-12  …  1.85644e-12  1.8999e-12 
 1.75633e-12  1.76549e-12  1.7678e-12      1.77935e-12  1.85009e-12
 1.68485e-12  1.76647e-12  1.80515e-12     1.84619e-12  1.89725e-12
 1.72677e-12  1.72225e-12  1.73066e-12     1.80855e-12  1.83333e-12
 1.80612e-12  1.86652e-12  1.77657e-12     1.91055e-12  1.97412e-12
 1.63219e-12  1.72878e-12  1.71362e-12  …  1.8596e-12   1.85757e-12
 1.74638e-12  1.93444e-12  1.82609e-12     1.90223e-12  1.94329e-12
 1.70905e-12  1.86179e-12  1.75679e-12     1.90106e-12  1.93152e-12
 1.81406e-12  1.86307e-12  1.86327e-12     1.89824e-12  1.99118e-12
 1.77968e-12  1.80309e-12  1.80249e-12     1.89937e-12  2.00921e-12
 1.79521e-12  1.85867e-12  1.80933e-12  …  1.84601e-12  1.93379e-12
 1.66403e-12  1.83271e-12  1.674e-12       1.8353e-12   1.85383e-12
 1.77728e-12  1.84881e-12  1.83598e-12     1.94665e-12  1.90078e-12
 ⋮                                      ⋱               ⋮          
 1.61761e-12  1.64317e

Ovdje nije lako razabrati relativnu pogrešku pa nam treba pogodnija mjera -> __matrične i vektorske norme__