# Množenje matrica

---

Matrice možemo množiti na __tri različita načina__: 

\begin{align*}
\begin{bmatrix}    
1& 2& 3\\
  4 &5 &6\\
  7 &8& 9
\end{bmatrix}
\begin{bmatrix}
   1&  2&  0\\
   4&  3&  2\\
   1& -1&  1
 \end{bmatrix}&=
 \begin{bmatrix}
   (1\cdot 1 + 2\cdot 4+3\cdot 1) & 1\cdot 2+2\cdot 3+3\cdot(-1))&  
    (1\cdot 0 + 2\cdot 2 + 3\cdot 1)\\
   (4\cdot 1+5\cdot 5+6\cdot 1) & (4\cdot 2+5\cdot 3+6\cdot (-1)) &  
   (4\cdot 0+5\cdot 2+6\cdot 1)\\
   (7\cdot 1+8\cdot 5+9\cdot 1) & (7\cdot 2+8\cdot 3+9\cdot (-1)) &  
   (7\cdot 0+8\cdot 2+9\cdot 1)
 \end{bmatrix} \\ \\
\begin{bmatrix}    
  1& 2& 3\\
  4 &5 &6\\
  7 &8& 9
\end{bmatrix}
\begin{bmatrix}
   1&  2&  0\\
   4&  3&  2\\
   1& -1&  1
 \end{bmatrix}& =
 \begin{bmatrix} 1\\ 4\\ 7 \end{bmatrix}
 \begin{bmatrix} 1&2&0 \end{bmatrix} + 
 \begin{bmatrix} 2\\ 5\\ 8 \end{bmatrix}
 \begin{bmatrix} 4&3&2 \end{bmatrix} + 
 \begin{bmatrix} 3\\ 6\\ 9 \end{bmatrix}
 \begin{bmatrix} 1&-1&1 \end{bmatrix}\\ \\
\begin{bmatrix}    
  1& 2& 3\\
  4 &5 &6\\
  7 &8& 9
\end{bmatrix}
\begin{bmatrix}
   1&  2&  0\\
   4&  3&  2\\
   1& -1&  1
 \end{bmatrix}&=
 \begin{bmatrix}
   1 \begin{bmatrix} 1\\ 4\\ 7\end{bmatrix}+
   4 \begin{bmatrix} 2\\ 5\\ 8\end{bmatrix}+
   1 \begin{bmatrix} 3\\ 6\\ 9\end{bmatrix} &
   2 \begin{bmatrix} 1\\ 4\\ 7\end{bmatrix}+
   3 \begin{bmatrix} 2\\ 5\\ 8\end{bmatrix}+
   (-1) \begin{bmatrix} 3\\ 6\\ 9\end{bmatrix} &
   0 \begin{bmatrix} 1\\ 4\\ 7\end{bmatrix}+
   2 \begin{bmatrix} 2\\ 5\\ 8\end{bmatrix}+
   1 \begin{bmatrix} 3\\ 6\\ 9\end{bmatrix}
 \end{bmatrix}
\end{align*}

Formule se razlikuju u načinu prisutupa memoriji pa stoga i po brzini te u pogreškama zaokruživanja.

In [1]:
n=5
A=ones(5,5)
B=ones(5,5)
C=zeros(n,n)
for i=1:n
    for j=1:n
        for k=1:n
            C[i,j]=C[i,j]+A[i,k]*A[k,j]
        end
    end
end
C

5x5 Array{Float64,2}:
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0

In [2]:
# Ili, krace: _dot
for i=1:n
    for j=1:n
        @show C[i,j]=(A[i,:]*B[:,j])[]
    end
end

C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0


In [3]:
C=zeros(n,n)
for k=1:n
    for j=1:n
        for i=1:n
            C[i,j]=C[i,j]+A[i,k]*A[k,j]
            @show i,j,C[i,j]
        end
    end
end

(i,j,C[i,j]) = (1,1,1.0)
(i,j,C[i,j]) = (2,1,1.0)
(i,j,C[i,j]) = (3,1,1.0)
(i,j,C[i,j]) = (4,1,1.0)
(i,j,C[i,j]) = (5,1,1.0)
(i,j,C[i,j]) = (1,2,1.0)
(i,j,C[i,j]) = (2,2,1.0)
(i,j,C[i,j]) = (3,2,1.0)
(i,j,C[i,j]) = (4,2,1.0)
(i,j,C[i,j]) = (5,2,1.0)
(i,j,C[i,j]) = (1,3,1.0)
(i,j,C[i,j]) = (2,3,1.0)
(i,j,C[i,j]) = (3,3,1.0)
(i,j,C[i,j]) = (4,3,1.0)
(i,j,C[i,j]) = (5,3,1.0)
(i,j,C[i,j]) = (1,4,1.0)
(i,j,C[i,j]) = (2,4,1.0)
(i,j,C[i,j]) = (3,4,1.0)
(i,j,C[i,j]) = (4,4,1.0)
(i,j,C[i,j]) = (5,4,1.0)
(i,j,C[i,j]) = (1,5,1.0)
(i,j,C[i,j]) = (2,5,1.0)
(i,j,C[i,j]) = (3,5,1.0)
(i,j,C[i,j]) = (4,5,1.0)
(i,j,C[i,j]) = (5,5,1.0)
(i,j,C[i,j]) = (1,1,2.0)
(i,j,C[i,j]) = (2,1,2.0)
(i,j,C[i,j]) = (3,1,2.0)
(i,j,C[i,j]) = (4,1,2.0)
(i,j,C[i,j]) = (5,1,2.0)
(i,j,C[i,j]) = (1,2,2.0)
(i,j,C[i,j]) = (2,2,2.0)
(i,j,C[i,j]) = (3,2,2.0)
(i,j,C[i,j]) = (4,2,2.0)
(i,j,C[i,j]) = (5,2,2.0)
(i,j,C[i,j]) = (1,3,2.0)
(i,j,C[i,j]) = (2,3,2.0)
(i,j,C[i,j]) = (3,3,2.0)
(i,j,C[i,j]) = (4,3,2.0)
(i,j,C[i,j]) = (5,3,2.0)


In [4]:
# Ili, krace: _syrk
C=zeros(n,n)
for i=1:n
    @show C=C+A[:,i]*A[i,:]
end

C = C + A[:,i] * A[i,:] = [1.0 1.0 1.0 1.0 1.0
 1.0 1.0 1.0 1.0 1.0
 1.0 1.0 1.0 1.0 1.0
 1.0 1.0 1.0 1.0 1.0
 1.0 1.0 1.0 1.0 1.0]
C = C + A[:,i] * A[i,:] = [2.0 2.0 2.0 2.0 2.0
 2.0 2.0 2.0 2.0 2.0
 2.0 2.0 2.0 2.0 2.0
 2.0 2.0 2.0 2.0 2.0
 2.0 2.0 2.0 2.0 2.0]
C = C + A[:,i] * A[i,:] = [3.0 3.0 3.0 3.0 3.0
 3.0 3.0 3.0 3.0 3.0
 3.0 3.0 3.0 3.0 3.0
 3.0 3.0 3.0 3.0 3.0
 3.0 3.0 3.0 3.0 3.0]
C = C + A[:,i] * A[i,:] = [4.0 4.0 4.0 4.0 4.0
 4.0 4.0 4.0 4.0 4.0
 4.0 4.0 4.0 4.0 4.0
 4.0 4.0 4.0 4.0 4.0
 4.0 4.0 4.0 4.0 4.0]
C = C + A[:,i] * A[i,:] = [5.0 5.0 5.0 5.0 5.0
 5.0 5.0 5.0 5.0 5.0
 5.0 5.0 5.0 5.0 5.0
 5.0 5.0 5.0 5.0 5.0
 5.0 5.0 5.0 5.0 5.0]


In [5]:
C=zeros(n,n)
for j=1:n
    for k=1:n
        for i=1:n
            C[i,j]=C[i,j]+A[i,k]*A[k,j]
            @show i,j,C[i,j]
        end
    end
end

(i,j,C[i,j]) = (1,1,1.0)
(i,j,C[i,j]) = (2,1,1.0)
(i,j,C[i,j]) = (3,1,1.0)
(i,j,C[i,j]) = (4,1,1.0)
(i,j,C[i,j]) = (5,1,1.0)
(i,j,C[i,j]) = (1,1,2.0)
(i,j,C[i,j]) = (2,1,2.0)
(i,j,C[i,j]) = (3,1,2.0)
(i,j,C[i,j]) = (4,1,2.0)
(i,j,C[i,j]) = (5,1,2.0)
(i,j,C[i,j]) = (1,1,3.0)
(i,j,C[i,j]) = (2,1,3.0)
(i,j,C[i,j]) = (3,1,3.0)
(i,j,C[i,j]) = (4,1,3.0)
(i,j,C[i,j]) = (5,1,3.0)
(i,j,C[i,j]) = (1,1,4.0)
(i,j,C[i,j]) = (2,1,4.0)
(i,j,C[i,j]) = (3,1,4.0)
(i,j,C[i,j]) = (4,1,4.0)
(i,j,C[i,j]) = (5,1,4.0)
(i,j,C[i,j]) = (1,1,5.0)
(i,j,C[i,j]) = (2,1,5.0)
(i,j,C[i,j]) = (3,1,5.0)
(i,j,C[i,j]) = (4,1,5.0)
(i,j,C[i,j]) = (5,1,5.0)
(i,j,C[i,j]) = (1,2,1.0)
(i,j,C[i,j]) = (2,2,1.0)
(i,j,C[i,j]) = (3,2,1.0)
(i,j,C[i,j]) = (4,2,1.0)
(i,j,C[i,j]) = (5,2,1.0)
(i,j,C[i,j]) = (1,2,2.0)
(i,j,C[i,j]) = (2,2,2.0)
(i,j,C[i,j]) = (3,2,2.0)
(i,j,C[i,j]) = (4,2,2.0)
(i,j,C[i,j]) = (5,2,2.0)
(i,j,C[i,j]) = (1,2,3.0)
(i,j,C[i,j]) = (2,2,3.0)
(i,j,C[i,j]) = (3,2,3.0)
(i,j,C[i,j]) = (4,2,3.0)
(i,j,C[i,j]) = (5,2,3.0)


In [6]:
# _axpy
C=zeros(n,n)
for i=1:n
    for k=1:n
        C[:,i]=C[:,i]+A[:,k]*B[k,i]
    end
    @show C
end

C = [5.0 0.0 0.0 0.0 0.0
 5.0 0.0 0.0 0.0 0.0
 5.0 0.0 0.0 0.0 0.0
 5.0 0.0 0.0 0.0 0.0
 5.0 0.0 0.0 0.0 0.0]
C = [5.0 5.0 0.0 0.0 0.0
 5.0 5.0 0.0 0.0 0.0
 5.0 5.0 0.0 0.0 0.0
 5.0 5.0 0.0 0.0 0.0
 5.0 5.0 0.0 0.0 0.0]
C = [5.0 5.0 5.0 0.0 0.0
 5.0 5.0 5.0 0.0 0.0
 5.0 5.0 5.0 0.0 0.0
 5.0 5.0 5.0 0.0 0.0
 5.0 5.0 5.0 0.0 0.0]
C = [5.0 5.0 5.0 5.0 0.0
 5.0 5.0 5.0 5.0 0.0
 5.0 5.0 5.0 5.0 0.0
 5.0 5.0 5.0 5.0 0.0
 5.0 5.0 5.0 5.0 0.0]
C = [5.0 5.0 5.0 5.0 5.0
 5.0 5.0 5.0 5.0 5.0
 5.0 5.0 5.0 5.0 5.0
 5.0 5.0 5.0 5.0 5.0
 5.0 5.0 5.0 5.0 5.0]


## Basic Linear Algrbea Subroutines - [BLAS](http://www.netlib.org/blas/)

Na primjer, [`ddot.f`](http://www.netlib.org/lapack/explore-html/d5/df6/ddot_8f_source.html) - uočite _loop unrolling_:

```
DOUBLE PRECISION FUNCTION DDOT(N,DX,INCX,DY,INCY)
*     .. Scalar Arguments ..
      INTEGER INCX,INCY,N
*     ..
*     .. Array Arguments ..
      DOUBLE PRECISION DX(*),DY(*)
*     ..
*
*  Purpose
*  =======
*
*     forms the dot product of two vectors.
*     uses unrolled loops for increments equal to one.
*     jack dongarra, linpack, 3/11/78.
*     modified 12/3/93, array(1) declarations changed to array(*)
*
*
*     .. Local Scalars ..
      DOUBLE PRECISION DTEMP
      INTEGER I,IX,IY,M,MP1
*     ..
*     .. Intrinsic Functions ..
      INTRINSIC MOD
*     ..
      DDOT = 0.0d0
      DTEMP = 0.0d0
      IF (N.LE.0) RETURN
      IF (INCX.EQ.1 .AND. INCY.EQ.1) GO TO 20
*
*        code for unequal increments or equal increments
*          not equal to 1
*
      IX = 1
      IY = 1
      IF (INCX.LT.0) IX = (-N+1)*INCX + 1
      IF (INCY.LT.0) IY = (-N+1)*INCY + 1
      DO 10 I = 1,N
          DTEMP = DTEMP + DX(IX)*DY(IY)
          IX = IX + INCX
          IY = IY + INCY
   10 CONTINUE
      DDOT = DTEMP
      RETURN
*
*        code for both increments equal to 1
*
*
*        clean-up loop
*
   20 M = MOD(N,5)
      IF (M.EQ.0) GO TO 40
      DO 30 I = 1,M
          DTEMP = DTEMP + DX(I)*DY(I)
   30 CONTINUE
      IF (N.LT.5) GO TO 60
   40 MP1 = M + 1
      DO 50 I = MP1,N,5
          DTEMP = DTEMP + DX(I)*DY(I) + DX(I+1)*DY(I+1) +
     +            DX(I+2)*DY(I+2) + DX(I+3)*DY(I+3) + DX(I+4)*DY(I+4)
   50 CONTINUE
   60 DDOT = DTEMP
      RETURN
      END
```


## Brzina

In [1]:
function AB{T}(A::Array{T},B::Array{T})
    n=maximum(size(A))
    C=zeros(n,n)
    # C=[zeros(A[1,1]) for i=1:n, j=1:n]
    for i=1:n
        for j=1:n
            for k=1:n
                C[i,j]=C[i,j]+(A[i,k]*B[k,j])[]
            end
        end
    end
    C
end

AB (generic function with 1 method)

In [2]:
n=512
A=rand(n,n)
B=rand(n,n)

512x512 Array{Float64,2}:
 0.134698    0.247067    0.908251  …  0.50624     0.366463   0.407217 
 0.408657    0.908037    0.18839      0.00824593  0.289704   0.978939 
 0.400351    0.419817    0.911431     0.605392    0.0983382  0.364905 
 0.55769     0.124846    0.076421     0.145915    0.661123   0.987884 
 0.655715    0.507574    0.985976     0.800839    0.806173   0.605702 
 0.159751    0.552568    0.658584  …  0.709786    0.149457   0.767284 
 0.142179    0.327382    0.731548     0.162614    0.555102   0.0827774
 0.622467    0.00567664  0.764891     0.058429    0.564639   0.34249  
 0.563557    0.0136565   0.915272     0.887039    0.838292   0.945158 
 0.524441    0.489412    0.204116     0.237732    0.340972   0.735985 
 0.111402    0.63437     0.323525  …  0.144308    0.509784   0.703416 
 0.686551    0.371129    0.626029     0.274668    0.082981   0.261579 
 0.199338    0.172178    0.487987     0.129129    0.306619   0.795555 
 ⋮                                 ⋱              ⋮

In [5]:
# Izvedite 2 puta, releventno je drugo mjerenje.
@time C=A*B

  0.016783 seconds (9 allocations: 2.000 MB)


512x512 Array{Float64,2}:
 125.026  129.156  132.2    127.47   …  123.398  122.639  132.985  126.093
 123.532  123.308  128.658  127.835     124.315  120.227  127.199  126.219
 129.926  129.075  130.328  125.225     121.197  123.184  133.886  127.554
 130.461  133.032  133.777  131.038     128.909  133.431  136.64   129.377
 126.161  127.376  126.723  125.621     127.258  124.119  135.018  125.98 
 127.071  125.47   130.156  130.103  …  125.68   123.048  135.069  125.751
 129.032  131.008  132.463  129.182     128.027  128.112  134.438  125.722
 121.507  124.619  125.657  126.487     124.485  123.742  130.271  119.997
 134.103  130.873  135.076  131.887     130.8    129.379  141.726  133.202
 130.015  131.213  132.904  127.122     130.579  124.45   135.912  133.123
 121.29   121.422  124.852  123.644  …  122.564  121.144  127.932  121.006
 130.454  126.936  129.522  127.156     128.023  127.794  132.664  126.115
 131.89   126.565  125.734  125.677     125.157  120.19   131.673  127.773

In [6]:
operacija_u_sekundi=(2*n^3)/0.012

2.2369621333333332e10

In [9]:
# Izvedite 2 puta, releventno je drugo mjerenje. Izvodjenje nadeg programa je znacajno sporije!! 
@time AB(A,B);

  0.462747 seconds (6 allocations: 2.000 MB)


### Blok varijanta

Da bi ubrzali naš program, potrebno je računati s blok-matricama:

In [11]:
function AB{T}(A::Array{T},B::Array{T})
    n=maximum(size(A))
    # C=zeros(n,n)
    C=[zeros(A[1,1]) for i=1:n, j=1:n]
    for i=1:n
        for j=1:n
            for k=1:n
                C[i,j]=C[i,j]+(A[i,k]*B[k,j])[]
            end
        end
    end
    C
end

AB (generic function with 1 method)

In [18]:
# Probajte k,l=32,16 i k,l=64,8. Izvedite dva puta.
k,l=64,8
Ab=[rand(k,k) for i=1:l, j=1:l]
Bb=[rand(k,k) for i=1:l, j=1:l];

In [19]:
# Ovo je bitno brze
@time C=AB(Ab,Bb);

  0.039279 seconds (3.21 k allocations: 34.091 MB, 5.54% gc time)


## Točnost

__Apsloutna pogreška__:

$$|fl(x\cdot y)-x\cdot y|\leq O(n\varepsilon) |x|\cdot |y| \tag{1}$$

__Relativna pogreška__:

$$\frac{|fl(x\cdot y)-x\cdot y|}{|x\cdot y|}\leq O(n\varepsilon) \frac{|x|\cdot |y|}{|x\cdot y|}$$


In [21]:
n=1000000
x=rand(n)
j=round(Int64,(rand(n)-0.5.<0.0))
y=rand(n)-0.5

1000000-element Array{Float64,1}:
  0.494258  
  0.490999  
 -0.34357   
  0.156186  
 -0.0665376 
  0.0852794 
  0.446943  
 -0.0638079 
 -0.262237  
 -0.435588  
 -0.311995  
 -0.0607622 
  0.0131093 
  ⋮         
 -0.166736  
 -0.478517  
  0.32944   
  0.00798877
 -0.181731  
 -0.292722  
  0.0824565 
 -0.265628  
  0.281904  
  0.264625  
 -0.469749  
  0.0259992 

In [22]:
d=x⋅y

113.22936907389717

In [23]:
ab=abs(x)⋅abs(y)

124898.6241992054

In [24]:
# provjerimo rješenje pomocu `BigFloat` brojeva (70tak tocnih znamenki)
xbig=map(BigFloat,x)
ybig=map(BigFloat,y)

1000000-element Array{BigFloat,1}:
  4.942579973553331562641233176691457629203796386718750000000000000000000000000000e-01
  4.909993426187939657978631657897494733333587646484375000000000000000000000000000e-01
 -3.435697278698195411550386779708787798881530761718750000000000000000000000000000e-01
  1.561861939869453319573722183122299611568450927734375000000000000000000000000000e-01
 -6.653760627227223167778902279678732156753540039062500000000000000000000000000000e-02
  8.527943337044341376440570456907153129577636718750000000000000000000000000000000e-02
  4.469429664425175197095541079761460423469543457031250000000000000000000000000000e-01
 -6.380794988456872651738649437902495265007019042968750000000000000000000000000000e-02
 -2.622369326335414196904594064108096063137054443359375000000000000000000000000000e-01
 -4.355877645471815107214297313475981354713439941406250000000000000000000000000000e-01
 -3.119945342530092702304500562604516744613647460937500000000000000000000000000000e-01
 -6.0762

In [25]:
dbig=xbig⋅ybig

1.132293690738966207378749259091641569182194321291879838690148799614648700284647e+02

In [26]:
abserr=abs(d-dbig)

5.540199285151161525583222590834958120161309851200385351299715352979546878486872e-13

In [27]:
relerr=abserr/d

4.892899545819642426414219950900262136072798733777311722000781543339094909565077e-15

### Za matrice

Iz formule (1) za matrice slijedi

$$ |fl(A\cdot B) -A\cdot B| \leq O(n\varepsilon) |A|\cdot |B|.$$ 

In [28]:
n=256
A=rand(n,n)
B=rand(n,n).-0.5

256x256 Array{Float64,2}:
  0.25433      0.377483     0.0602168  …   0.0360486  -0.086397   -0.488326  
 -0.433274    -0.313755    -0.247953       0.0575027  -0.487551    0.312855  
 -0.308697     0.152568     0.410779       0.249416    0.266007    0.479594  
 -0.189316     0.172956    -0.398474      -0.1196     -0.377993   -0.136453  
  0.294341    -0.294168    -0.480751       0.225332    0.414433    0.0675695 
 -0.109213     0.0792828   -0.120398   …   0.0499068  -0.108012    0.150726  
  0.371597     0.0232555    0.461231       0.402458    0.359463   -0.45998   
 -0.260406    -0.32546     -0.0727102     -0.394049    0.128593    0.220183  
  0.0878372   -0.279609     0.130793      -0.262316    0.178813    0.213803  
  0.262186    -0.334933    -0.247898       0.0670878  -0.0977401  -0.287861  
  0.348469    -0.0499317   -0.299782   …   0.243476   -0.425321   -0.00809899
  0.42806     -0.0553905   -0.49486        0.245762    0.408132   -0.324412  
 -0.15742     -0.112853     0.156095  

In [29]:
Ab=[BigFloat(A[i,j]) for i=1:n, j=1:n]
Bb=[BigFloat(B[i,j]) for i=1:n, j=1:n]

256x256 Array{BigFloat,2}:
  2.543300413461919706747949021519161760807037353515625000000000000000000000000000e-01  …  -4.883264438115144656649135868065059185028076171875000000000000000000000000000000e-01
 -4.332741117677143538600148531259037554264068603515625000000000000000000000000000e-01      3.128554460553363281150041075306944549083709716796875000000000000000000000000000e-01
 -3.086966753295405929691241908585652709007263183593750000000000000000000000000000e-01      4.795935284233774353879198315553367137908935546875000000000000000000000000000000e-01
 -1.893156977170347143868411876610480248928070068359375000000000000000000000000000e-01     -1.364533609780465006622307555517181754112243652343750000000000000000000000000000e-01
  2.943408254560897496787674754159525036811828613281250000000000000000000000000000e-01      6.756952940347371594498326885513961315155029296875000000000000000000000000000000e-02
 -1.092134432954192657660996701451949775218963623046875000000000000000000000000000e-01  

In [30]:
C=A*B
# ovo traje malo duze
Cb=Ab*Bb
abserr=abs(C-map(Float64,Cb))

256x256 Array{Float64,2}:
 0.0          6.66134e-16  1.77636e-15  …  0.0          2.22045e-16
 2.22045e-16  0.0          3.33067e-15     1.77636e-15  4.44089e-16
 4.44089e-16  2.22045e-16  0.0             8.88178e-16  1.77636e-15
 7.77156e-16  4.44089e-16  1.77636e-15     2.66454e-15  4.44089e-16
 6.17562e-16  6.66134e-16  0.0             6.66134e-16  4.44089e-16
 1.11022e-16  4.44089e-16  3.33067e-16  …  8.88178e-16  1.80411e-16
 1.77636e-15  1.11022e-15  4.44089e-15     1.77636e-15  2.22045e-15
 9.99201e-16  0.0          2.22045e-15     1.33227e-15  8.88178e-16
 1.05471e-15  4.44089e-16  4.44089e-16     2.22045e-16  4.44089e-16
 4.44089e-16  1.77636e-15  8.88178e-16     5.55112e-17  4.44089e-16
 2.77556e-16  8.88178e-16  4.44089e-16  …  3.10862e-15  0.0        
 1.77636e-15  4.44089e-16  4.44089e-16     3.05311e-16  8.88178e-16
 1.33227e-15  2.66454e-15  4.44089e-16     1.33227e-15  4.44089e-16
 ⋮                                      ⋱               ⋮          
 2.22045e-15  8.88178e

In [31]:
abs(A)*abs(B)*n*eps()

256x256 Array{Float64,2}:
 1.68216e-12  1.71033e-12  1.52322e-12  …  1.77018e-12  1.65758e-12
 1.76518e-12  1.78325e-12  1.57079e-12     1.83656e-12  1.72425e-12
 1.85775e-12  1.84401e-12  1.71691e-12     1.9997e-12   1.91494e-12
 1.69943e-12  1.84688e-12  1.67128e-12     1.94177e-12  1.74859e-12
 1.89558e-12  1.74403e-12  1.66098e-12     1.88695e-12  1.82901e-12
 1.74136e-12  1.74426e-12  1.61504e-12  …  1.86691e-12  1.73763e-12
 1.83685e-12  1.80737e-12  1.67064e-12     1.87366e-12  1.69128e-12
 1.88608e-12  1.89271e-12  1.72968e-12     1.94653e-12  1.82548e-12
 1.59901e-12  1.65517e-12  1.48615e-12     1.76962e-12  1.47505e-12
 1.78262e-12  1.87231e-12  1.6392e-12      1.89426e-12  1.80018e-12
 1.66015e-12  1.81507e-12  1.54317e-12  …  1.86758e-12  1.75641e-12
 1.89097e-12  1.94811e-12  1.72871e-12     1.92655e-12  1.84051e-12
 1.76939e-12  1.78985e-12  1.68576e-12     1.94867e-12  1.79587e-12
 ⋮                                      ⋱               ⋮          
 1.81985e-12  1.83986e

Ovdje nije lako razabrati relativnu pogrešku pa nam treba pogodnija mjera -> __matrične i vektorske norme__.