# Množenje matrica

$$
\begin{bmatrix}    
1& 2& 3\\
  4 &5 &6\\
  7 &8& 9
\end{bmatrix}
\begin{bmatrix}
   1&  2&  0\\
   4&  3&  2\\
   1& -1&  1
 \end{bmatrix}=\\
 \begin{bmatrix}
   (1\cdot 1 + 2\cdot 4+3\cdot 1) & 1\cdot 2+2\cdot 3+3\cdot(-1))&  
    (1\cdot 0 + 2\cdot 2 + 3\cdot 1)\\
   (4\cdot 1+5\cdot 5+6\cdot 1) & (4\cdot 2+5\cdot 3+6\cdot (-1)) &  
   (4\cdot 0+5\cdot 2+6\cdot 1)\\
   (7\cdot 1+8\cdot 5+9\cdot 1) & (7\cdot 2+8\cdot 3+9\cdot (-1)) &  
   (7\cdot 0+8\cdot 2+9\cdot 1)
 \end{bmatrix}
$$

$$
\begin{bmatrix}    
  1& 2& 3\\
  4 &5 &6\\
  7 &8& 9
\end{bmatrix}
\begin{bmatrix}
   1&  2&  0\\
   4&  3&  2\\
   1& -1&  1
 \end{bmatrix}=\\
 \begin{bmatrix} 1\\ 4\\ 7 \end{bmatrix}
 \begin{bmatrix} 1&2&0 \end{bmatrix} + 
 \begin{bmatrix} 2\\ 5\\ 8 \end{bmatrix}
 \begin{bmatrix} 4&3&2 \end{bmatrix} + 
 \begin{bmatrix} 3\\ 6\\ 9 \end{bmatrix}
 \begin{bmatrix} 1&-1&1 \end{bmatrix}
$$

$$
\begin{bmatrix}    
  1& 2& 3\\
  4 &5 &6\\
  7 &8& 9
\end{bmatrix}
\begin{bmatrix}
   1&  2&  0\\
   4&  3&  2\\
   1& -1&  1
 \end{bmatrix}=\\
 \begin{bmatrix}
   1 \begin{bmatrix} 1\\ 4\\ 7\end{bmatrix}+
   4 \begin{bmatrix} 2\\ 5\\ 8\end{bmatrix}+
   1 \begin{bmatrix} 3\\ 6\\ 9\end{bmatrix} &
   2 \begin{bmatrix} 1\\ 4\\ 7\end{bmatrix}+
   3 \begin{bmatrix} 2\\ 5\\ 8\end{bmatrix}+
   (-1) \begin{bmatrix} 3\\ 6\\ 9\end{bmatrix} &
   0 \begin{bmatrix} 1\\ 4\\ 7\end{bmatrix}+
   2 \begin{bmatrix} 2\\ 5\\ 8\end{bmatrix}+
   1 \begin{bmatrix} 3\\ 6\\ 9\end{bmatrix}
 \end{bmatrix}
$$


In [1]:
n=5
A=ones(5,5)
B=ones(5,5)
C=zeros(n,n)
for i=1:n
    for j=1:n
        for k=1:n
            C[i,j]=C[i,j]+A[i,k]*A[k,j]
        end
    end
end
C

5x5 Array{Float64,2}:
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0

In [2]:
# _dot
for i=1:n
    for j=1:n
        @show C[i,j]=(A[i,:]*B[:,j])[]
    end
end

C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0
C[i,j] = (A[i,:] * B[:,j])[] => 5.0


In [3]:
# _syrk
C=zeros(n,n)
for i=1:n
    @show C=C+A[:,i]*A[i,:]
end

C = C + A[:,i] * A[i,:] => [1.0 1.0 1.0 1.0 1.0
 1.0 1.0 1.0 1.0 1.0
 1.0 1.0 1.0 1.0 1.0
 1.0 1.0 1.0 1.0 1.0
 1.0 1.0 1.0 1.0 1.0]
C = C + A[:,i] * A[i,:] => [2.0 2.0 2.0 2.0 2.0
 2.0 2.0 2.0 2.0 2.0
 2.0 2.0 2.0 2.0 2.0
 2.0 2.0 2.0 2.0 2.0
 2.0 2.0 2.0 2.0 2.0]
C = C + A[:,i] * A[i,:] => [3.0 3.0 3.0 3.0 3.0
 3.0 3.0 3.0 3.0 3.0
 3.0 3.0 3.0 3.0 3.0
 3.0 3.0 3.0 3.0 3.0
 3.0 3.0 3.0 3.0 3.0]
C = C + A[:,i] * A[i,:] => [4.0 4.0 4.0 4.0 4.0
 4.0 4.0 4.0 4.0 4.0
 4.0 4.0 4.0 4.0 4.0
 4.0 4.0 4.0 4.0 4.0
 4.0 4.0 4.0 4.0 4.0]
C = C + A[:,i] * A[i,:] => [5.0 5.0 5.0 5.0 5.0
 5.0 5.0 5.0 5.0 5.0
 5.0 5.0 5.0 5.0 5.0
 5.0 5.0 5.0 5.0 5.0
 5.0 5.0 5.0 5.0 5.0]


In [4]:
# _axpy
C=zeros(n,n)
for i=1:n
    for k=1:n
        C[:,i]=C[:,i]+A[:,k]*B[k,i]
    end
    @show c
end

LoadError: c not defined
while loading In[4], in expression starting on line 3

## Basic Linear Algrbea Subroutines - BLAS

Na primjer, `ddot.f` from _NetLib_

Uočite _loop unrolling_

```
DOUBLE PRECISION FUNCTION DDOT(N,DX,INCX,DY,INCY)
*     .. Scalar Arguments ..
      INTEGER INCX,INCY,N
*     ..
*     .. Array Arguments ..
      DOUBLE PRECISION DX(*),DY(*)
*     ..
*
*  Purpose
*  =======
*
*     forms the dot product of two vectors.
*     uses unrolled loops for increments equal to one.
*     jack dongarra, linpack, 3/11/78.
*     modified 12/3/93, array(1) declarations changed to array(*)
*
*
*     .. Local Scalars ..
      DOUBLE PRECISION DTEMP
      INTEGER I,IX,IY,M,MP1
*     ..
*     .. Intrinsic Functions ..
      INTRINSIC MOD
*     ..
      DDOT = 0.0d0
      DTEMP = 0.0d0
      IF (N.LE.0) RETURN
      IF (INCX.EQ.1 .AND. INCY.EQ.1) GO TO 20
*
*        code for unequal increments or equal increments
*          not equal to 1
*
      IX = 1
      IY = 1
      IF (INCX.LT.0) IX = (-N+1)*INCX + 1
      IF (INCY.LT.0) IY = (-N+1)*INCY + 1
      DO 10 I = 1,N
          DTEMP = DTEMP + DX(IX)*DY(IY)
          IX = IX + INCX
          IY = IY + INCY
   10 CONTINUE
      DDOT = DTEMP
      RETURN
*
*        code for both increments equal to 1
*
*
*        clean-up loop
*
   20 M = MOD(N,5)
      IF (M.EQ.0) GO TO 40
      DO 30 I = 1,M
          DTEMP = DTEMP + DX(I)*DY(I)
   30 CONTINUE
      IF (N.LT.5) GO TO 60
   40 MP1 = M + 1
      DO 50 I = MP1,N,5
          DTEMP = DTEMP + DX(I)*DY(I) + DX(I+1)*DY(I+1) +
     +            DX(I+2)*DY(I+2) + DX(I+3)*DY(I+3) + DX(I+4)*DY(I+4)
   50 CONTINUE
   60 DDOT = DTEMP
      RETURN
      END
```


## Brzina

In [58]:
function AB{T}(A::Array{T},B::Array{T})
    n=maximum(size(A))
    # C=zeros(n,n)
    C=[zeros(A[1,1]) for i=1:n, j=1:n]
    for i=1:n
        for j=1:n
            for k=1:n
                C[i,j]=C[i,j]+(A[i,k]*B[k,j])[]
            end
        end
    end
    C
end

AB (generic function with 1 method)

In [51]:
n=100
A=rand(n,n)
B=rand(n,n)

100x100 Array{Float64,2}:
 0.511589   0.760529  0.647323   …  0.356745   0.652889   0.862349 
 0.110614   0.827552  0.876892      0.920042   0.108556   0.90584  
 0.276463   0.893464  0.410662      0.961285   0.580317   0.76955  
 0.609009   0.973912  0.323933      0.669161   0.80924    0.251189 
 0.641693   0.708929  0.844763      0.341669   0.280555   0.108278 
 0.759774   0.636442  0.807089   …  0.571491   0.858746   0.676957 
 0.366118   0.716423  0.542553      0.484463   0.736794   0.103351 
 0.307768   0.773617  0.87171       0.0687062  0.96458    0.517434 
 0.987694   0.171585  0.461027      0.989528   0.593142   0.165842 
 0.484751   0.495485  0.193522      0.0985061  0.703039   0.505927 
 0.180468   0.501967  0.33542    …  0.996573   0.584011   0.887046 
 0.0393713  0.929034  0.0290025     0.144255   0.307976   0.730211 
 0.560514   0.15783   0.0438902     0.561093   0.440438   0.359522 
 ⋮                               ⋱                                 
 0.782831   0.720181  

In [52]:
@time C=A*B

elapsed time: 0.006135705 seconds (80160 bytes allocated)


100x100 Array{Float64,2}:
 26.99    28.167   25.1423  24.9176  …  24.1629  25.1994  24.2679  25.1705
 28.0482  31.1952  25.8012  26.9201     27.0867  26.2732  24.8124  24.8581
 26.6097  28.3429  24.414   25.0853     23.7929  24.0577  23.7951  24.3807
 27.6527  29.8279  26.7661  25.326      24.4097  24.51    24.2569  24.5229
 26.8721  27.9655  26.4351  25.4146     23.8809  25.3145  24.3789  23.8894
 24.9488  25.1169  25.3477  24.3692  …  22.9758  22.1073  21.6166  22.5163
 24.7224  27.1906  24.0812  22.8383     22.1703  23.8019  22.6132  23.1473
 27.0138  27.6711  25.5806  24.4764     23.0897  23.4442  23.4585  23.1104
 27.8141  28.988   27.5712  24.9026     24.8154  26.7835  25.4514  29.5548
 27.76    28.3015  27.2248  25.2295     24.0389  24.3721  23.6617  25.054 
 27.2037  27.257   26.24    26.1698  …  25.5228  26.0959  26.179   26.2447
 27.0442  29.9207  27.4927  26.7485     23.8408  25.3542  27.044   25.7804
 25.4141  29.7179  25.4705  24.493      25.4337  25.5016  24.9267  24.7118

In [62]:
operacija_u_sekundi=(2*n^3)/0.07

2.8571428571428567e7

In [63]:
@time AB(A,B);

LoadError: `Array{T,N}` has no method matching Array{T,N}(::Type{Float64}, ::Float64)
while loading In[63], in expression starting on line 56

In [64]:
Ab=[rand(32,32) for i=1:8, j=1:8]
Bb=[rand(32,32) for i=1:8, j=1:8];

In [65]:
@time AB(Ab,Bb);

elapsed time: 0.035610333 seconds (8999664 bytes allocated, 82.20% gc time)


## Točnost

__Apsloutna pogreška__
$$|fl(x\cdot y)-x\cdot y|\leq O(n\varepsilon) |x|\cdot |y|$$

__Relativna pogreška__
$$\frac{|fl(x\cdot y)-x\cdot y|}{|x\cdot y|}\leq O(n\varepsilon) \frac{|x|\cdot |y|}{|x\cdot y|}$$


In [99]:
n=1000000
x=rand(n)
j=int(rand(n)-0.5.<0.0)
y=rand(n)-0.5

1000000-element Array{Float64,1}:
 -0.380272 
  0.351492 
 -0.0199727
  0.484073 
 -0.367944 
  0.185128 
  0.0787329
 -0.277681 
 -0.096651 
  0.0530972
  0.0537208
 -0.0711645
  0.198102 
  ⋮        
  0.243286 
 -0.196278 
  0.427288 
  0.15746  
  0.398385 
  0.0167999
 -0.344971 
  0.307159 
  0.0687675
  0.259894 
  0.183248 
  0.0429108

In [100]:
d=x⋅y

30.214107751027516

In [101]:
ab=abs(x)⋅abs(y)

124896.36753637249

In [102]:
xb=[BigFloat(x[k]) for k=1:n]
yb=[BigFloat(y[k]) for k=1:n]

1000000-element Array{Any,1}:
 -3.8027218281144659073333968990482389926910400390625e-01  
  3.51492449177158050588332116603851318359375e-01          
 -1.9972713968886335322849845397286117076873779296875e-02  
  4.84073204765350428857573206187225878238677978515625e-01 
 -3.679443993068460816431297644157893955707550048828125e-01
  1.8512790849154026062706179800443351268768310546875e-01  
  7.873292585968538759289003792218863964080810546875e-02   
 -2.776810972467214089220988171291537582874298095703125e-01
 -9.66510497969108595128773231408558785915374755859375e-02 
  5.30971799275701261677795628202147781848907470703125e-02 
  5.3720817858211145079394555068574845790863037109375e-02  
 -7.11645410518626508888928583473898470401763916015625e-02 
  1.98101652009682549504532289574854075908660888671875e-01 
  ⋮                                                        
  2.43286127277337893559661097242496907711029052734375e-01 
 -1.962777617655977469013350855675525963306427001953125e-01
  4.272876

In [103]:
db=xb⋅yb

3.021410775102717251353050301485621373724427587522307362555493690826902142276822e+01 with 256 bits of precision

In [104]:
abserr=abs(d-db)

3.43488765166735454266857390733890401926374445063091730978577231780946021899581e-13 with 256 bits of precision

In [105]:
relerr=abserr/d

1.136848944861044752964716228617138591593382871333367386123886581835564449382384e-14 with 256 bits of precision