# Množenje matrica

---

Matrice možemo množiti na __tri različita načina__: 

\begin{align*}
\begin{bmatrix}    
1& 2& 3\\
  4 &5 &6\\
  7 &8& 9
\end{bmatrix}
\begin{bmatrix}
   1&  2&  0\\
   4&  3&  2\\
   1& -1&  1
 \end{bmatrix}&=
 \begin{bmatrix}
   (1\cdot 1 + 2\cdot 4+3\cdot 1) & 1\cdot 2+2\cdot 3+3\cdot(-1))&  
    (1\cdot 0 + 2\cdot 2 + 3\cdot 1)\\
   (4\cdot 1+5\cdot 5+6\cdot 1) & (4\cdot 2+5\cdot 3+6\cdot (-1)) &  
   (4\cdot 0+5\cdot 2+6\cdot 1)\\
   (7\cdot 1+8\cdot 5+9\cdot 1) & (7\cdot 2+8\cdot 3+9\cdot (-1)) &  
   (7\cdot 0+8\cdot 2+9\cdot 1)
 \end{bmatrix} \\ \\
\begin{bmatrix}    
  1& 2& 3\\
  4 &5 &6\\
  7 &8& 9
\end{bmatrix}
\begin{bmatrix}
   1&  2&  0\\
   4&  3&  2\\
   1& -1&  1
 \end{bmatrix}& =
 \begin{bmatrix} 1\\ 4\\ 7 \end{bmatrix}
 \begin{bmatrix} 1&2&0 \end{bmatrix} + 
 \begin{bmatrix} 2\\ 5\\ 8 \end{bmatrix}
 \begin{bmatrix} 4&3&2 \end{bmatrix} + 
 \begin{bmatrix} 3\\ 6\\ 9 \end{bmatrix}
 \begin{bmatrix} 1&-1&1 \end{bmatrix}\\ \\
\begin{bmatrix}    
  1& 2& 3\\
  4 &5 &6\\
  7 &8& 9
\end{bmatrix}
\begin{bmatrix}
   1&  2&  0\\
   4&  3&  2\\
   1& -1&  1
 \end{bmatrix}&=
 \begin{bmatrix}
   1 \begin{bmatrix} 1\\ 4\\ 7\end{bmatrix}+
   4 \begin{bmatrix} 2\\ 5\\ 8\end{bmatrix}+
   1 \begin{bmatrix} 3\\ 6\\ 9\end{bmatrix} &
   2 \begin{bmatrix} 1\\ 4\\ 7\end{bmatrix}+
   3 \begin{bmatrix} 2\\ 5\\ 8\end{bmatrix}+
   (-1) \begin{bmatrix} 3\\ 6\\ 9\end{bmatrix} &
   0 \begin{bmatrix} 1\\ 4\\ 7\end{bmatrix}+
   2 \begin{bmatrix} 2\\ 5\\ 8\end{bmatrix}+
   1 \begin{bmatrix} 3\\ 6\\ 9\end{bmatrix}
 \end{bmatrix}
\end{align*}

Formule se razlikuju u načinu prisutupa memoriji pa stoga i po brzini te u pogreškama zaokruživanja.

In [1]:
n=5
A=ones(5,5)
B=ones(5,5)
C=zeros(n,n)
for i=1:n
    for j=1:n
        for k=1:n
            C[i,j]=C[i,j]+A[i,k]*A[k,j]
        end
    end
end
C

5×5 Array{Float64,2}:
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0

In [4]:
# Ili, krace: _dot
for i=1:n
    for j=1:n
        @show C[i,j]=(A[i,:]⋅B[:,j])[]
    end
end

C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0


In [5]:
C=zeros(n,n)
for k=1:n
    for j=1:n
        for i=1:n
            C[i,j]=C[i,j]+A[i,k]*A[k,j]
            @show i,j,C[i,j]
        end
    end
end

(i,j,C[i,j]) = (1,1,1.0)
(i,j,C[i,j]) = (2,1,1.0)
(i,j,C[i,j]) = (3,1,1.0)
(i,j,C[i,j]) = (4,1,1.0)
(i,j,C[i,j]) = (5,1,1.0)
(i,j,C[i,j]) = (1,2,1.0)
(i,j,C[i,j]) = (2,2,1.0)
(i,j,C[i,j]) = (3,2,1.0)
(i,j,C[i,j]) = (4,2,1.0)
(i,j,C[i,j]) = (5,2,1.0)
(i,j,C[i,j]) = (1,3,1.0)
(i,j,C[i,j]) = (2,3,1.0)
(i,j,C[i,j]) = (3,3,1.0)
(i,j,C[i,j]) = (4,3,1.0)
(i,j,C[i,j]) = (5,3,1.0)
(i,j,C[i,j]) = (1,4,1.0)
(i,j,C[i,j]) = (2,4,1.0)
(i,j,C[i,j]) = (3,4,1.0)
(i,j,C[i,j]) = (4,4,1.0)
(i,j,C[i,j]) = (5,4,1.0)
(i,j,C[i,j]) = (1,5,1.0)
(i,j,C[i,j]) = (2,5,1.0)
(i,j,C[i,j]) = (3,5,1.0)
(i,j,C[i,j]) = (4,5,1.0)
(i,j,C[i,j]) = (5,5,1.0)
(i,j,C[i,j]) = (1,1,2.0)
(i,j,C[i,j]) = (2,1,2.0)
(i,j,C[i,j]) = (3,1,2.0)
(i,j,C[i,j]) = (4,1,2.0)
(i,j,C[i,j]) = (5,1,2.0)
(i,j,C[i,j]) = (1,2,2.0)
(i,j,C[i,j]) = (2,2,2.0)
(i,j,C[i,j]) = (3,2,2.0)
(i,j,C[i,j]) = (4,2,2.0)
(i,j,C[i,j]) = (5,2,2.0)
(i,j,C[i,j]) = (1,3,2.0)
(i,j,C[i,j]) = (2,3,2.0)
(i,j,C[i,j]) = (3,3,2.0)
(i,j,C[i,j]) = (4,3,2.0)
(i,j,C[i,j]) = (5,3,2.0)


In [8]:
# Ili, krace: _syrk
C=zeros(n,n)
for i=1:n
    @show C=C+A[:,i]*A[i,:]'
end

C = C + A[:,i] * (A[i,:])' = [1.0 1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0 1.0]
C = C + A[:,i] * (A[i,:])' = [2.0 2.0 2.0 2.0 2.0; 2.0 2.0 2.0 2.0 2.0; 2.0 2.0 2.0 2.0 2.0; 2.0 2.0 2.0 2.0 2.0; 2.0 2.0 2.0 2.0 2.0]
C = C + A[:,i] * (A[i,:])' = [3.0 3.0 3.0 3.0 3.0; 3.0 3.0 3.0 3.0 3.0; 3.0 3.0 3.0 3.0 3.0; 3.0 3.0 3.0 3.0 3.0; 3.0 3.0 3.0 3.0 3.0]
C = C + A[:,i] * (A[i,:])' = [4.0 4.0 4.0 4.0 4.0; 4.0 4.0 4.0 4.0 4.0; 4.0 4.0 4.0 4.0 4.0; 4.0 4.0 4.0 4.0 4.0; 4.0 4.0 4.0 4.0 4.0]
C = C + A[:,i] * (A[i,:])' = [5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0]


In [9]:
C=zeros(n,n)
for j=1:n
    for k=1:n
        for i=1:n
            C[i,j]=C[i,j]+A[i,k]*A[k,j]
            @show i,j,C[i,j]
        end
    end
end

(i,j,C[i,j]) = (1,1,1.0)
(i,j,C[i,j]) = (2,1,1.0)
(i,j,C[i,j]) = (3,1,1.0)
(i,j,C[i,j]) = (4,1,1.0)
(i,j,C[i,j]) = (5,1,1.0)
(i,j,C[i,j]) = (1,1,2.0)
(i,j,C[i,j]) = (2,1,2.0)
(i,j,C[i,j]) = (3,1,2.0)
(i,j,C[i,j]) = (4,1,2.0)
(i,j,C[i,j]) = (5,1,2.0)
(i,j,C[i,j]) = (1,1,3.0)
(i,j,C[i,j]) = (2,1,3.0)
(i,j,C[i,j]) = (3,1,3.0)
(i,j,C[i,j]) = (4,1,3.0)
(i,j,C[i,j]) = (5,1,3.0)
(i,j,C[i,j]) = (1,1,4.0)
(i,j,C[i,j]) = (2,1,4.0)
(i,j,C[i,j]) = (3,1,4.0)
(i,j,C[i,j]) = (4,1,4.0)
(i,j,C[i,j]) = (5,1,4.0)
(i,j,C[i,j]) = (1,1,5.0)
(i,j,C[i,j]) = (2,1,5.0)
(i,j,C[i,j]) = (3,1,5.0)
(i,j,C[i,j]) = (4,1,5.0)
(i,j,C[i,j]) = (5,1,5.0)
(i,j,C[i,j]) = (1,2,1.0)
(i,j,C[i,j]) = (2,2,1.0)
(i,j,C[i,j]) = (3,2,1.0)
(i,j,C[i,j]) = (4,2,1.0)
(i,j,C[i,j]) = (5,2,1.0)
(i,j,C[i,j]) = (1,2,2.0)
(i,j,C[i,j]) = (2,2,2.0)
(i,j,C[i,j]) = (3,2,2.0)
(i,j,C[i,j]) = (4,2,2.0)
(i,j,C[i,j]) = (5,2,2.0)
(i,j,C[i,j]) = (1,2,3.0)
(i,j,C[i,j]) = (2,2,3.0)
(i,j,C[i,j]) = (3,2,3.0)
(i,j,C[i,j]) = (4,2,3.0)
(i,j,C[i,j]) = (5,2,3.0)


In [10]:
# _axpy
C=zeros(n,n)
for i=1:n
    for k=1:n
        C[:,i]=C[:,i]+A[:,k]*B[k,i]
    end
    @show C
end

C = [5.0 0.0 0.0 0.0 0.0; 5.0 0.0 0.0 0.0 0.0; 5.0 0.0 0.0 0.0 0.0; 5.0 0.0 0.0 0.0 0.0; 5.0 0.0 0.0 0.0 0.0]
C = [5.0 5.0 0.0 0.0 0.0; 5.0 5.0 0.0 0.0 0.0; 5.0 5.0 0.0 0.0 0.0; 5.0 5.0 0.0 0.0 0.0; 5.0 5.0 0.0 0.0 0.0]
C = [5.0 5.0 5.0 0.0 0.0; 5.0 5.0 5.0 0.0 0.0; 5.0 5.0 5.0 0.0 0.0; 5.0 5.0 5.0 0.0 0.0; 5.0 5.0 5.0 0.0 0.0]
C = [5.0 5.0 5.0 5.0 0.0; 5.0 5.0 5.0 5.0 0.0; 5.0 5.0 5.0 5.0 0.0; 5.0 5.0 5.0 5.0 0.0; 5.0 5.0 5.0 5.0 0.0]
C = [5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0]


## Basic Linear Algrbea Subroutines - [BLAS](http://www.netlib.org/blas/)

Na primjer, [`ddot.f`](http://www.netlib.org/lapack/explore-html/d5/df6/ddot_8f_source.html) - uočite _loop unrolling_:

```
DOUBLE PRECISION FUNCTION DDOT(N,DX,INCX,DY,INCY)
*     .. Scalar Arguments ..
      INTEGER INCX,INCY,N
*     ..
*     .. Array Arguments ..
      DOUBLE PRECISION DX(*),DY(*)
*     ..
*
*  Purpose
*  =======
*
*     forms the dot product of two vectors.
*     uses unrolled loops for increments equal to one.
*     jack dongarra, linpack, 3/11/78.
*     modified 12/3/93, array(1) declarations changed to array(*)
*
*
*     .. Local Scalars ..
      DOUBLE PRECISION DTEMP
      INTEGER I,IX,IY,M,MP1
*     ..
*     .. Intrinsic Functions ..
      INTRINSIC MOD
*     ..
      DDOT = 0.0d0
      DTEMP = 0.0d0
      IF (N.LE.0) RETURN
      IF (INCX.EQ.1 .AND. INCY.EQ.1) GO TO 20
*
*        code for unequal increments or equal increments
*          not equal to 1
*
      IX = 1
      IY = 1
      IF (INCX.LT.0) IX = (-N+1)*INCX + 1
      IF (INCY.LT.0) IY = (-N+1)*INCY + 1
      DO 10 I = 1,N
          DTEMP = DTEMP + DX(IX)*DY(IY)
          IX = IX + INCX
          IY = IY + INCY
   10 CONTINUE
      DDOT = DTEMP
      RETURN
*
*        code for both increments equal to 1
*
*
*        clean-up loop
*
   20 M = MOD(N,5)
      IF (M.EQ.0) GO TO 40
      DO 30 I = 1,M
          DTEMP = DTEMP + DX(I)*DY(I)
   30 CONTINUE
      IF (N.LT.5) GO TO 60
   40 MP1 = M + 1
      DO 50 I = MP1,N,5
          DTEMP = DTEMP + DX(I)*DY(I) + DX(I+1)*DY(I+1) +
     +            DX(I+2)*DY(I+2) + DX(I+3)*DY(I+3) + DX(I+4)*DY(I+4)
   50 CONTINUE
   60 DDOT = DTEMP
      RETURN
      END
```


## Brzina

In [11]:
function AB{T}(A::Array{T},B::Array{T})
    n=maximum(size(A))
    C=zeros(n,n)
    # C=[zeros(A[1,1]) for i=1:n, j=1:n]
    for i=1:n
        for j=1:n
            for k=1:n
                C[i,j]=C[i,j]+(A[i,k]*B[k,j])[]
            end
        end
    end
    C
end

AB (generic function with 1 method)

In [12]:
n=512
A=rand(n,n)
B=rand(n,n)

512×512 Array{Float64,2}:
 0.232789    0.091186  0.984363   …  0.939331   0.450222    0.372043 
 0.467557    0.921048  0.20794       0.499477   0.741836    0.606268 
 0.829947    0.793203  0.717219      0.564078   0.91599     0.327769 
 0.230399    0.212575  0.0935441     0.201215   0.0947762   0.580407 
 0.580451    0.234676  0.880451      0.696022   0.608738    0.2872   
 0.551655    0.473047  0.90528    …  0.891669   0.392719    0.899343 
 0.43023     0.160459  0.562356      0.882188   0.843364    0.689068 
 0.0704332   0.279321  0.0422964     0.783833   0.622459    0.382652 
 0.870728    0.115482  0.213917      0.993564   0.165715    0.693995 
 0.303079    0.494402  0.268903      0.39052    0.456154    0.155266 
 0.484301    0.971327  0.416298   …  0.912691   0.704566    0.885353 
 0.987751    0.731912  0.714253      0.0142451  0.449079    0.767636 
 0.518172    0.548378  0.314647      0.273179   0.635177    0.891287 
 ⋮                                ⋱             ⋮               

In [18]:
# Izvedite 2 puta, releventno je drugo mjerenje.
@time C=A*B

  0.017149 seconds (7 allocations: 2.000 MB)


512×512 Array{Float64,2}:
 117.867  129.802  127.748  127.549  …  128.623  128.797  127.624  123.429
 126.644  128.792  129.048  132.168     135.211  131.599  124.875  128.762
 123.888  137.627  129.353  132.389     131.814  132.502  131.074  132.588
 126.2    134.209  130.44   132.568     129.732  131.815  131.836  131.081
 122.495  131.901  126.048  128.787     124.763  129.514  127.025  126.021
 127.569  135.792  126.68   127.569  …  130.294  130.981  129.868  132.078
 120.107  131.389  129.893  134.749     130.131  127.824  124.822  130.81 
 119.736  129.359  125.201  130.158     129.889  130.881  125.935  126.349
 116.685  125.662  125.144  119.922     122.557  126.105  121.297  122.924
 125.01   133.459  128.803  131.532     129.529  131.89   128.988  133.717
 121.678  130.668  128.139  125.256  …  132.228  135.117  126.934  127.464
 119.904  130.658  127.045  126.579     124.442  129.565  125.657  126.228
 119.163  128.633  127.925  127.376     126.224  126.592  125.065  130.142

In [15]:
operacija_u_sekundi=(2*n^3)/0.012

2.2369621333333332e10

In [17]:
# Izvedite 2 puta, releventno je drugo mjerenje. Izvodjenje nadeg programa je znacajno sporije!! 
@time AB(A,B);

  0.439797 seconds (10 allocations: 2.000 MB)


### Blok varijanta

Da bi ubrzali naš program, potrebno je računati s blok-matricama:

In [20]:
function AB{T}(A::Array{T},B::Array{T})
    n=maximum(size(A))
    # C=zeros(n,n)
    C=[zeros(A[1,1]) for i=1:n, j=1:n]
    for i=1:n
        for j=1:n
            for k=1:n
                C[i,j]=C[i,j]+(A[i,k]*B[k,j])[]
            end
        end
    end
    C
end

AB (generic function with 1 method)

In [22]:
# Probajte k,l=32,16 i k,l=64,8. Izvedite dva puta.
k,l=64,8
Ab=[rand(k,k) for i=1:l, j=1:l]
Bb=[rand(k,k) for i=1:l, j=1:l];

In [24]:
# Ovo je bitno brze
@time C=AB(Ab,Bb);

  0.042803 seconds (2.70 k allocations: 34.100 MB, 9.38% gc time)


## Točnost

__Apsloutna pogreška__:

$$|fl(x\cdot y)-x\cdot y|\leq O(n\varepsilon) |x|\cdot |y| \tag{1}$$

__Relativna pogreška__:

$$\frac{|fl(x\cdot y)-x\cdot y|}{|x\cdot y|}\leq O(n\varepsilon) \frac{|x|\cdot |y|}{|x\cdot y|}$$


In [25]:
n=1000000
x=rand(n)
j=round(Int64,(rand(n)-0.5.<0.0))
y=rand(n)-0.5

1000000-element Array{Float64,1}:
  0.0457887  
 -0.0250312  
 -0.356152   
  0.30661    
  0.451347   
  0.0952762  
  0.0756716  
 -0.365838   
  0.251745   
  0.346085   
  0.0529502  
  0.318044   
 -0.492925   
  ⋮          
 -0.492378   
  0.0726155  
 -0.000916732
 -0.233607   
 -0.269071   
 -0.190727   
 -0.141026   
  0.161134   
  0.351356   
 -0.328234   
  0.412639   
 -0.0998758  

In [26]:
d=x⋅y

63.48147555646063

In [27]:
ab=abs(x)⋅abs(y)

124978.62715979619

In [28]:
# provjerimo rješenje pomocu `BigFloat` brojeva (70tak tocnih znamenki)
xbig=map(BigFloat,x)
ybig=map(BigFloat,y)

1000000-element Array{BigFloat,1}:
  4.578871697546960106706137594301253557205200195312500000000000000000000000000000e-02
 -2.503121289418652750669025408569723367691040039062500000000000000000000000000000e-02
 -3.561523853957893059885009279241785407066345214843750000000000000000000000000000e-01
  3.066095551552545650508818653179332613945007324218750000000000000000000000000000e-01
  4.513469287297930954139246750855818390846252441406250000000000000000000000000000e-01
  9.527616123833126948738936334848403930664062500000000000000000000000000000000000e-02
  7.567155127905089706530361581826582551002502441406250000000000000000000000000000e-02
 -3.658377639746408505061481264419853687286376953125000000000000000000000000000000e-01
  2.517452067589405206859964891918934881687164306640625000000000000000000000000000e-01
  3.460851266313007545960545030538924038410186767578125000000000000000000000000000e-01
  5.295015515886158929959037777734920382499694824218750000000000000000000000000000e-02
  3.1804

In [29]:
dbig=xbig⋅ybig

6.348147555646157272216434544748506455587545219158925170147028281195100696265854e+01

In [30]:
abserr=abs(d-dbig)

9.426058021916621818295018593389103392517014702828119510069626585391233675181866e-13

In [31]:
relerr=abserr/d

1.484851752308916521926215412840884045740884315089156045597289996026772880670904e-14

### Za matrice

Iz formule (1) za matrice slijedi

$$ |fl(A\cdot B) -A\cdot B| \leq O(n\varepsilon) |A|\cdot |B|.$$ 

In [32]:
n=256
A=rand(n,n)
B=rand(n,n).-0.5

256×256 Array{Float64,2}:
  0.00572707   0.388335   -0.346641   …   0.352959   -0.445042     0.311015 
  0.384459     0.105432   -0.0637479      0.489143   -0.0800038    0.245706 
 -0.369157    -0.350275    0.33787        0.467564   -0.486989    -0.255525 
 -0.392765     0.0691517  -0.214522      -0.0227646  -0.45992      0.314942 
  0.428287     0.0164158  -0.449328      -0.450988    0.484217     0.423389 
  0.462398     0.0626327   0.363337   …   0.36374    -0.0644844   -0.3778   
  0.188386     0.337728   -0.415524       0.116981   -0.00267029  -0.146552 
 -0.424852    -0.232947   -0.203588       0.333838   -0.241846    -0.08463  
  0.158529     0.122033   -0.091738      -0.13808    -0.237032     0.382749 
 -0.142558     0.151853   -0.451054      -0.464299   -0.214157     0.482064 
  0.437642    -0.387024   -0.113912   …  -0.402182    0.0671069    0.106519 
 -0.292929    -0.46769     0.389098       0.148765   -0.191852     0.463807 
  0.422689     0.0314057  -0.257895       0.044909

In [33]:
Ab=[BigFloat(A[i,j]) for i=1:n, j=1:n]
Bb=[BigFloat(B[i,j]) for i=1:n, j=1:n]

256×256 Array{BigFloat,2}:
  5.727067652858686130912246881052851676940917968750000000000000000000000000000000e-03  …   3.110148888160080282716535293729975819587707519531250000000000000000000000000000e-01
  3.844592428749340484728236333467066287994384765625000000000000000000000000000000e-01      2.457057713662560427536618590238504111766815185546875000000000000000000000000000e-01
 -3.691574827210382103714891854906454682350158691406250000000000000000000000000000e-01     -2.555248491359440876635744643863290548324584960937500000000000000000000000000000e-01
 -3.927650297673144219601226723170839250087738037109375000000000000000000000000000e-01      3.149423539545690431395996711216866970062255859375000000000000000000000000000000e-01
  4.282869040883592326451889675809070467948913574218750000000000000000000000000000e-01      4.233885812870163967147618677699938416481018066406250000000000000000000000000000e-01
  4.623982408238769270525381216430105268955230712890625000000000000000000000000000e-01  

In [34]:
C=A*B
# ovo traje malo duze
Cb=Ab*Bb
abserr=abs(C-map(Float64,Cb))

256×256 Array{Float64,2}:
 1.77636e-15  0.0          8.88178e-16  …  8.88178e-16  1.33227e-15
 0.0          2.22045e-16  4.44089e-16     1.77636e-15  4.44089e-16
 3.55271e-15  0.0          1.77636e-15     2.66454e-15  0.0        
 0.0          8.88178e-16  5.55112e-16     8.88178e-16  8.88178e-16
 2.66454e-15  0.0          2.77556e-16     6.21725e-15  8.88178e-16
 0.0          8.88178e-16  0.0          …  4.44089e-16  1.22125e-15
 8.88178e-16  2.22045e-16  8.95117e-16     0.0          7.49401e-16
 8.88178e-16  4.44089e-16  1.77636e-15     4.44089e-16  6.66134e-16
 8.88178e-16  4.44089e-16  8.88178e-16     1.66533e-15  2.66454e-15
 3.55271e-15  4.44089e-16  6.9519e-16      2.22045e-16  4.44089e-16
 0.0          3.33067e-16  8.88178e-16  …  0.0          8.88178e-16
 8.88178e-16  1.33227e-15  1.33227e-15     1.11022e-15  1.55431e-15
 1.77636e-15  8.88178e-16  1.33227e-15     1.11022e-16  8.88178e-16
 ⋮                                      ⋱               ⋮          
 1.77636e-15  1.77636e

In [35]:
abs(A)*abs(B)*n*eps()

256×256 Array{Float64,2}:
 2.00148e-12  1.91676e-12  1.8862e-12   …  1.96596e-12  1.80028e-12
 2.04555e-12  1.88418e-12  1.92579e-12     1.9439e-12   1.84974e-12
 1.96616e-12  1.96874e-12  1.93084e-12     1.91622e-12  1.79481e-12
 1.97367e-12  1.79866e-12  1.80633e-12     1.85849e-12  1.74351e-12
 1.95711e-12  1.73031e-12  1.87746e-12     1.90071e-12  1.77695e-12
 2.02516e-12  1.87432e-12  1.85554e-12  …  1.88062e-12  1.78718e-12
 1.81298e-12  1.82002e-12  1.83158e-12     1.77752e-12  1.75124e-12
 1.93794e-12  1.82322e-12  1.79723e-12     1.81444e-12  1.74486e-12
 2.00287e-12  1.86002e-12  1.83864e-12     1.88822e-12  1.76563e-12
 1.98692e-12  1.91722e-12  1.78448e-12     1.87212e-12  1.77536e-12
 1.87892e-12  1.82529e-12  1.80509e-12  …  1.79282e-12  1.76164e-12
 1.9355e-12   1.85259e-12  1.86768e-12     1.8013e-12   1.79333e-12
 1.99434e-12  1.89865e-12  1.83643e-12     1.87064e-12  1.82555e-12
 ⋮                                      ⋱               ⋮          
 2.05464e-12  1.93067e

Ovdje nije lako razabrati relativnu pogrešku pa nam treba pogodnija mjera -> __matrične i vektorske norme__.