# Množenje matrica

---

Matrice možemo množiti na __tri različita načina__: 

\begin{align*}
\begin{bmatrix}    
1& 2& 3\\
  4 &5 &6\\
  7 &8& 9
\end{bmatrix}
\begin{bmatrix}
   1&  2&  0\\
   4&  3&  2\\
   1& -1&  1
 \end{bmatrix}&=
 \begin{bmatrix}
   (1\cdot 1 + 2\cdot 4+3\cdot 1) & 1\cdot 2+2\cdot 3+3\cdot(-1))&  
    (1\cdot 0 + 2\cdot 2 + 3\cdot 1)\\
   (4\cdot 1+5\cdot 5+6\cdot 1) & (4\cdot 2+5\cdot 3+6\cdot (-1)) &  
   (4\cdot 0+5\cdot 2+6\cdot 1)\\
   (7\cdot 1+8\cdot 5+9\cdot 1) & (7\cdot 2+8\cdot 3+9\cdot (-1)) &  
   (7\cdot 0+8\cdot 2+9\cdot 1)
 \end{bmatrix} \\ \\
\begin{bmatrix}    
  1& 2& 3\\
  4 &5 &6\\
  7 &8& 9
\end{bmatrix}
\begin{bmatrix}
   1&  2&  0\\
   4&  3&  2\\
   1& -1&  1
 \end{bmatrix}& =
 \begin{bmatrix} 1\\ 4\\ 7 \end{bmatrix}
 \begin{bmatrix} 1&2&0 \end{bmatrix} + 
 \begin{bmatrix} 2\\ 5\\ 8 \end{bmatrix}
 \begin{bmatrix} 4&3&2 \end{bmatrix} + 
 \begin{bmatrix} 3\\ 6\\ 9 \end{bmatrix}
 \begin{bmatrix} 1&-1&1 \end{bmatrix}\\ \\
\begin{bmatrix}    
  1& 2& 3\\
  4 &5 &6\\
  7 &8& 9
\end{bmatrix}
\begin{bmatrix}
   1&  2&  0\\
   4&  3&  2\\
   1& -1&  1
 \end{bmatrix}&=
 \begin{bmatrix}
   1 \begin{bmatrix} 1\\ 4\\ 7\end{bmatrix}+
   4 \begin{bmatrix} 2\\ 5\\ 8\end{bmatrix}+
   1 \begin{bmatrix} 3\\ 6\\ 9\end{bmatrix} &
   2 \begin{bmatrix} 1\\ 4\\ 7\end{bmatrix}+
   3 \begin{bmatrix} 2\\ 5\\ 8\end{bmatrix}+
   (-1) \begin{bmatrix} 3\\ 6\\ 9\end{bmatrix} &
   0 \begin{bmatrix} 1\\ 4\\ 7\end{bmatrix}+
   2 \begin{bmatrix} 2\\ 5\\ 8\end{bmatrix}+
   1 \begin{bmatrix} 3\\ 6\\ 9\end{bmatrix}
 \end{bmatrix}
\end{align*}

Formule se razlikuju u načinu prisutupa memoriji pa stoga i po brzini te u pogreškama zaokruživanja.

In [1]:
n=5
A=ones(5,5)
B=ones(5,5)
C=zeros(n,n)
for i=1:n
    for j=1:n
        for k=1:n
            C[i,j]=C[i,j]+A[i,k]*A[k,j]
        end
    end
end
C

5×5 Array{Float64,2}:
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0

In [2]:
# Ili, krace: _dot
for i=1:n
    for j=1:n
        @show C[i,j]=(A[i,:]⋅B[:,j])[]
    end
end

C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0
C[i,j] = (A[i,:] ⋅ B[:,j])[] = 5.0


In [3]:
C=zeros(n,n)
for k=1:n
    for j=1:n
        for i=1:n
            C[i,j]=C[i,j]+A[i,k]*A[k,j]
            @show i,j,C[i,j]
        end
    end
end

(i,j,C[i,j]) = (1,1,1.0)
(i,j,C[i,j]) = (2,1,1.0)
(i,j,C[i,j]) = (3,1,1.0)
(i,j,C[i,j]) = (4,1,1.0)
(i,j,C[i,j]) = (5,1,1.0)
(i,j,C[i,j]) = (1,2,1.0)
(i,j,C[i,j]) = (2,2,1.0)
(i,j,C[i,j]) = (3,2,1.0)
(i,j,C[i,j]) = (4,2,1.0)
(i,j,C[i,j]) = (5,2,1.0)
(i,j,C[i,j]) = (1,3,1.0)
(i,j,C[i,j]) = (2,3,1.0)
(i,j,C[i,j]) = (3,3,1.0)
(i,j,C[i,j]) = (4,3,1.0)
(i,j,C[i,j]) = (5,3,1.0)
(i,j,C[i,j]) = (1,4,1.0)
(i,j,C[i,j]) = (2,4,1.0)
(i,j,C[i,j]) = (3,4,1.0)
(i,j,C[i,j]) = (4,4,1.0)
(i,j,C[i,j]) = (5,4,1.0)
(i,j,C[i,j]) = (1,5,1.0)
(i,j,C[i,j]) = (2,5,1.0)
(i,j,C[i,j]) = (3,5,1.0)
(i,j,C[i,j]) = (4,5,1.0)
(i,j,C[i,j]) = (5,5,1.0)
(i,j,C[i,j]) = (1,1,2.0)
(i,j,C[i,j]) = (2,1,2.0)
(i,j,C[i,j]) = (3,1,2.0)
(i,j,C[i,j]) = (4,1,2.0)
(i,j,C[i,j]) = (5,1,2.0)
(i,j,C[i,j]) = (1,2,2.0)
(i,j,C[i,j]) = (2,2,2.0)
(i,j,C[i,j]) = (3,2,2.0)
(i,j,C[i,j]) = (4,2,2.0)
(i,j,C[i,j]) = (5,2,2.0)
(i,j,C[i,j]) = (1,3,2.0)
(i,j,C[i,j]) = (2,3,2.0)
(i,j,C[i,j]) = (3,3,2.0)
(i,j,C[i,j]) = (4,3,2.0)
(i,j,C[i,j]) = (5,3,2.0)


In [4]:
# Ili, krace: _syrk
C=zeros(n,n)
for i=1:n
    @show C=C+A[:,i]*A[i,:]'
end

C = C + A[:,i] * (A[i,:])' = [1.0 1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0 1.0]
C = C + A[:,i] * (A[i,:])' = [2.0 2.0 2.0 2.0 2.0; 2.0 2.0 2.0 2.0 2.0; 2.0 2.0 2.0 2.0 2.0; 2.0 2.0 2.0 2.0 2.0; 2.0 2.0 2.0 2.0 2.0]
C = C + A[:,i] * (A[i,:])' = [3.0 3.0 3.0 3.0 3.0; 3.0 3.0 3.0 3.0 3.0; 3.0 3.0 3.0 3.0 3.0; 3.0 3.0 3.0 3.0 3.0; 3.0 3.0 3.0 3.0 3.0]
C = C + A[:,i] * (A[i,:])' = [4.0 4.0 4.0 4.0 4.0; 4.0 4.0 4.0 4.0 4.0; 4.0 4.0 4.0 4.0 4.0; 4.0 4.0 4.0 4.0 4.0; 4.0 4.0 4.0 4.0 4.0]
C = C + A[:,i] * (A[i,:])' = [5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0]


In [5]:
C=zeros(n,n)
for j=1:n
    for k=1:n
        for i=1:n
            C[i,j]=C[i,j]+A[i,k]*A[k,j]
            @show i,j,C[i,j]
        end
    end
end

(i,j,C[i,j]) = (1,1,1.0)
(i,j,C[i,j]) = (2,1,1.0)
(i,j,C[i,j]) = (3,1,1.0)
(i,j,C[i,j]) = (4,1,1.0)
(i,j,C[i,j]) = (5,1,1.0)
(i,j,C[i,j]) = (1,1,2.0)
(i,j,C[i,j]) = (2,1,2.0)
(i,j,C[i,j]) = (3,1,2.0)
(i,j,C[i,j]) = (4,1,2.0)
(i,j,C[i,j]) = (5,1,2.0)
(i,j,C[i,j]) = (1,1,3.0)
(i,j,C[i,j]) = (2,1,3.0)
(i,j,C[i,j]) = (3,1,3.0)
(i,j,C[i,j]) = (4,1,3.0)
(i,j,C[i,j]) = (5,1,3.0)
(i,j,C[i,j]) = (1,1,4.0)
(i,j,C[i,j]) = (2,1,4.0)
(i,j,C[i,j]) = (3,1,4.0)
(i,j,C[i,j]) = (4,1,4.0)
(i,j,C[i,j]) = (5,1,4.0)
(i,j,C[i,j]) = (1,1,5.0)
(i,j,C[i,j]) = (2,1,5.0)
(i,j,C[i,j]) = (3,1,5.0)
(i,j,C[i,j]) = (4,1,5.0)
(i,j,C[i,j]) = (5,1,5.0)
(i,j,C[i,j]) = (1,2,1.0)
(i,j,C[i,j]) = (2,2,1.0)
(i,j,C[i,j]) = (3,2,1.0)
(i,j,C[i,j]) = (4,2,1.0)
(i,j,C[i,j]) = (5,2,1.0)
(i,j,C[i,j]) = (1,2,2.0)
(i,j,C[i,j]) = (2,2,2.0)
(i,j,C[i,j]) = (3,2,2.0)
(i,j,C[i,j]) = (4,2,2.0)
(i,j,C[i,j]) = (5,2,2.0)
(i,j,C[i,j]) = (1,2,3.0)
(i,j,C[i,j]) = (2,2,3.0)
(i,j,C[i,j]) = (3,2,3.0)
(i,j,C[i,j]) = (4,2,3.0)
(i,j,C[i,j]) = (5,2,3.0)


In [6]:
# _axpy
C=zeros(n,n)
for i=1:n
    for k=1:n
        C[:,i]=C[:,i]+A[:,k]*B[k,i]
    end
    @show C
end

C = [5.0 0.0 0.0 0.0 0.0; 5.0 0.0 0.0 0.0 0.0; 5.0 0.0 0.0 0.0 0.0; 5.0 0.0 0.0 0.0 0.0; 5.0 0.0 0.0 0.0 0.0]
C = [5.0 5.0 0.0 0.0 0.0; 5.0 5.0 0.0 0.0 0.0; 5.0 5.0 0.0 0.0 0.0; 5.0 5.0 0.0 0.0 0.0; 5.0 5.0 0.0 0.0 0.0]
C = [5.0 5.0 5.0 0.0 0.0; 5.0 5.0 5.0 0.0 0.0; 5.0 5.0 5.0 0.0 0.0; 5.0 5.0 5.0 0.0 0.0; 5.0 5.0 5.0 0.0 0.0]
C = [5.0 5.0 5.0 5.0 0.0; 5.0 5.0 5.0 5.0 0.0; 5.0 5.0 5.0 5.0 0.0; 5.0 5.0 5.0 5.0 0.0; 5.0 5.0 5.0 5.0 0.0]
C = [5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0]


## Basic Linear Algrbea Subroutines - [BLAS](http://www.netlib.org/blas/)

Na primjer, [`ddot.f`](http://www.netlib.org/lapack/explore-html/d5/df6/ddot_8f_source.html) - uočite _loop unrolling_:

```
DOUBLE PRECISION FUNCTION DDOT(N,DX,INCX,DY,INCY)
*     .. Scalar Arguments ..
      INTEGER INCX,INCY,N
*     ..
*     .. Array Arguments ..
      DOUBLE PRECISION DX(*),DY(*)
*     ..
*
*  Purpose
*  =======
*
*     forms the dot product of two vectors.
*     uses unrolled loops for increments equal to one.
*     jack dongarra, linpack, 3/11/78.
*     modified 12/3/93, array(1) declarations changed to array(*)
*
*
*     .. Local Scalars ..
      DOUBLE PRECISION DTEMP
      INTEGER I,IX,IY,M,MP1
*     ..
*     .. Intrinsic Functions ..
      INTRINSIC MOD
*     ..
      DDOT = 0.0d0
      DTEMP = 0.0d0
      IF (N.LE.0) RETURN
      IF (INCX.EQ.1 .AND. INCY.EQ.1) GO TO 20
*
*        code for unequal increments or equal increments
*          not equal to 1
*
      IX = 1
      IY = 1
      IF (INCX.LT.0) IX = (-N+1)*INCX + 1
      IF (INCY.LT.0) IY = (-N+1)*INCY + 1
      DO 10 I = 1,N
          DTEMP = DTEMP + DX(IX)*DY(IY)
          IX = IX + INCX
          IY = IY + INCY
   10 CONTINUE
      DDOT = DTEMP
      RETURN
*
*        code for both increments equal to 1
*
*
*        clean-up loop
*
   20 M = MOD(N,5)
      IF (M.EQ.0) GO TO 40
      DO 30 I = 1,M
          DTEMP = DTEMP + DX(I)*DY(I)
   30 CONTINUE
      IF (N.LT.5) GO TO 60
   40 MP1 = M + 1
      DO 50 I = MP1,N,5
          DTEMP = DTEMP + DX(I)*DY(I) + DX(I+1)*DY(I+1) +
     +            DX(I+2)*DY(I+2) + DX(I+3)*DY(I+3) + DX(I+4)*DY(I+4)
   50 CONTINUE
   60 DDOT = DTEMP
      RETURN
      END
```


## Brzina

In [7]:
function AB{T}(A::Array{T},B::Array{T})
    n=maximum(size(A))
    C=zeros(n,n)
    # C=[zeros(A[1,1]) for i=1:n, j=1:n]
    for i=1:n
        for j=1:n
            for k=1:n
                C[i,j]=C[i,j]+(A[i,k]*B[k,j])[]
            end
        end
    end
    C
end

AB (generic function with 1 method)

In [8]:
n=512
A=rand(n,n)
B=rand(n,n)

512×512 Array{Float64,2}:
 0.621639   0.595963   0.655223    …  0.234318   0.363904   0.341348 
 0.91882    0.548326   0.121848       0.305199   0.677099   0.253106 
 0.0677332  0.237517   0.444241       0.68608    0.789298   0.534425 
 0.270474   0.425897   0.829007       0.42685    0.654952   0.160351 
 0.778728   0.189521   0.0153992      0.443905   0.0999872  0.389512 
 0.110595   0.133419   0.566579    …  0.0396701  0.537755   0.0272079
 0.0567248  0.402099   0.412835       0.73191    0.406492   0.143099 
 0.926132   0.036805   0.064335       0.736652   0.784421   0.286256 
 0.191571   0.571804   0.789363       0.297134   0.184339   0.575926 
 0.266187   0.109247   0.368514       0.0165141  0.718605   0.788667 
 0.342074   0.484271   0.682834    …  0.129758   0.710491   0.447401 
 0.730726   0.49042    0.722322       0.76976    0.727817   0.0547249
 0.772642   0.40438    0.50152        0.467389   0.940072   0.655736 
 ⋮                                 ⋱             ⋮              

In [11]:
# Izvedite 2 puta, releventno je drugo mjerenje.
@time C=A*B

  0.007083 seconds (6 allocations: 2.000 MB)


512×512 Array{Float64,2}:
 124.995  127.767  124.845  132.321  …  131.279  132.647  132.667  129.551
 117.995  125.227  118.919  124.846     124.126  126.633  127.463  117.716
 118.812  123.684  118.985  123.295     121.702  121.923  123.367  120.19 
 121.117  125.901  120.361  129.027     124.636  126.606  125.081  121.524
 127.715  132.267  127.574  131.264     132.752  132.058  134.803  132.634
 122.056  131.275  129.758  132.257  …  128.702  129.916  129.555  128.381
 118.839  124.46   119.618  123.901     120.722  124.828  126.961  120.335
 123.755  127.233  122.398  127.389     126.832  130.695  127.047  125.24 
 121.438  121.265  121.348  125.959     124.118  127.972  131.873  122.36 
 122.02   124.215  124.927  127.994     127.924  127.33   124.385  123.085
 125.334  127.796  125.239  130.865  …  125.395  126.471  131.451  129.87 
 127.016  130.118  127.464  132.848     130.282  134.292  131.564  128.288
 130.135  130.114  130.967  135.336     128.469  131.816  135.112  128.696

In [14]:
operacija_u_sekundi=(2*n^3)/0.007

3.834792228571429e10

In [16]:
# Izvedite 2 puta, releventno je drugo mjerenje. Izvodjenje nadeg programa je znacajno sporije!! 
@time AB(A,B);

  0.434560 seconds (10 allocations: 2.000 MB)


### Blok varijanta

Da bi ubrzali naš program, potrebno je računati s blok-matricama:

In [17]:
function AB{T}(A::Array{T},B::Array{T})
    n=maximum(size(A))
    # C=zeros(n,n)
    C=[zeros(A[1,1]) for i=1:n, j=1:n]
    for i=1:n
        for j=1:n
            for k=1:n
                C[i,j]=C[i,j]+(A[i,k]*B[k,j])[]
            end
        end
    end
    C
end

AB (generic function with 1 method)

In [18]:
# Probajte k,l=32,16 i k,l=64,8. Izvedite dva puta.
k,l=64,8
Ab=[rand(k,k) for i=1:l, j=1:l]
Bb=[rand(k,k) for i=1:l, j=1:l];

In [20]:
# Ovo je bitno brze
@time C=AB(Ab,Bb);

  0.038810 seconds (2.18 k allocations: 34.084 MB, 10.57% gc time)


## Točnost

__Apsloutna pogreška__:

$$| fl(x\cdot y)-x\cdot y|\leq O(n\varepsilon) |x|\cdot |y| \tag{1}$$

__Relativna pogreška__:

$$\frac{|fl(x\cdot y)-x\cdot y|}{|x\cdot y|}\leq O(n\varepsilon) \frac{|x|\cdot |y|}{|x\cdot y|}$$


In [21]:
n=1000000
x=rand(n)
j=round(Int64,(rand(n)-0.5.<0.0))
y=rand(n)-0.5

1000000-element Array{Float64,1}:
 -0.0798526 
 -0.0735599 
  0.461912  
 -0.460573  
  0.376837  
 -0.410809  
 -0.378046  
  0.291321  
 -0.0778554 
  0.279566  
 -0.330661  
  0.324644  
  0.265865  
  ⋮         
 -0.293972  
 -0.279827  
  0.391165  
  0.0344962 
 -0.00671468
  0.346785  
 -0.401988  
 -0.172272  
 -0.362931  
 -0.179384  
 -0.0367548 
  0.250444  

In [22]:
d=x⋅y

11.435537669330401

In [23]:
ab=abs(x)⋅abs(y)

125036.8269139054

In [24]:
# provjerimo rješenje pomocu `BigFloat` brojeva (70tak tocnih znamenki)
xbig=map(BigFloat,x)
ybig=map(BigFloat,y)

1000000-element Array{BigFloat,1}:
 -7.985257408198043194147430767770856618881225585937500000000000000000000000000000e-02
 -7.355988682290481861514308548066765069961547851562500000000000000000000000000000e-02
  4.619118403601523148438445787178352475166320800781250000000000000000000000000000e-01
 -4.605734413447308828182258366723544895648956298828125000000000000000000000000000e-01
  3.768366474075131034027208443148992955684661865234375000000000000000000000000000e-01
 -4.108088124973623411761991519597359001636505126953125000000000000000000000000000e-01
 -3.780460159235505823716039230930618941783905029296875000000000000000000000000000e-01
  2.913208359144292547426857709069736301898956298828125000000000000000000000000000e-01
 -7.785538633387223406145949411438778042793273925781250000000000000000000000000000e-02
  2.795658557242690633870552119333297014236450195312500000000000000000000000000000e-01
 -3.306613183120732379904893605271354317665100097656250000000000000000000000000000e-01
  3.2464

In [25]:
dbig=xbig⋅ybig

1.143553766933048321963542755565279505846056549873506565644464927182510916026104e+01

In [26]:
abserr=abs(d-dbig)

8.227463513528800242922899279206123506565644464927182510916026103586773388087749e-14

In [27]:
relerr=abserr/d

7.194645106713686335462244037698370105579858332184680972562909866351291410064072e-15

### Za matrice

Iz formule (1) za matrice slijedi

$$ |fl(A\cdot B) -A\cdot B| \leq O(n\varepsilon) |A|\cdot |B|.$$ 

In [28]:
n=256
A=rand(n,n)
B=rand(n,n).-0.5

256×256 Array{Float64,2}:
  0.072906    0.123518     0.23831    …  -0.158548    -0.227463    0.435195 
  0.34931    -0.404327    -0.315035      -0.447072     0.284946    0.272281 
  0.313326   -0.0631612   -0.392143       0.14082     -0.302593   -0.105858 
  0.43455    -0.37419     -0.285804       0.00303524   0.169667    0.441509 
 -0.0561124   0.308995    -0.116316      -0.266953     0.0958903  -0.326876 
 -0.0459504   0.129262     0.437754   …  -0.160271     0.187784    0.289822 
  0.166342   -0.415934     0.0460977      0.308421     0.438029   -0.466965 
  0.235295   -0.333363    -0.176478      -0.270932    -0.420498   -0.469813 
  0.44895     0.3865      -0.161246       0.454931    -0.183901    0.269771 
  0.331348    0.192394     0.362794       0.299712    -0.456147   -0.218186 
 -0.409394   -0.152683    -0.263406   …  -0.275042    -0.490527   -0.0264723
  0.478029   -0.329544    -0.485646       0.20348     -0.327865    0.191981 
 -0.238452    0.495563    -0.495719       0.368445

In [29]:
Ab=[BigFloat(A[i,j]) for i=1:n, j=1:n]
Bb=[BigFloat(B[i,j]) for i=1:n, j=1:n]

256×256 Array{BigFloat,2}:
  7.290596303630403340889643004629760980606079101562500000000000000000000000000000e-02  …   4.351949307195488447774778251186944544315338134765625000000000000000000000000000e-01
  3.493099257595870810177984822075814008712768554687500000000000000000000000000000e-01      2.722806454474662185560873695067130029201507568359375000000000000000000000000000e-01
  3.133256521664735672061397053766995668411254882812500000000000000000000000000000e-01     -1.058577794590205289892992368550039827823638916015625000000000000000000000000000e-01
  4.345500339654582155901607620762661099433898925781250000000000000000000000000000e-01      4.415088844942178791797005033004097640514373779296875000000000000000000000000000e-01
 -5.611237851598427361921039846492931246757507324218750000000000000000000000000000e-02     -3.268759154791260890249304793542250990867614746093750000000000000000000000000000e-01
 -4.595040011206719121616970369359478354454040527343750000000000000000000000000000e-02  

In [30]:
C=A*B
# ovo traje malo duze
Cb=Ab*Bb
abserr=abs(C-map(Float64,Cb))

256×256 Array{Float64,2}:
 4.44089e-16  8.88178e-16  1.33227e-15  …  3.9968e-15   6.66134e-16
 2.22045e-16  1.77636e-15  8.88178e-16     1.77636e-15  1.77636e-15
 1.11022e-16  1.11022e-15  2.88658e-15     2.66454e-15  2.22045e-16
 1.33227e-15  8.88178e-16  2.22045e-16     1.33227e-15  8.88178e-16
 8.88178e-16  1.55431e-15  2.22045e-16     6.66134e-16  3.33067e-16
 8.88178e-16  8.88178e-16  1.16573e-15  …  8.88178e-16  2.77556e-16
 1.11022e-16  1.77636e-15  4.44089e-16     1.77636e-15  1.33227e-15
 1.11022e-16  6.66134e-16  2.66454e-15     8.88178e-16  6.66134e-16
 1.11022e-16  1.33227e-15  4.44089e-16     4.44089e-16  1.9984e-15 
 0.0          1.77636e-15  4.44089e-16     8.88178e-16  0.0        
 2.22045e-16  1.33227e-15  1.11022e-15  …  8.88178e-16  1.9984e-15 
 8.88178e-16  1.77636e-15  1.77636e-15     0.0          8.60423e-16
 5.27356e-16  2.22045e-16  1.22125e-15     8.88178e-15  7.77156e-16
 ⋮                                      ⋱               ⋮          
 3.60822e-16  1.33227e

In [31]:
abs(A)*abs(B)*n*eps()

256×256 Array{Float64,2}:
 1.72467e-12  1.95187e-12  1.72224e-12  …  1.70594e-12  1.81717e-12
 1.72666e-12  1.98701e-12  1.85542e-12     1.76174e-12  1.84922e-12
 1.78781e-12  2.07402e-12  1.92742e-12     1.82616e-12  1.93239e-12
 1.55379e-12  1.92474e-12  1.64245e-12     1.70857e-12  1.74532e-12
 1.65738e-12  1.96859e-12  1.83433e-12     1.80612e-12  1.91184e-12
 1.71746e-12  1.96039e-12  1.80482e-12  …  1.82337e-12  1.84748e-12
 1.62818e-12  1.87271e-12  1.73843e-12     1.66123e-12  1.68623e-12
 1.56691e-12  1.86206e-12  1.7755e-12      1.74585e-12  1.75146e-12
 1.57169e-12  1.85063e-12  1.63849e-12     1.67843e-12  1.74561e-12
 1.73617e-12  2.03143e-12  1.89724e-12     1.77764e-12  1.91057e-12
 1.57017e-12  1.82822e-12  1.63898e-12  …  1.66972e-12  1.66437e-12
 1.71521e-12  2.02219e-12  1.81673e-12     1.75459e-12  1.81995e-12
 1.77703e-12  1.98589e-12  1.89466e-12     1.81903e-12  1.81036e-12
 ⋮                                      ⋱               ⋮          
 1.73476e-12  1.93605e

Ovdje nije lako razabrati relativnu pogrešku pa nam treba pogodnija mjera -> __matrične i vektorske norme__.