# Gaussova eliminacija

## Općenito

Sustav $Ax=b$ se rješava u tri koraka (__bez pivotiranja__)

1. $A=LU$ (LU rastav, $O(\frac{2}{3}n^3)$ operacija)
2. $Ly=b$ (donje trokutrasti sustav, $n^2$ operacija)
3. $Ux=y$ (gornje torkutasti sustav, $n^2$ operacija)

Ukoliko pivotiramo, tada je

1. $PA=LU$ 
2. $Ly=P^T b$
3. $Ux=y$ 

## LU rastav

In [1]:
function mylu{T}(A1::Array{T}) # Strang, page 100
    A=deepcopy(A1)
    n,m=size(A)
    U=map(Float64,[zero(A[1,1]) for i=1:n, j=1:n]) # This acccepts blocks and numbers
    L=map(Float64,[zero(A[1,1]) for i=1:n, j=1:n])
    for k=1:n
        L[k,k]=one(A[1,1])
        for i=k+1:n
            L[i,k]=A[i,k]/A[k,k]
            for j=k+1:n
                A[i,j]=A[i,j]-L[i,k]*A[k,j]
            end
        end
        for j=k:n
            U[k,j]=A[k,j]
        end
    end
    L,U
end

mylu (generic function with 1 method)

In [2]:
A=rand(6,6)
# A=[2.0 2;3 4]

6x6 Array{Float64,2}:
 0.212404  0.044726  0.401233   0.321473  0.0522049  0.683447
 0.798053  0.460997  0.0923267  0.237497  0.478373   0.656234
 0.424197  0.558987  0.0042313  0.987409  0.269812   0.362175
 0.634948  0.994747  0.164243   0.508488  0.621959   0.927666
 0.165104  0.277185  0.234571   0.695975  0.0675539  0.878593
 0.822249  0.606081  0.30457    0.497722  0.0748867  0.883883

In [3]:
L,U=mylu(A)

(
6x6 Array{Float64,2}:
 1.0       0.0       0.0       0.0        0.0     0.0
 3.75724   1.0       0.0       0.0        0.0     0.0
 1.99712   1.60322   1.0       0.0        0.0     0.0
 2.98934   2.93922   2.12286   1.0        0.0     0.0
 0.777312  0.827508  0.74316   0.100076   1.0     0.0
 3.87116   1.47786   0.572636  0.245291  24.5799  1.0,

6x6 Array{Float64,2}:
 0.212404  0.044726   0.401233   0.321473   0.0522049   0.683447
 0.0       0.292951  -1.4152    -0.970355   0.282227   -1.91164 
 0.0       0.0        1.47179    1.90108   -0.286918    2.06202 
 0.0       0.0        0.0       -1.63613    0.245461    0.125965
 0.0       0.0        0.0        0.0       -0.0179093   0.384223
 0.0       0.0        0.0        0.0        0.0        -9.59254 )

In [4]:
L*U-A

6x6 Array{Float64,2}:
 0.0   0.0           0.0           0.0           0.0          0.0        
 0.0   0.0           0.0           0.0           0.0          0.0        
 0.0   0.0           0.0           0.0           0.0          0.0        
 0.0  -2.22045e-16  -2.22045e-16  -2.22045e-16   0.0          4.44089e-16
 0.0  -5.55112e-17   0.0           0.0           2.77556e-17  0.0        
 0.0   0.0          -1.11022e-16   0.0          -5.55112e-17  1.11022e-15

## Trokutasti sustavi

In [5]:
function myU{T}(U::Array{T},b1::Array{T})
    b=deepcopy(b1)
    n=length(b)
    for i=n:-1:1
       for j=n:-1:i+1
            b[i]=b[i]-U[i,j]*b[j]
       end
        b[i]=b[i]/U[i,i]
    end
    b
end

function myL{T}(L::Array{T},b1::Array{T})
    b=deepcopy(b1)
    n=length(b)
    for i=1:n
        for j=1:i-1
            b[i]=b[i]-L[i,j]*b[j]
        end
        b[i]=b[i]/L[i,i]
    end
    b
end

myL (generic function with 1 method)

In [6]:
b=rand(6)

6-element Array{Float64,1}:
 0.791764 
 0.607499 
 0.787487 
 0.496574 
 0.0180298
 0.11178  

In [7]:
x=A\b

6-element Array{Float64,1}:
  0.471087
 -0.859887
  3.74174 
  1.02967 
  2.55979 
 -1.80817 

In [8]:
y=myL(L,b)

6-element Array{Float64,1}:
  0.791764
 -2.36735 
  3.0016  
 -1.28411 
 -0.740585
 17.345   

In [9]:
x1=myU(U,y)

6-element Array{Float64,1}:
  0.471087
 -0.859887
  3.74174 
  1.02967 
  2.55979 
 -1.80817 

In [10]:
x-x1

6-element Array{Float64,1}:
  2.77556e-16
  2.33147e-15
 -4.44089e-16
  1.11022e-15
  4.44089e-16
 -4.44089e-16

## Brzina

Program `mylu()` je jako spor. Između ostalog, alocira nepotrebno tri matrice.

Program se može reformulirati na načun da su i $L$ i $U$ spremljene u polje $A$, pri čemu se dijagonala od $L$ ne sprema, jer su svi elementi jednaki 1.

In [12]:
function mylu1{T}(A1::Array{T}) # Strang, page 100
    A=deepcopy(A1)
    n,m=size(A)
    for k=1:n-1
        rho=k+1:n
        A[rho,k]=A[rho,k]/A[k,k]
        A[rho,rho]=A[rho,rho]-A[rho,k]*A[k,rho]
    end
    A
end

mylu1 (generic function with 1 method)

In [13]:
mylu1(A)

6x6 Array{Float64,2}:
 0.212404  0.044726   0.401233   0.321473   0.0522049   0.683447
 3.75724   0.292951  -1.4152    -0.970355   0.282227   -1.91164 
 1.99712   1.60322    1.47179    1.90108   -0.286918    2.06202 
 2.98934   2.93922    2.12286   -1.63613    0.245461    0.125965
 0.777312  0.827508   0.74316    0.100076  -0.0179093   0.384223
 3.87116   1.47786    0.572636   0.245291  24.5799     -9.59254 

In [14]:
L,U

(
6x6 Array{Float64,2}:
 1.0       0.0       0.0       0.0        0.0     0.0
 3.75724   1.0       0.0       0.0        0.0     0.0
 1.99712   1.60322   1.0       0.0        0.0     0.0
 2.98934   2.93922   2.12286   1.0        0.0     0.0
 0.777312  0.827508  0.74316   0.100076   1.0     0.0
 3.87116   1.47786   0.572636  0.245291  24.5799  1.0,

6x6 Array{Float64,2}:
 0.212404  0.044726   0.401233   0.321473   0.0522049   0.683447
 0.0       0.292951  -1.4152    -0.970355   0.282227   -1.91164 
 0.0       0.0        1.47179    1.90108   -0.286918    2.06202 
 0.0       0.0        0.0       -1.63613    0.245461    0.125965
 0.0       0.0        0.0        0.0       -0.0179093   0.384223
 0.0       0.0        0.0        0.0        0.0        -9.59254 )

Usporedimo brzine LAPACK-ovog programa `lu()` i našeg naivnog programa `mylu()`na većoj dimenziji. 

Izvedite program par puta radi točnijeg mjerenja brzine.

In [15]:
n=512
A=rand(n,n)

512x512 Array{Float64,2}:
 0.46633   0.206025   0.826244   …  0.971939   0.156166    0.921662 
 0.709655  0.948336   0.421422      0.0035544  0.29129     0.0429031
 0.29564   0.0391389  0.534725      0.366484   0.412612    0.1859   
 0.903492  0.580158   0.840777      0.855413   0.259161    0.885009 
 0.180339  0.349036   0.524048      0.35488    0.0807613   0.82644  
 0.203491  0.939211   0.998378   …  0.338686   0.976247    0.299419 
 0.136706  0.204837   0.0961085     0.0775802  0.00120947  0.0600546
 0.930452  0.0928178  0.79331       0.4829     0.254856    0.474976 
 0.247034  0.636064   0.217572      0.4524     0.19174     0.538975 
 0.188994  0.325944   0.224531      0.506324   0.400855    0.210364 
 0.2352    0.0289375  0.813838   …  0.118393   0.823485    0.0778189
 0.690935  0.143852   0.764562      0.581129   0.188989    0.0442943
 0.793913  0.497687   0.34811       0.807359   0.29563     0.881062 
 ⋮                               ⋱             ⋮                    
 0.97867

In [17]:
@time lu(A);

  0.163510 seconds (55 allocations: 6.010 MB)


In [19]:
@time mylu1(A);

  0.394485 seconds (17.26 k allocations: 1.004 GB, 8.50% gc time)


### Blok varijanta

`mylu()` je nekoliko desetaka puta sporiji. `mylu1()` je malo sporiji.

Probajmo s blokovima:

Preradimo `mylu1()` za rad s blokovima (nemamo ugrađeno pivotiranje!)

In [20]:
function mylu2{T}(A1::Array{T}) # Strang, page 100
    A=deepcopy(A1)
    n,m=size(A)
    for k=1:n-1
        for rho=k+1:n
            A[rho,k]=A[rho,k]/A[k,k]
            for l=k+1:n
                A[rho,l]=A[rho,l]-A[rho,k]*A[k,l]
            end
        end
    end
    A
end

mylu2 (generic function with 1 method)

Napravimo prvo mali test:

In [21]:
# Probajte k,l=32,16 i k,l=64,8
k,l=4,4
Ab=[rand(k,k) for i=1:l, j=1:l];

In [24]:
A0=mylu2(Ab)

4x4 Array{Any,2}:
 4x4 Array{Float64,2}:
 0.875452   0.148186    0.552143  0.326848
 0.161713   0.00207364  0.456368  0.137411
 0.0994159  0.929053    0.954159  0.928069
 0.0721732  0.626672    0.961861  0.104831                  …  4x4 Array{Float64,2}:
 0.292225  0.871954   0.732715   0.0797755
 0.217164  0.204059   0.0521057  0.296787 
 0.876107  0.0736508  0.0756502  0.694097 
 0.830341  0.410534   0.66809    0.541331         
 4x4 Array{Float64,2}:
 -0.124069   0.594229   0.681821    0.00625171
  1.24344   -1.05054   -0.306836    0.53364   
  0.907164  -2.86017   -0.0115581   1.21982   
  0.885111   1.05603    0.412847   -0.809197       4x4 Array{Float64,2}:
 -0.470548   0.512168   0.715876   -0.411644
  0.52836   -0.460283  -0.288874    0.695566
  0.333965  -0.414419  -0.462733    0.51777 
  0.604962  -0.204302  -0.0980766   0.626034
 4x4 Array{Float64,2}:
 -0.0285004   1.41505  0.312283   -0.241599
 -0.265509    1.8336   0.0332912   0.13173 
  1.01097    -1.77176  0.0842238   0.

In [25]:
# Provjera
U=triu(A0)
L=tril(A0)
for i=1:maximum(size(L))
    L[i,i]=eye(L[1,1])
end

In [26]:
Res=L*U-Ab

4x4 Array{Any,2}:
 4x4 Array{Float64,2}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0                                                                                                                                                  …  4x4 Array{Float64,2}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0                                                                                                            
 4x4 Array{Float64,2}:
 0.0          0.0           0.0           0.0        
 1.11022e-16  2.77556e-17  -5.55112e-17  -6.245e-17  
 0.0          0.0           1.11022e-16  -9.71445e-17
 0.0          0.0          -1.11022e-16   1.11022e-16             4x4 Array{Float64,2}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0                                                                                                            
 4x4 Array{Float64,2}:
  0.0           0.0          -1.11022

In [27]:
# pretvaranje blok matrice u obicnu
unblock(A) = mapreduce(identity, hcat, [mapreduce(identity, vcat, A[:,i]) for i = 1:size(A,2)])

unblock (generic function with 1 method)

In [28]:
norm(unblock(Res))

7.337206751439907e-16

Sada probajmo veću dimenziju:

In [29]:
# Probajmo vece dimenzije (n=k*l)
k,l=32,16
Ab=[rand(k,k) for i=1:l, j=1:l];

In [30]:
@time mylu2(Ab);

  0.192982 seconds (8.79 k allocations: 26.526 MB, 2.92% gc time)


Vidimo da je `mylu2()` gotovo jednako brz kao `lu()`, uz napomenu da `mylu2()` nema ugrađeno pivotiranje. 

## Pivotiranje

Stanardne implementacije uvijek računaju Gaussovu eliminaciju s _parcijalnim pivotiranjem_:

> u svakom koraku se retci pivotiranju tako da pivotni element ima najveću apsolutnu vrijednst u danom stupcu. Na taj 
> način je 
> 
> $$|L_{ij}| \leq 1,$$
> što u praksi dovoljno spriječava rast elemenata.


In [32]:
A=rand(5,5)
L,U,P=lu(A)

(
5x5 Array{Float64,2}:
 1.0       0.0       0.0        0.0        0.0
 0.14147   1.0       0.0        0.0        0.0
 0.178195  0.421298  1.0        0.0        0.0
 0.462087  0.390092  0.148616   1.0        0.0
 0.57052   0.890231  0.50088   -0.0497234  1.0,

5x5 Array{Float64,2}:
 0.814091  0.380744  0.491771   0.595496   0.412362
 0.0       0.48304   0.302009   0.72673    0.455245
 0.0       0.0       0.708493  -0.256694   0.196174
 0.0       0.0       0.0        0.311776   0.183652
 0.0       0.0       0.0        0.0       -0.561589,

[2,1,5,3,4])

In [33]:
L*U-A[P,:]

5x5 Array{Float64,2}:
 0.0   0.0          0.0  0.0          0.0
 0.0   0.0          0.0  0.0          0.0
 0.0   0.0          0.0  0.0          0.0
 0.0   0.0          0.0  1.11022e-16  0.0
 0.0  -1.11022e-16  0.0  0.0          0.0

### Potpuno pivotiranje

Sljedeći program računa Gaussovu eliminaciju s _potpunim pivotiranjem_ - u svakom koraku retci i stupci zamijene na način da se na pivotnu poziciju dovede element koji ima najveću apsolutnu vrijednost u trenutnoj podmatrici.

In [34]:
function gecp{T}(A1::Array{T})
    # Gaussova eliminacija s potpunim pivotiranjem
    # Izlaz: Pr*L*U*Pc'=A ili Pr'*A*Pc=L*U
    A=deepcopy(A1)
    n,m=size(A)
    Pr=eye(n,n)
    Pc=eye(n,n)
    D=zeros(n)
    for i=1:n-1
        am1,im1=findmax(abs(A[i:n,i:n]),1)
        am,JJ=findmax(am1)
        II=mod(im1[JJ],(n-i+1))
        if II==0
            II=n-i+1
        end
        imax=II+i-1
        jmax=JJ+i-1
        #  zamijena redaka
        if (imax != i)
            temp = Pr[:,i]
            Pr[:,i] = Pr[:,imax]
            Pr[:,imax] = temp
            temp = A[i,:]
            A[i,:] = A[imax,:]
            A[imax,:] = temp
        end
        # zamijena stupaca
        if (jmax != i)
            temp = Pc[:,i]
            Pc[:,i] = Pc[:,jmax]
            Pc[:,jmax] = temp
            temp = A[:,i]
            A[:,i] = A[:,jmax]
            A[:,jmax] = temp
        end
        # eliminacija
        D[i]=A[i,i]
        A[i+1:n,i] = A[i+1:n,i]/D[i]
        A[i+1:n,i+1:n] = A[i+1:n,i+1:n] - A[i+1:n,i]*A[i,i+1:n]
        A[i,i+1:n]=A[i,i+1:n]/D[i]
    end
    D[n]=A[n,n]
    L=eye(n,n)+tril(A,-1)
    U=eye(n,n)+triu(A,1)
    U=diagm(D)*U
    L,U,Pr,Pc
end

gecp (generic function with 1 method)

In [35]:
n=5
A=rand(n,n)
b=rand(n)

5-element Array{Float64,1}:
 0.534202
 0.682644
 0.71686 
 0.473825
 0.919802

In [36]:
L,U,Pr,Pc=gecp(A)

(
5x5 Array{Float64,2}:
 1.0         0.0        0.0        0.0       0.0
 0.0911512   1.0        0.0        0.0       0.0
 0.682288    0.768991   1.0        0.0       0.0
 0.78931    -0.257312  -0.11616    1.0       0.0
 0.767545    0.312559   0.318382  -0.928332  1.0,

5x5 Array{Float64,2}:
 0.975517  0.502101   0.657609   0.689226   0.534002 
 0.0       0.816636   0.730769   0.309203   0.766391 
 0.0       0.0       -0.877071   0.114622  -0.793538 
 0.0       0.0        0.0       -0.324985  -0.0852189
 0.0       0.0        0.0        0.0        0.0105081,

5x5 Array{Float64,2}:
 1.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0
 0.0  0.0  0.0  1.0  0.0
 0.0  1.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0,

5x5 Array{Float64,2}:
 0.0  0.0  0.0  1.0  0.0
 0.0  1.0  0.0  0.0  0.0
 1.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0)

In [37]:
Pr*L*U*Pc'-A

5x5 Array{Float64,2}:
 0.0  0.0  0.0  0.0           0.0        
 0.0  0.0  0.0  0.0          -5.55112e-17
 0.0  0.0  0.0  0.0           0.0        
 0.0  0.0  0.0  0.0           0.0        
 0.0  0.0  0.0  1.11022e-16   0.0        

In [38]:
y=myL(L,Pr'*b)

5-element Array{Float64,1}:
 0.534202
 0.425132
 0.2284  
 0.431132
 0.467256

In [39]:
z=myU(U,y)

5-element Array{Float64,1}:
  13.0706 
   1.46023
 -42.189  
 -12.9867 
  44.4664 

In [40]:
x=Pc*z

5-element Array{Float64,1}:
 -12.9867 
   1.46023
  13.0706 
 -42.189  
  44.4664 

In [41]:
A*x-b

5-element Array{Float64,1}:
 -4.44089e-16
  8.88178e-16
  0.0        
  7.54952e-15
 -2.22045e-15

## Točnost

Neka je zadan sustav $Ax=b$, pri čemu je matrica $A$ regularna.

Da bi primijenili koncepte iz bilježnice [NA04_Pogreska_unatrag_i stabilni_algoritmi](NA04_Pogreska_unatrag_i_stabilni_algoritmi.ipynb), potrebno je:

1. napraviti teoriju smetnje za dani problem
2. analizirati pogreške algoritma (Gaussove eliminacije)

### Teorija smetnje

Neka je 

$$
(A+\delta A)\hat x=(b+\delta b)
$$
za neki $\hat x=x+\delta x$.

Želimo ocijeniti 
$$
\frac{\| \hat x - x \|}{\| x\|} \equiv \frac{\| \delta x\|}{\| x\|}.
$$

Uvedimo oznake (npr. prema [G. Golub and C. F. Van Loan, Matrix Computations, str. 87, poglavlje 2.6.2][GVL13])

$$
\delta A=\varepsilon F, \quad \delta b=\varepsilon f, \qquad \hat x=x(\varepsilon),
$$
čime smo dobili jednodimenzionalni problem 

$$
(A+\varepsilon F)x(\varepsilon)=b+\varepsilon f.
$$

za neke (nepoznate) matricu $F$ i vektor $f$. 

Deriviranje po $\varepsilon$ daje

$$
Fx(\varepsilon)+(A+\varepsilon F)\dot x(\varepsilon)=f.
$$

Uvrštavanje $\varepsilon=0$ daje

$$
F x+A\dot x(0)=f,
$$
odnosno
$$
\dot x(0)=A^{-1}(f-Fx).
$$

Taylorov razvoj oko $x(0)$ glasi

$$
x(\varepsilon)=x(0)+\varepsilon \dot x(0) +O(\varepsilon^2),
$$
odnosno, uz zanemarivanje člana $O(\varepsilon^2)$,

$$
\hat x-x=\varepsilon A^{-1}(f-Fx)=A^{-1} (\varepsilon f + \varepsilon F x) = A^{-1} (\delta b + \delta A x).
$$

Svojstva norme povlače

$$
\| \hat x-x\|\leq \| A^{-1} \| (\| \delta b \|  + \| \delta A \| \cdot \|  x\| ).
$$

Konačno, zbog $\| b\| \leq \| A\| \| x\|$ imamo

$$
\frac{\| \hat x-x\|}{\| x\|}\leq \| A\|  \cdot \| A^{-1} \| \bigg(\frac{\| \delta b \|}{\|b\|}  + \frac{\| \delta A \|}{ \|  A\|} \bigg). \tag{1}
$$

Broj 
$$
\kappa(A)\equiv \| A\|  \cdot \| A^{-1} \|
$$ 

je _uvjetovanost_ (_kondicija_)  matrice $A$ i kazuje nam 

> koliko se relativno uvećaju relativne promjene u polaznim podacima (matrici $A$ i vektoru $b$).

Pogledajmo primjer iz [R. Scitovski, Numerička matematika, str. 42][RS04]:




[GVL13]: https://books.google.hr/books?id=X5YfsuCWpxMC&printsec=frontcover&hl=hr#v=onepage&q&f=false "G. Golub and C. F Van Loan, 'Matrix Computations', 4th Edition, John Hopkins, Baltimore, 2013" 

[RS04]: http://www.mathos.unios.hr/pim/Materijali/Num.pdf "R. Scitovski, 'Numerička matematika', Sveučilište u Osijeku, osijek, 2004."

In [42]:
A= [0.234 0.458; 0.383 0.750]

2x2 Array{Float64,2}:
 0.234  0.458
 0.383  0.75 

In [43]:
b=[0.224;0.367]

2-element Array{Float64,1}:
 0.224
 0.367

In [44]:
x=A\b

2-element Array{Float64,1}:
 -1.0
  1.0

In [45]:
δb=[0.00009; 0.000005]
x1=A\(b+δb)

2-element Array{Float64,1}:
 -0.241744
  0.612791

In [46]:
cond(A), norm(δb)/norm(b), norm(x1-x)/norm(x)

(11322.197586092605,0.0002096449170953002,0.6020311134825742)

In [47]:
δA=[-0.001 0;0 0]
x2=(A+δA)\b

2-element Array{Float64,1}:
 0.129518
 0.423193

In [48]:
cond(A), norm(δA)/norm(A), norm(x2-x)/norm(x)

(11322.197586092605,0.0010134105230118603,0.896804787832142)

### Pogreška Gaussove eliminacije

Prema [G. Golub and C. F. Van Loan, Matrix Computations, str. 122, poglavlje 3.3][GVL13], za izračunate faktore
$\hat L$ i $\hat U$ vrijedi

$$
\hat L\cdot \hat U = A+\delta A
$$

gdje je (nejednakost se čita po elementima matrica, $\varepsilon$ je sada točnost stroja)

$$
| \delta A|\leq 3(n-1) \varepsilon (|A|+|\hat L| \cdot |\hat U|) +O(\varepsilon^2).
$$

Zanemarivanje člana $O(\varepsilon^2)$ i prelazak na normu daju

$$
\|\delta A \| \approx \leq  O(n)\varepsilon (\| A\| + \| \hat L\| \cdot \| \hat U\|),
$$

pa je 

$$
 \frac{\|\delta A \|}{\|A\|} \leq O(n)\varepsilon \bigg(1+\frac{\| \hat L\| \cdot \| \hat U\|}{\|A\|}\bigg).
$$

Ukoliko se Gaussova eliminacija radi s pivotiranjem, tada će najvjerojatnije zadnji kvocijent također biti malen 
($\approx 1$). Također, pogreška kod rješavanja trokutastih sustava nije veća od navedene pa, uvrštavanjme u (1), slijedi 
da za relativnu pogrešku izračunatog rješenja vrijedi

$$
\frac{\| \hat x-x\|}{\| x\|}\leq \kappa(A) O(n\varepsilon).
$$

> __Ukoliko je kondicija matrice velika, rješenje može biti netočno.__

[GVL13]: https://books.google.hr/books?id=X5YfsuCWpxMC&printsec=frontcover&hl=hr#v=onepage&q&f=false "G. Golub and C. F Van Loan, 'Matrix Computations', 4th Edition, John Hopkins, Baltimore, 2013" 

In [49]:
n=10
v=rand(n)

10-element Array{Float64,1}:
 0.607311
 0.160587
 0.714493
 0.693856
 0.845259
 0.725358
 0.612459
 0.969179
 0.120647
 0.207438

In [50]:
A=Array(Float64,n,n)
for i=1:n
    A[:,i]=v.^(i-1)
end
A=A'

10x10 Array{Float64,2}:
 1.0        1.0          1.0        …  1.0       1.0          1.0        
 0.607311   0.160587     0.714493      0.969179  0.120647     0.207438   
 0.368827   0.0257881    0.5105        0.939307  0.0145556    0.0430305  
 0.223993   0.00414123   0.364748      0.910356  0.00175608   0.00892617 
 0.136033   0.000665027  0.26061       0.882298  0.000211865  0.00185163 
 0.0826144  0.000106795  0.186204   …  0.855104  2.55608e-5   0.000384098
 0.0501727  1.71498e-5   0.133041      0.828749  3.08382e-6   7.96764e-5 
 0.0304704  2.75403e-6   0.0950571     0.803206  3.72053e-7   1.65279e-5 
 0.018505   4.42261e-7   0.0679176     0.77845   4.48869e-8   3.42852e-6 
 0.0112383  7.10213e-8   0.0485266     0.754457  5.41545e-9   7.11205e-7 

In [51]:
b=rand(n)

10-element Array{Float64,1}:
 0.740709 
 0.635757 
 0.434511 
 0.0410912
 0.933363 
 0.0419936
 0.388915 
 0.688959 
 0.913519 
 0.990192 

In [52]:
x=A\b

10-element Array{Float64,1}:
     -1.20831e8
     -2.55682e5
      3.37009e8
     -1.64906e8
      7.92754e5
     -1.92645e8
      1.40568e8
 -25894.8      
  90239.4      
      2.03737e5

In [53]:
cond(A)

8.727631413981882e9

In [54]:
Ab=Array(BigFloat,n,n)
bb=Array(BigFloat,n)
for i=1:n
    for j=1:n
        Ab[i,j]=convert(BigFloat,A[i,j])
    end
    bb[i]=convert(BigFloat,b[i])
end
xb=Ab\bb

10-element Array{BigFloat,1}:
 -1.208308132110681397309551749412551159116691244224550790812878072715993467066749e+08
 -2.556821001821039150785073490755804853226168555667054556807705907161020950659327e+05
  3.370086013682936823083447120187754186046432909490619657254388641202007632773779e+08
 -1.649056086418036393499804525582264910157120177603335005995248151959166030587366e+08
  7.927539300129839799402206076771155036276701460547188720956855623093728521193877e+05
 -1.926448780996507859829761843933474208204814581568959305086546310072215387788094e+08
  1.405675454147319388875055076067426408764858365860927599644299934494545687162966e+08
 -2.58947706548268862112532441256641636640889256576286000179793436565427568685929e+04 
  9.023937253638861061689066343261740030865130642914046089801138194832966562444675e+04
  2.03737478493676684636532562048449316505659606338496526990948895197098884737959e+05 

In [55]:
norm(xb-x)/norm(xb)

5.652350705763762643556379575170409479165859073632640749492837177735901035825800e-09

### Umjetno loša kondicija

In [56]:
A=[1 1; 1 2]
b=[1;3]
x=A\b
@show x,cond(A)
A1=[1e-4 1e-4;1 2]
b1=[1e-4;3]
x1=A1\b1
x,cond(A1),x-x1

(x,cond(A)) = ([-1.0,2.0],6.854101966249685)

([-1.0,2.0],50000.00017991671,[8.881784197001252e-16,-4.440892098500626e-16])

## Rezidual

(Prema [G. W. Stewart, Afternotes on Numerical Analysis, str. 128.][Ste96])

Izračunato rješenje $\hat x$ sustava $Ax=b$ je točno rješenje nekog sličnog sustava

$$ 
(A+\delta A)\hat x=b. \tag{1}
$$

_Rezidual_ (ili _ostatak_) definiramo kao 

$$
r=b-A\hat x.
$$

Tada je 

$$
0=b-(A+\delta A)\hat x=r- \delta A\hat x
$$
pa je 

$$ 
\| r\| \leq \| \delta A\hat x \| \leq \| \delta A\| \cdot \|\hat x \|,
$$

odnosno

$$
\frac{\|  \delta A\|}{\|A \|} \geq \frac{\|r\|}{\| A\| \cdot \|\hat x \|}.
$$

Dakle,
> ako  _relativni rezidual_ 
>
> $$ \frac{r}{\| A\| \cdot \|\hat x \|}$$
ima veliku normu, tada __rješenje nije izračunato stabilno.__

S druge strane, ako relativni rezidual ima malu normu, tada je rješenje izračunato stabilno. Naime, za

$$
\delta A=\frac{r\hat x^T}{\|\hat x\|^2}
$$
vrijedi (1):

$$
b-(A+\delta A)\hat x=(b-A\hat x)-\delta A \hat x = r-\frac{r\hat x^T \hat x}{\|\hat x\|^2}
= r-\frac{r \|\hat x^T \hat x\|}{\|\hat x\|^2}=r-r=0.
$$
Također vrijedi

$$
\frac{\|  \delta A\|}{\|A \|}  \leq  \frac{\|r\|\|\hat x \|}{\| A\| \cdot \|\hat x \|^2}=
\frac{\|r\|}{\| A\| \cdot \|\hat x \|}.
$$




[Ste96]: https://books.google.hr/books?id=w-2PWh01kWcC&printsec=frontcover&hl=hr#v=onepage&q&f=false    "G. W. Stewart, 'Afternotes on Numerical Analysis', SIAM, Philadelphi, 1996"

In [57]:
r=b-A*x

2-element Array{Float64,1}:
 0.0
 0.0

In [58]:
norm(r)/(norm(A)*norm(x))

0.0