# QR rastav

---

__QR rastav__ matrice $A$ tipa $m\times n$,  $m\geq n$,
glasi

$$
A=QR, 
$$

pri čemu je $Q$ __ortonormirana matrica__ dimenzije $m\times m$, odnosno
\[
Q^TQ=Q Q^T=I,
\]
a $R$ je $m\times n$ gornje trokutasta matrica.

Ortonormiranu matricu kraće zovemo i __ortogonalna matrica__.

Na primjer,

$$
\begin{bmatrix} a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33} \\
a_{41} & a_{42} & a_{43} \\
a_{51} & a_{52} & a_{53}
\end{bmatrix}
=
\begin{bmatrix}
q_{11} & q_{12} & q_{13} & q_{14} & q_{15} \\
q_{21} & q_{22} & q_{23} & q_{24} & q_{25} \\
q_{31} & q_{32} & q_{33} & q_{34} & q_{35} \\
q_{41} & q_{42} & q_{43} & q_{44} & q_{45} \\
q_{51} & q_{52} & q_{53} & q_{54} & q_{55}
\end{bmatrix}
\begin{bmatrix}
r_{11} & r_{12} & r_{13} \\
0 & r_{22} & r_{23} \\
0 & 0 & r_{33} \\
0 & 0 & 0 \\
0 & 0 & 0 
\end{bmatrix}. \tag{1}
$$

S (1) je definiram i __ekonomični QR rastav__

$$
\begin{bmatrix} a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33} \\
a_{41} & a_{42} & a_{43} \\
a_{51} & a_{52} & a_{53}
\end{bmatrix}
=
\begin{bmatrix}
q_{11} & q_{12} & q_{13} \\
q_{21} & q_{22} & q_{23} \\
q_{31} & q_{32} & q_{33} \\
q_{41} & q_{42} & q_{43} \\
q_{51} & q_{52} & q_{53}
\end{bmatrix}
\begin{bmatrix}
r_{11} & r_{12} & r_{13} \\
0 & r_{22} & r_{23} \\
0 & 0 & r_{33}
\end{bmatrix}. \tag{2}
$$


Izjednačavanje stupaca počevši od prvog daje: 

\begin{align}
t&=a_{:1}\\
r_{11}&=\|t\|_2 \\
q_{:1}&=t\frac{1}{r_{11}}\\
r_{12}&= q_{:1}^Ta_{:1} \\
t&=a_{:2}-q_{:1}r_{12} \\
r_{22}&=\|t\|_2 \\
q_{:2}&=t\frac{1}{r_{22}} \\
r_{13}&=q_{:1}^Ta_{:3} \\
r_{23}&=q_{:2}^Ta_{:3} \\
t&=a_{:3}-q_{:1}r_{13}-q_{:2}r_{23}\\
r_{33}&=\|t\|_2 \\
q_{:3}&=t\frac{1}{r_{33}}.
\end{align}

Indukcijom slijedi __Gram-Schmidt-ov postupak ortogonalizacije__.

In [1]:
function myGramSchmidtQR{T}(A::Array{T})
    m,n=size(A)
    R=zeros(Float64,n,n)
    Q=Array(Float64,m,n)
    R[1,1]=norm(A[:,1])
    Q[:,1]=A[:,1]/R[1,1]
    for k=2:n
        for i=1:k-1
            R[i,k]=Q[:,i]⋅A[:,k]
        end
        t=A[:,k]-sum([R[i,k]*Q[:,i] for i=1:k-1])
        R[k,k]=norm(t)
        Q[:,k]=t/R[k,k]
    end
    Q,R
end 

myGramSchmidtQR (generic function with 1 method)

In [2]:
A=rand(8,5)
Q,R=myGramSchmidtQR(A)

(
8x5 Array{Float64,2}:
 0.078616    0.531294    0.402368  -0.0906726  -0.504591 
 0.628647   -0.426034    0.116157   0.233483   -0.19617  
 0.438997    0.190536   -0.254697   0.14167    -0.431868 
 0.208419   -0.1244      0.542875   0.29983     0.150228 
 0.0184714   0.530536   -0.122796   0.723691    0.352421 
 0.567501    0.186312   -0.370342  -0.359526    0.426517 
 0.139354   -0.0418132   0.49452   -0.114738    0.428375 
 0.143689    0.408061    0.26123   -0.401426    0.0905748,

5x5 Array{Float64,2}:
 1.0873  1.2775  1.30268    1.05161   1.00839 
 0.0     1.2966  0.253525   0.572734  0.476711
 0.0     0.0     1.11815   -0.060735  0.41717 
 0.0     0.0     0.0        0.631003  0.271628
 0.0     0.0     0.0        0.0       0.720495)

In [3]:
A-Q*R

8x5 Array{Float64,2}:
  0.0          0.0   0.0           0.0          0.0
  0.0          0.0   0.0           0.0          0.0
  5.55112e-17  0.0  -5.55112e-17   0.0          0.0
  0.0          0.0   0.0          -5.55112e-17  0.0
  0.0          0.0   0.0           0.0          0.0
  0.0          0.0   0.0           0.0          0.0
  0.0          0.0   0.0           0.0          0.0
 -2.77556e-17  0.0   0.0           0.0          0.0

In [4]:
Q'*Q

5x5 Array{Float64,2}:
  1.0          -2.77556e-17   3.46945e-17   4.30211e-16  -2.23779e-16
 -2.77556e-17   1.0           8.32667e-17   1.11022e-16  -1.38778e-16
  3.46945e-17   8.32667e-17   1.0           1.38778e-17  -6.93889e-17
  4.30211e-16   1.11022e-16   1.38778e-17   1.0          -7.77156e-16
 -2.23779e-16  -1.38778e-16  -6.93889e-17  -7.77156e-16   1.0        

Algoritam `myGramSchmidtQR()` je numerički nestabilan pa je bolje koristiti _modificirani Gram-Schmidt-ov algoritam_ ili _Householder-ove reflektore_ ili _Givens-ove rotacije_ (vidi [Matrix Computations, poglavlje 5][GVL13]).

[GVL13]: https://books.google.hr/books?id=X5YfsuCWpxMC&printsec=frontcover&hl=hr#v=onepage&q&f=false "G. Golub and C. F Van Loan, 'Matrix Computations', 4th Edition, John Hopkins, Baltimore, 2013"

## Householderovi reflektori

__QR rastav vektora__ $x$ jednak je

$$
H \begin{bmatrix} x_1 \\ x_2 \\ \vdots \\ x_m 
\end{bmatrix}  =r,
$$

gdje je 

$$
H=I - \frac{2}{v^Tv}v v^T, \qquad  
v=\begin{bmatrix}
x_1\pm \|x\|_2 \\ x_2 \\ x_3 \\ \vdots \\ x_m
\end{bmatrix}.
$$ 

__Householderov reflektor__ $H$ je __simetrična__ i __ortogonalna__ matrica (dokažite!). Ovisno o izboru predznaka u definicije vektora $v$ vrijedi

$$
r=\begin{bmatrix} \mp \|x\| \\ 0 \\ \vdots \\ 0
\end{bmatrix}
$$

Zbog numeričke stabilnost se najčešće uzima

$$
v_1=x_1+\mathop{\mathrm{sign}} (x_1) \|x\|_2.
$$

Matrica $H$ se __ne računa eksplicitno__ već se produkt $Hx$ računa po formuli

$$
Hx=x-v\frac{2v^Tx}{v^Tv}
$$

za koju je potrebno $O(6m)$ operacija.

In [5]:
function myHouseholderVector{T}(x::Array{T})
    # Vraca v
    v=deepcopy(x)
    v[1]=x[1]+sign(x[1])*norm(x)
    v
end

myHouseholderVector (generic function with 1 method)

In [6]:
x=rand(8)
v=myHouseholderVector(x)
β=(2/(v⋅v))*(v⋅x)
x-β*v

8-element Array{Float64,1}:
 -1.56063    
  1.11022e-16
  1.38778e-17
  5.55112e-17
  5.55112e-17
  1.11022e-16
  5.55112e-17
  1.11022e-16

In [7]:
norm(x)

1.560633229244573

QR rastav matrice se računa rekurzivnim QR rastavom vektora pomoću Householderovih reflektora:

In [8]:
function myHouseholderQR{T}(A1::Array{T})
    # Vraca Q i R
    A=deepcopy(A1)
    m,n=size(A)
    # R=zeros(Float64,m,n)
    Q=eye(Float64,m,m)
    for k=1:n
        v=myHouseholderVector(A[k:m,k])
        β=(2/(v⋅v))*v
        A[k:m,k:n]=A[k:m,k:n]-β*(v'*A[k:m,k:n])
        Q[k:m,:]=Q[k:m,:]-β*(v'*Q[k:m,:])
    end
    R=triu(A)
    Q',R
end
    

myHouseholderQR (generic function with 1 method)

In [9]:
A=rand(8,5)

8x5 Array{Float64,2}:
 0.0665277  0.9388     0.187428  0.939442  0.51729  
 0.623285   0.63411    0.854875  0.266542  0.803312 
 0.315867   0.439227   0.138331  0.676894  0.474948 
 0.644408   0.763881   0.252037  0.317958  0.0653466
 0.0337883  0.522479   0.453746  0.911328  0.269676 
 0.198002   0.652266   0.950899  0.776652  0.79112  
 0.139664   0.708062   0.524645  0.817366  0.121286 
 0.913403   0.0470904  0.120822  0.406958  0.774429 

In [10]:
Q,R=myHouseholderQR(A)

(
8x8 Array{Float64,2}:
 -0.0495579   0.59742   -0.46074    …  -0.306755  -0.00915418   0.180569 
 -0.464298    0.106115   0.430477      -0.270208   0.0897109   -0.476787 
 -0.235296    0.133084  -0.212858       0.676312   0.22773     -0.492038 
 -0.480033    0.182564  -0.375703       0.240206  -0.316204     0.176614 
 -0.0251696   0.334152   0.155551      -0.237841  -0.59554     -0.363809 
 -0.147496    0.337029   0.615581   …   0.399552  -0.125366     0.516919 
 -0.104039    0.404568   0.0857848     -0.206381   0.684717     0.0780927
 -0.680413   -0.438026  -0.0738342     -0.242875   0.0282895    0.247212 ,

8x5 Array{Float64,2}:
 -1.34242  -1.02604  -0.848207  -0.981641   -1.20476 
  0.0       1.48631   0.898543   1.45636     0.536013
  0.0       0.0       0.849534   0.0782825   0.463995
  0.0       0.0       0.0        0.830403    0.382035
  0.0       0.0       0.0        0.0         0.596486
  0.0       0.0       0.0        0.0         0.0     
  0.0       0.0       0.0        0.0

In [11]:
Q'*A

8x5 Array{Float64,2}:
 -1.34242      -1.02604      -0.848207     -0.981641     -1.20476    
 -1.11022e-16   1.48631       0.898543      1.45636       0.536013   
  2.77556e-17  -1.30104e-16   0.849534      0.0782825     0.463995   
 -3.33067e-16  -1.70003e-16  -6.93889e-17   0.830403      0.382035   
 -5.55112e-17   1.35308e-16   6.93889e-17   4.71845e-16   0.596486   
  1.11022e-16   2.08167e-16   1.80411e-16   9.71445e-17   1.38778e-16
 -1.07553e-16  -2.53703e-17   6.98226e-17   1.75207e-16  -3.81639e-17
 -1.11022e-16   1.89085e-16  -1.17961e-16   2.91434e-16   0.0        

Program `myHouseholderQR()` je ilustrativan. Profesionalni programi imaju sljedeća svojstva:

* računaju s blok matricama (uobičajena dimenzija bloka je 32 ili 64),
* izračuna se vektor $\hat v=v/v_1$. Vrijedi $\hat v_1=1$, dok se ostali elemenenti vektora $\hat v$ spremaju u strogi donji trokut matrice $A$,
* ako se traži matrica $Q$, akumulacija se vrši unatrag koristeći spremljene vektore $v$ (tako se smanjuje broj operacija),
* postoji opcija vraćanja ekonomičnog rastava,
* postoji opcija računanja s __pivotiranjem__ - u svakom koraku se na prvo mjesto dovede stupac s najvećom normom pa je 

$$
AP=QR.
$$

Vrijedi

$$
|R_{kk}|\geq |R_{k+1,k+1}|
$$

pa se može utvrditi i numerički rank matrice.

In [12]:
Q1,R1=qr(A,thin=true)

(
8x5 Array{Float64,2}:
 -0.0495579   0.59742   -0.46074     0.0684073   0.544871 
 -0.464298    0.106115   0.430477   -0.454565    0.26989  
 -0.235296    0.133084  -0.212858    0.323655    0.159696 
 -0.480033    0.182564  -0.375703   -0.469326   -0.431211 
 -0.0251696   0.334152   0.155551    0.467      -0.319107 
 -0.147496    0.337029   0.615581    0.111803    0.175079 
 -0.104039    0.404568   0.0857848   0.143698   -0.529116 
 -0.680413   -0.438026  -0.0738342   0.460905    0.0798994,

5x5 Array{Float64,2}:
 -1.34242  -1.02604  -0.848207  -0.981641   -1.20476 
  0.0       1.48631   0.898543   1.45636     0.536013
  0.0       0.0       0.849534   0.0782825   0.463995
  0.0       0.0       0.0        0.830403    0.382035
  0.0       0.0       0.0        0.0         0.596486)

In [13]:
Q2,R2,P2=qr(A,Val{true})

(
8x5 Array{Float64,2}:
 -0.483178   0.2252     -0.312576     -0.440962    0.544871 
 -0.137089  -0.457704    0.597565     -0.182765    0.26989  
 -0.348144  -0.0689591  -0.301188      0.0803921   0.159696 
 -0.163534  -0.460465   -0.0867108    -0.615541   -0.431211 
 -0.468719   0.244997   -0.000488808   0.273599   -0.319107 
 -0.399452   0.0627678   0.558562      0.226473    0.175079 
 -0.420392   0.12536     0.0941733    -0.0345594  -0.529116 
 -0.209309  -0.665831   -0.355132      0.509367    0.0798994,

5x5 Array{Float64,2}:
 -1.9443  -0.677766  -1.13549   -1.63134   -1.1916  
  0.0     -1.15876   -0.31849   -0.23449   -0.698734
  0.0      0.0        0.926154   0.300981   0.347779
  0.0      0.0        0.0       -0.674572   0.266263
  0.0      0.0        0.0        0.0        0.596486,

[4,1,3,2,5])

In [14]:
Q2*R2-A[:,P2]

8x5 Array{Float64,2}:
 1.11022e-16  2.22045e-16   5.55112e-17  6.66134e-16  -2.22045e-16
 0.0          1.11022e-16  -1.11022e-16  1.11022e-16   0.0        
 1.11022e-16  1.11022e-16   5.55112e-17  2.22045e-16   1.11022e-16
 0.0          1.11022e-16   0.0          1.11022e-16  -1.11022e-16
 1.11022e-16  5.55112e-17   5.55112e-17  1.11022e-16  -1.11022e-16
 1.11022e-16  5.55112e-17   0.0          1.11022e-16   0.0        
 0.0          2.77556e-17  -1.11022e-16  1.11022e-16  -5.55112e-17
 5.55112e-17  1.11022e-16   0.0          0.0           2.22045e-16

## Brzina

Broj računskih operacija potrebnih za računanje QR rastava matrice $n\times n$ je $O\big(\frac{4}{3}n^3\big)$ za računanje matrice $R$ i  $O\big(\frac{4}{3}n^3\big)$ za računanje matrice $Q$. 


In [15]:
n=512
A=rand(n,n)

512x512 Array{Float64,2}:
 0.257606  0.0845131  0.118717   …  0.195343   0.227622   0.715156 
 0.708221  0.137803   0.794173      0.997456   0.621092   0.28563  
 0.411062  0.295472   0.266258      0.374317   0.968265   0.745656 
 0.820678  0.295179   0.960145      0.370324   0.102766   0.147607 
 0.15415   0.379783   0.0765235     0.358867   0.629899   0.90207  
 0.516885  0.0331738  0.748555   …  0.283804   0.447094   0.124252 
 0.82854   0.97993    0.0045712     0.630137   0.0925477  0.373992 
 0.57788   0.34125    0.270476      0.0361061  0.312488   0.599964 
 0.588155  0.390631   0.336293      0.435792   0.0827596  0.344603 
 0.899007  0.851428   0.283197      0.158036   0.20447    0.759127 
 0.863036  0.60136    0.607387   …  0.969492   0.149484   0.0740349
 0.420625  0.135084   0.422086      0.725621   0.469543   0.283248 
 0.253695  0.625787   0.198367      0.102971   0.490133   0.220909 
 ⋮                               ⋱             ⋮                   
 0.636397  0.938067   

In [16]:
@time qr(A);

  0.041536 seconds (785 allocations: 8.325 MB)


In [17]:
@time qr(A,Val{true});

  0.049736 seconds (36 allocations: 6.267 MB)


In [18]:
@time myHouseholderQR(A);

  1.386338 seconds (48.49 k allocations: 3.359 GB, 8.17% gc time)


## Točnost

Za matrice $\hat Q$ i $\hat R$ izračunate Householder-ovom metodom vrijedi: 

\begin{align*}
\hat Q^T\hat Q& =I+E, \qquad \|E \|_2\approx \varepsilon,\\ 
\| A-\hat Q\hat R\|_2& \approx \varepsilon\|A\|_2.
\end{align*}

Također, postoji egzaktna ortogonalna matrica $Q$ za koju je 

$$\| A- Q\hat R\|_2\approx \varepsilon\|A\|_2.
$$