# QR rastav

---

__QR rastav__ matrice $A$ tipa $m\times n$,  $m\geq n$,
glasi

$$
A=QR, 
$$

pri čemu je $Q$ __ortonormirana matrica__ dimenzije $m\times m$, odnosno
\[
Q^TQ=Q Q^T=I,
\]
a $R$ je $m\times n$ gornje trokutasta matrica.

Ortonormiranu matricu kraće zovemo i __ortogonalna matrica__.

Na primjer,

$$
\begin{bmatrix} a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33} \\
a_{41} & a_{42} & a_{43} \\
a_{51} & a_{52} & a_{53}
\end{bmatrix}
=
\begin{bmatrix}
q_{11} & q_{12} & q_{13} & q_{14} & q_{15} \\
q_{21} & q_{22} & q_{23} & q_{24} & q_{25} \\
q_{31} & q_{32} & q_{33} & q_{34} & q_{35} \\
q_{41} & q_{42} & q_{43} & q_{44} & q_{45} \\
q_{51} & q_{52} & q_{53} & q_{54} & q_{55}
\end{bmatrix}
\begin{bmatrix}
r_{11} & r_{12} & r_{13} \\
0 & r_{22} & r_{23} \\
0 & 0 & r_{33} \\
0 & 0 & 0 \\
0 & 0 & 0 
\end{bmatrix}. \tag{1}
$$

S (1) je definiram i __ekonomični QR rastav__

$$
\begin{bmatrix} a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33} \\
a_{41} & a_{42} & a_{43} \\
a_{51} & a_{52} & a_{53}
\end{bmatrix}
=
\begin{bmatrix}
q_{11} & q_{12} & q_{13} \\
q_{21} & q_{22} & q_{23} \\
q_{31} & q_{32} & q_{33} \\
q_{41} & q_{42} & q_{43} \\
q_{51} & q_{52} & q_{53}
\end{bmatrix}
\begin{bmatrix}
r_{11} & r_{12} & r_{13} \\
0 & r_{22} & r_{23} \\
0 & 0 & r_{33}
\end{bmatrix}. \tag{2}
$$


Izjednačavanje stupaca počevši od prvog daje: 

\begin{align}
t&=a_{:1}\\
r_{11}&=\|t\|_2 \\
q_{:1}&=t\frac{1}{r_{11}}\\
r_{12}&= q_{:1}^Ta_{:1} \\
t&=a_{:2}-q_{:1}r_{12} \\
r_{22}&=\|t\|_2 \\
q_{:2}&=t\frac{1}{r_{22}}
r_{13}&=q_{:1}^Ta_{:3} \\
r_{23}&=q_{:2}^Ta_{:3} \\
t&=a_{:3}-q_{:1}r_{13}-q_{:2}r_{23}\\
r_{33}&=\|t\|_2 \\
q_{:3}&=t\frac{1}{r_{33}}.
\end{align}

Indukcijom dobijemo __Gram-Schmidt-ov postupak ortogonalizacije__

In [1]:
function myGramSchmidtQR{T}(A::Array{T})
    m,n=size(A)
    R=zeros(Float64,n,n)
    Q=Array(Float64,m,n)
    R[1,1]=norm(A[:,1])
    Q[:,1]=A[:,1]/R[1,1]
    for k=2:n
        for i=1:k-1
            R[i,k]=Q[:,i]⋅A[:,k]
        end
        t=A[:,k]-sum([R[i,k]*Q[:,i] for i=1:k-1])
        R[k,k]=norm(t)
        Q[:,k]=t/R[k,k]
    end
    Q,R
end 

myGramSchmidtQR (generic function with 1 method)

In [2]:
A=rand(8,5)
Q,R=myGramSchmidtQR(A)

(
8x5 Array{Float64,2}:
 0.359648    0.503638   -0.285932      0.588354   0.0994707
 0.318703   -0.435042   -0.000649985   0.287177   0.144203 
 0.621199   -0.434796   -0.159205     -0.367048   0.189053 
 0.0149078   0.180702    0.416849     -0.144982   0.0650706
 0.394503    0.0479348   0.312581      0.319804   0.0847595
 0.411997    0.292243   -0.163206     -0.31799   -0.732296 
 0.136792   -0.0818673   0.74755       0.136438  -0.292223 
 0.197194    0.490899    0.189629     -0.44002    0.548178 ,

5x5 Array{Float64,2}:
 1.56401  1.41757    1.2373      1.04789    1.12889 
 0.0      0.609087  -0.00797281  0.283191   0.336651
 0.0      0.0        1.03646     0.851554   0.207381
 0.0      0.0        0.0         0.595904  -0.249448
 0.0      0.0        0.0         0.0        0.789342)

In [3]:
A-Q*R

8x5 Array{Float64,2}:
  0.0          0.0  0.0  0.0  0.0
  0.0          0.0  0.0  0.0  0.0
  0.0          0.0  0.0  0.0  0.0
  0.0          0.0  0.0  0.0  0.0
  0.0          0.0  0.0  0.0  0.0
  0.0          0.0  0.0  0.0  0.0
 -2.77556e-17  0.0  0.0  0.0  0.0
  0.0          0.0  0.0  0.0  0.0

In [4]:
Q'*Q

5x5 Array{Float64,2}:
  1.0          -6.52256e-16  -4.44089e-16   4.30211e-16   5.41234e-16
 -6.52256e-16   1.0           8.60423e-16  -1.94289e-16   6.66134e-16
 -4.44089e-16   8.60423e-16   1.0           5.13478e-16   3.46945e-16
  4.30211e-16  -1.94289e-16   5.13478e-16   1.0          -7.49401e-16
  5.41234e-16   6.66134e-16   3.46945e-16  -7.49401e-16   1.0        

Algoritam `myGramSchmidtQR()` je numerički nestabilan pa je bolje koristiti _modificirani Gram-Schmidt-ov algoritam_ ili _Householder-ove reflektore_ ili _Givens-ove rotacije_ (vidi [G. Golub and C. F. Van Loan, Matrix Computations, poglavlje 5][GVL13]).

[GVL13]: https://books.google.hr/books?id=X5YfsuCWpxMC&printsec=frontcover&hl=hr#v=onepage&q&f=false "G. Golub and C. F Van Loan, 'Matrix Computations', 4th Edition, John Hopkins, Baltimore, 2013"

## Householderovi reflektori

_QR rastav vektora_ $x$ jednak je

$$
H \begin{bmatrix} x_1 \\ x_2 \\ \vdots \\ x_m 
\end{bmatrix}  =r,
$$

gdje je 

$$
H=I - \frac{2}{v^Tv}v v^T, \qquad  
v=\begin{bmatrix}
x_1\pm \|x\|_2 \\ x_2 \\ x_3 \\ \vdots \\ x_m
\end{bmatrix}.
$$ 

__Householderov reflektor__ $H$ je _simetrična_ i _ortogonalna_ matrica (dokažite!). Ovisno o izboru predznaka u definicije vektora $v$ vrijedi

$$
r=\begin{bmatrix} \mp \|x\| \\ 0 \\ \vdots \\ 0
\end{bmatrix}
$$

Zbog numeričke stabilnost se najčešće uzima

$$
v_1=x_1+\mathop{\mathrm{sign}} (x_1) \|x\|_2.
$$

Matrica $H$ se __ne računa eksplicitno__ već se produkt $Hx$ računa po formuli

$$
Hx=x-v\frac{2v^Tx}{v^Tv}
$$

za koju je potrebno $O(6m)$ operacija.

In [5]:
function myHouseholderVector{T}(x::Array{T})
    # Vraca v
    v=deepcopy(x)
    v[1]=x[1]+sign(x[1])*norm(x)
    v
end

myHouseholderVector (generic function with 1 method)

In [6]:
x=rand(8)
v=myHouseholderVector(x)
β=(2/(v⋅v))*(v⋅x)
x-β*v

8-element Array{Float64,1}:
 -1.54718    
  5.55112e-17
  5.55112e-17
  2.22045e-16
  2.22045e-16
  1.11022e-16
  1.11022e-16
  5.55112e-17

In [7]:
norm(x)

1.5471820070627456

QR rastav matrice se računa rekurzivnim QR rastavom vektora pomoću Householderovih reflektora:

In [8]:
function myHouseholderQR{T}(A1::Array{T})
    # Vraca Q i R
    A=deepcopy(A1)
    m,n=size(A)
    # R=zeros(Float64,m,n)
    Q=eye(Float64,m,m)
    for k=1:n
        v=myHouseholderVector(A[k:m,k])
        β=(2/(v⋅v))*v
        A[k:m,k:n]=A[k:m,k:n]-β*(v'*A[k:m,k:n])
        Q[k:m,:]=Q[k:m,:]-β*(v'*Q[k:m,:])
    end
    R=triu(A)
    Q',R
end
    

myHouseholderQR (generic function with 1 method)

In [9]:
A=rand(8,5)

8x5 Array{Float64,2}:
 0.637868   0.942445   0.229427  0.335862   0.211171 
 0.0502825  0.788854   0.608826  0.0712778  0.344981 
 0.0522367  0.158408   0.278756  0.14095    0.0969722
 0.812943   0.653823   0.540247  0.687696   0.302442 
 0.864486   0.665771   0.103948  0.686406   0.6121   
 0.845197   0.357214   0.930272  0.836597   0.359225 
 0.72956    0.720899   0.340684  0.506786   0.976177 
 0.308771   0.0462862  0.355952  0.993085   0.655115 

In [10]:
Q,R=myHouseholderQR(A)

(
8x8 Array{Float64,2}:
 -0.358698   -0.435946    0.286206    0.0125258  …   0.466507   -0.374673   
 -0.0282758  -0.779004   -0.455964    0.0915112     -0.303554    0.188688   
 -0.0293747  -0.120349   -0.252613    0.0457061     -0.1448     -0.557876   
 -0.45715     0.014729   -0.0737819  -0.0881879      0.0948928   0.664911   
 -0.486135    0.0464109   0.454191    0.156038      -0.716986   -0.101483   
 -0.475288    0.351439   -0.590966   -0.364348   …  -0.0385142  -0.245066   
 -0.41026    -0.126566    0.137149   -0.068276       0.338098    0.0180863  
 -0.173634    0.216147   -0.258041    0.905452       0.174333   -0.000726289,

8x5 Array{Float64,2}:
 -1.77829  -1.46113   -1.04893   -1.55267   -1.20915 
  0.0      -0.959609  -0.234309   0.267602  -0.195313
  0.0       0.0       -0.86989   -0.392113  -0.113116
  0.0       0.0        0.0        0.623408   0.503129
  0.0       0.0        0.0        0.0       -0.619815
  0.0       0.0        0.0        0.0        0.0     
  0.0       

In [11]:
Q'*A

8x5 Array{Float64,2}:
 -1.77829      -1.46113      -1.04893      -1.55267      -1.20915    
  2.77556e-17  -0.959609     -0.234309      0.267602     -0.195313   
 -1.249e-16    -3.98986e-17  -0.86989      -0.392113     -0.113116   
 -1.11022e-16  -9.71445e-17  -5.55112e-17   0.623408      0.503129   
 -3.02709e-16  -1.65612e-17  -3.31766e-17  -4.77049e-17  -0.619815   
 -1.66533e-16  -1.69136e-16  -2.18575e-16  -1.66533e-16  -1.31839e-16
 -3.67761e-16  -5.55112e-17  -1.38778e-16  -1.94289e-16  -1.66533e-16
  2.99158e-16   7.82997e-17  -6.451e-18     2.21394e-16   1.57101e-16

Program `myHouseholderQR()` je ilustrativan. Profesionalni programi imaju sljedeća svojstva:

* računaju s blok matricama (uobičajena dimenzija bloka je 32 ili 64)
* izračuna se vektor $\hat v=v/v_1$. Vrijedi $\hat v_1=1$, dok se ostali elemenenti vektora $\hat v$ spremaju u strogi donji trokut matrice $A$.
* ako se traži matrica $Q$, akumulacija se vrši unatrag koristeći spremljene vektore $v$ (tako se smanjuje broj operacija)
* postoji opcija vraćanja ekonomičnog rastava
* postoji opcija računanja s __pivotiranjem__ - u svakom koraku se na prvo mjesto dovede stupac s najvećom normom pa je 
$$
AP=QR
$$
Vrijedi
$$
|R_{kk}|\geq |R_{k+1,k+1}|
$$
pa se može utvrditi i numerički rank matrice.

In [12]:
Q1,R1=qr(A,thin=true)

(
8x5 Array{Float64,2}:
 -0.358698   -0.435946    0.286206    0.0125258   0.454363  
 -0.0282758  -0.779004   -0.455964    0.0915112  -0.0984527 
 -0.0293747  -0.120349   -0.252613    0.0457061   0.0219782 
 -0.45715     0.014729   -0.0737819  -0.0881879   0.341099  
 -0.486135    0.0464109   0.454191    0.156038   -0.0100452 
 -0.475288    0.351439   -0.590966   -0.364348    0.048983  
 -0.41026    -0.126566    0.137149   -0.068276   -0.815176  
 -0.173634    0.216147   -0.258041    0.905452   -0.00424997,

5x5 Array{Float64,2}:
 -1.77829  -1.46113   -1.04893   -1.55267   -1.20915 
  0.0      -0.959609  -0.234309   0.267602  -0.195313
  0.0       0.0       -0.86989   -0.392113  -0.113116
  0.0       0.0        0.0        0.623408   0.503129
  0.0       0.0        0.0        0.0       -0.619815)

In [13]:
Q2,R2,P2=qr(A,Val{true})

(
8x5 Array{Float64,2}:
 -0.358698   -0.435946    0.286206   -0.344874   -0.296082  
 -0.0282758  -0.779004   -0.455964    0.134113   -0.00900092
 -0.0293747  -0.120349   -0.252613    0.0117417  -0.0493378 
 -0.45715     0.014729   -0.0737819  -0.320409   -0.146504  
 -0.486135    0.0464109   0.454191    0.10614    -0.114817  
 -0.475288    0.351439   -0.590966   -0.267656    0.25201   
 -0.41026    -0.126566    0.137149    0.589874    0.566764  
 -0.173634    0.216147   -0.258041    0.57395    -0.700317  ,

5x5 Array{Float64,2}:
 -1.77829  -1.46113   -1.04893   -1.20915   -1.55267 
  0.0      -0.959609  -0.234309  -0.195313   0.267602
  0.0       0.0       -0.86989   -0.113116  -0.392113
  0.0       0.0        0.0        0.798317   0.392895
  0.0       0.0        0.0        0.0       -0.484016,

[1,2,3,5,4])

In [14]:
Q2*R2-A[:,P2]

8x5 Array{Float64,2}:
 -3.33067e-16   4.44089e-16   8.32667e-17   2.22045e-16   1.66533e-16
  0.0          -1.11022e-16  -2.22045e-16   0.0           0.0        
  0.0           0.0           0.0           0.0           0.0        
  0.0           2.22045e-16   1.11022e-16   1.11022e-16   2.22045e-16
  1.11022e-16   2.22045e-16   5.55112e-17   1.11022e-16   0.0        
  0.0           2.22045e-16   0.0          -5.55112e-17   0.0        
  0.0           2.22045e-16   0.0           1.11022e-16   0.0        
  0.0           5.55112e-17   5.55112e-17   0.0          -2.22045e-16

## Brzina

Broj računskih operacija potrebnih za računanje QR rastava matrice $n\times n$ je $O\big(\frac{4}{3}n^3\big)$ za računanje matrice $R$ i  $O\big(\frac{4}{3}n^3\big)$ za računanje matrice $Q$. 


In [15]:
n=512
A=rand(n,n)

512x512 Array{Float64,2}:
 0.536437  0.620146  0.955737   …  0.716935    0.35192    0.284631 
 0.783614  0.391956  0.0641036     0.00798083  0.959556   0.26732  
 0.242334  0.266814  0.914898      0.250891    0.328223   0.604216 
 0.608386  0.16219   0.377054      0.939018    0.390028   0.302415 
 0.91532   0.53489   0.3475        0.663843    0.546346   0.726047 
 0.844444  0.518174  0.160187   …  0.554683    0.407571   0.621222 
 0.399279  0.717973  0.354074      0.527295    0.42568    0.388296 
 0.483104  0.578484  0.812733      0.0625844   0.807464   0.628519 
 0.549085  0.827302  0.426681      0.714567    0.180581   0.5971   
 0.673063  0.619267  0.819928      0.409231    0.6785     0.70661  
 0.790026  0.816188  0.428422   …  0.799447    0.0977509  0.95705  
 0.361776  0.793829  0.943605      0.673115    0.621075   0.609003 
 0.642054  0.577293  0.338452      0.653621    0.473432   0.0944336
 ⋮                              ⋱              ⋮                   
 0.780078  0.195557  0

In [16]:
@time qr(A);

  0.048902 seconds (785 allocations: 8.325 MB)


In [17]:
@time qr(A,Val{true});

  0.061348 seconds (36 allocations: 6.267 MB)


In [18]:
@time myHouseholderQR(A);

  1.391346 seconds (48.49 k allocations: 3.359 GB, 7.77% gc time)


## Točnost

Za matrice $\hat Q$ i $\hat R$ izračunate Householder-ovom metodom vrijedi: 

* $\hat Q^T\hat Q=I+E$, $\|E \|_2\approx \varepsilon$,

* $ \| A-\hat Q\hat R\|_2\approx \varepsilon\|A\|_2$,

* postoji egzaktna ortiogonalna matrica $Q$ za koju je $\| A- Q\hat R\|_2\approx \varepsilon\|A\|_2$.