# QR rastav

---

__QR rastav__ matrice $A$ tipa $m\times n$,  $m\geq n$,
glasi

$$
A=QR, 
$$

pri čemu je $Q$ __ortonormirana matrica__ dimenzije $m\times m$, odnosno
\[
Q^TQ=Q Q^T=I,
\]
a $R$ je $m\times n$ gornje trokutasta matrica.

Ortonormiranu matricu kraće zovemo i __ortogonalna matrica__.

Na primjer,

$$
\begin{bmatrix} a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33} \\
a_{41} & a_{42} & a_{43} \\
a_{51} & a_{52} & a_{53}
\end{bmatrix}
=
\begin{bmatrix}
q_{11} & q_{12} & q_{13} & q_{14} & q_{15} \\
q_{21} & q_{22} & q_{23} & q_{24} & q_{25} \\
q_{31} & q_{32} & q_{33} & q_{34} & q_{35} \\
q_{41} & q_{42} & q_{43} & q_{44} & q_{45} \\
q_{51} & q_{52} & q_{53} & q_{54} & q_{55}
\end{bmatrix}
\begin{bmatrix}
r_{11} & r_{12} & r_{13} \\
0 & r_{22} & r_{23} \\
0 & 0 & r_{33} \\
0 & 0 & 0 \\
0 & 0 & 0 
\end{bmatrix}. \tag{1}
$$

S (1) je definiram i __ekonomični QR rastav__

$$
\begin{bmatrix} a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33} \\
a_{41} & a_{42} & a_{43} \\
a_{51} & a_{52} & a_{53}
\end{bmatrix}
=
\begin{bmatrix}
q_{11} & q_{12} & q_{13} \\
q_{21} & q_{22} & q_{23} \\
q_{31} & q_{32} & q_{33} \\
q_{41} & q_{42} & q_{43} \\
q_{51} & q_{52} & q_{53}
\end{bmatrix}
\begin{bmatrix}
r_{11} & r_{12} & r_{13} \\
0 & r_{22} & r_{23} \\
0 & 0 & r_{33}
\end{bmatrix}. \tag{2}
$$


Izjednačavanje stupaca počevši od prvog daje: 

\begin{align}
t&=a_{:1}\\
r_{11}&=\|t\|_2 \\
q_{:1}&=t\frac{1}{r_{11}}\\
r_{12}&= q_{:1}^Ta_{:1} \\
t&=a_{:2}-q_{:1}r_{12} \\
r_{22}&=\|t\|_2 \\
q_{:2}&=t\frac{1}{r_{22}} \\
r_{13}&=q_{:1}^Ta_{:3} \\
r_{23}&=q_{:2}^Ta_{:3} \\
t&=a_{:3}-q_{:1}r_{13}-q_{:2}r_{23}\\
r_{33}&=\|t\|_2 \\
q_{:3}&=t\frac{1}{r_{33}}.
\end{align}

Indukcijom slijedi __Gram-Schmidt-ov postupak ortogonalizacije__.

In [1]:
function myGramSchmidtQR{T}(A::Array{T})
    m,n=size(A)
    R=zeros(Float64,n,n)
    Q=Array(Float64,m,n)
    R[1,1]=norm(A[:,1])
    Q[:,1]=A[:,1]/R[1,1]
    for k=2:n
        for i=1:k-1
            R[i,k]=Q[:,i]⋅A[:,k]
        end
        t=A[:,k]-sum([R[i,k]*Q[:,i] for i=1:k-1])
        R[k,k]=norm(t)
        Q[:,k]=t/R[k,k]
    end
    Q,R
end 

myGramSchmidtQR (generic function with 1 method)

In [5]:
A=rand(8,5)
Q,R=myGramSchmidtQR(A)
Q

8×5 Array{Float64,2}:
 0.0667871   0.347728  -0.592102   -0.271719   -0.0796266
 0.132742    0.453787   0.357013    0.515945   -0.476126 
 0.0627752   0.612443  -0.0982551   0.151018    0.688718 
 0.13384     0.33206    0.170432   -0.727717   -0.340692 
 0.231819    0.197815  -0.463022    0.255759   -0.348407 
 0.68374    -0.266884  -0.0575138  -0.0527572   0.143468 
 0.468983   -0.225121  -0.206266    0.154173   -0.0598524
 0.463551    0.16363    0.472243   -0.125003    0.176089 

In [6]:
R

5×5 Array{Float64,2}:
 1.33774  1.18926  0.917119   1.33698    0.875028  
 0.0      1.37557  1.30459    0.445936   0.427052  
 0.0      0.0      0.595713  -0.0211817  0.2928    
 0.0      0.0      0.0        0.436455   0.00651613
 0.0      0.0      0.0        0.0        0.397872  

In [7]:
A-Q*R

8×5 Array{Float64,2}:
  0.0          0.0  0.0  0.0  0.0
  0.0          0.0  0.0  0.0  0.0
  1.38778e-17  0.0  0.0  0.0  0.0
  0.0          0.0  0.0  0.0  0.0
  0.0          0.0  0.0  0.0  0.0
 -1.11022e-16  0.0  0.0  0.0  0.0
  0.0          0.0  0.0  0.0  0.0
  0.0          0.0  0.0  0.0  0.0

In [8]:
Q'*Q

5×5 Array{Float64,2}:
  1.0          -1.66533e-16  -8.32667e-17  -4.09395e-16  -1.94289e-16
 -1.66533e-16   1.0          -2.77556e-16  -1.07553e-16   3.26128e-16
 -8.32667e-17  -2.77556e-16   1.0           5.06539e-16   4.71845e-16
 -4.09395e-16  -1.07553e-16   5.06539e-16   1.0           7.14706e-16
 -1.94289e-16   3.26128e-16   4.71845e-16   7.14706e-16   1.0        

Algoritam `myGramSchmidtQR()` je numerički nestabilan pa je bolje koristiti _modificirani Gram-Schmidt-ov algoritam_ ili _Householder-ove reflektore_ ili _Givens-ove rotacije_ (vidi [Matrix Computations, poglavlje 5][GVL13]).

[GVL13]: https://books.google.hr/books?id=X5YfsuCWpxMC&printsec=frontcover&hl=hr#v=onepage&q&f=false "G. Golub and C. F Van Loan, 'Matrix Computations', 4th Edition, John Hopkins, Baltimore, 2013"

## Householderovi reflektori

__QR rastav vektora__ $x$ jednak je

$$
H \begin{bmatrix} x_1 \\ x_2 \\ \vdots \\ x_m 
\end{bmatrix}  =r,
$$

gdje je 

$$
H=I - \frac{2}{v^Tv}v v^T, \qquad  
v=\begin{bmatrix}
x_1\pm \|x\|_2 \\ x_2 \\ x_3 \\ \vdots \\ x_m
\end{bmatrix}.
$$ 

__Householderov reflektor__ $H$ je __simetrična__ i __ortogonalna__ matrica (dokažite!). Ovisno o izboru predznaka u definicije vektora $v$ vrijedi

$$
r=\begin{bmatrix} \mp \|x\| \\ 0 \\ \vdots \\ 0
\end{bmatrix}
$$

Zbog numeričke stabilnost se najčešće uzima

$$
v_1=x_1+\mathop{\mathrm{sign}} (x_1) \|x\|_2.
$$

Matrica $H$ se __ne računa eksplicitno__ već se produkt $Hx$ računa po formuli

$$
Hx=x-v\frac{2v^Tx}{v^Tv}
$$

za koju je potrebno $O(6m)$ operacija.

In [9]:
function myHouseholderVector{T}(x::Array{T})
    # Vraca v
    v=deepcopy(x)
    v[1]=x[1]+sign(x[1])*norm(x)
    v
end

myHouseholderVector (generic function with 1 method)

In [10]:
x=rand(8)
v=myHouseholderVector(x)
β=(2/(v⋅v))*(v⋅x)
x-β*v

8-element Array{Float64,1}:
 -1.94773    
 -2.77556e-17
 -1.11022e-16
 -1.11022e-16
 -2.22045e-16
 -2.22045e-16
 -2.22045e-16
 -2.77556e-17

In [11]:
norm(x)

1.9477272239020311

QR rastav matrice se računa rekurzivnim QR rastavom vektora pomoću Householderovih reflektora:

In [12]:
function myHouseholderQR{T}(A1::Array{T})
    # Vraca Q i R
    A=deepcopy(A1)
    m,n=size(A)
    # R=zeros(Float64,m,n)
    Q=eye(Float64,m,m)
    for k=1:n
        v=myHouseholderVector(A[k:m,k])
        β=(2/(v⋅v))*v
        A[k:m,k:n]=A[k:m,k:n]-β*(v'*A[k:m,k:n])
        Q[k:m,:]=Q[k:m,:]-β*(v'*Q[k:m,:])
    end
    R=triu(A)
    Q',R
end
    

myHouseholderQR (generic function with 1 method)

In [13]:
A=rand(8,5)

8×5 Array{Float64,2}:
 0.496754  0.585752  0.149732   0.518909  0.811441 
 0.352272  0.497119  0.92009    0.583799  0.495599 
 0.609883  0.157483  0.751717   0.422452  0.921829 
 0.261205  0.523142  0.528053   0.098942  0.31751  
 0.356776  0.281894  0.23427    0.31886   0.816996 
 0.460123  0.874011  0.0859313  0.645191  0.0784321
 0.651939  0.864188  0.428977   0.40529   0.386595 
 0.371886  0.111765  0.348495   0.129201  0.784203 

In [15]:
Q,R=myHouseholderQR(A)

(
[-0.379503 -0.0809463 … -0.377341 -0.183311; -0.269124 -0.164106 … 0.179241 0.197623; … ; -0.498059 -0.230842 … 0.442949 -0.0133157; -0.284109 0.36597 … -0.117945 0.806941],

[-1.30896 -1.38009 … -1.12289 -1.59979; 0.0 -0.765991 … -0.236617 0.593096; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0])

In [16]:
Q'*A

8×5 Array{Float64,2}:
 -1.30896      -1.38009      -1.16679      -1.12289      -1.59979    
  8.32667e-17  -0.765991      0.156311     -0.236617      0.593096   
 -8.67362e-17  -3.03577e-17  -0.833551     -0.0725695    -0.139226   
  1.38778e-17   2.04697e-16   3.19189e-16   0.41845       0.0817155  
  2.35922e-16   5.89806e-17   1.38778e-16   3.46945e-18  -0.596276   
  1.49186e-16   1.73472e-17   7.28584e-17  -9.36751e-17  -5.55112e-17
  1.249e-16    -2.25514e-17  -2.08167e-17  -1.40513e-16  -1.249e-16  
  0.0           5.55112e-17  -1.11022e-16  -6.93889e-17  -1.11022e-16

Program `myHouseholderQR()` je ilustrativan. Profesionalni programi imaju sljedeća svojstva:

* računaju s blok matricama (uobičajena dimenzija bloka je 32 ili 64),
* izračuna se vektor $\hat v=v/v_1$. Vrijedi $\hat v_1=1$, dok se ostali elemenenti vektora $\hat v$ spremaju u strogi donji trokut matrice $A$,
* ako se traži matrica $Q$, akumulacija se vrši unatrag koristeći spremljene vektore $v$ (tako se smanjuje broj operacija),
* postoji opcija vraćanja ekonomičnog rastava,
* postoji opcija računanja s __pivotiranjem__ - u svakom koraku se na prvo mjesto dovede stupac s najvećom normom pa je 

$$
AP=QR.
$$

Vrijedi

$$
|R_{kk}|\geq |R_{k+1,k+1}|
$$

pa se može utvrditi i numerički rank matrice.

In [18]:
Q1,R1=qr(A,thin=true)
Q1

8×5 Array{Float64,2}:
 -0.379503  -0.0809463   0.336411    0.234266   -0.469612 
 -0.269124  -0.164106   -0.757878    0.448734   -0.0338805
 -0.46593    0.633873   -0.130758    0.0950165   0.378144 
 -0.199552  -0.323429   -0.414819   -0.553866   -0.297848 
 -0.272565   0.123068    0.123559    0.121605   -0.528653 
 -0.351518  -0.507689    0.293755    0.362442    0.287676 
 -0.498059  -0.230842    0.139249   -0.474353    0.360798 
 -0.284109   0.36597     0.0482336  -0.238325   -0.232816 

In [19]:
R1

5×5 Array{Float64,2}:
 -1.30896  -1.38009   -1.16679   -1.12289    -1.59979  
  0.0      -0.765991   0.156311  -0.236617    0.593096 
  0.0       0.0       -0.833551  -0.0725695  -0.139226 
  0.0       0.0        0.0        0.41845     0.0817155
  0.0       0.0        0.0        0.0        -0.596276 

In [20]:
Q2,R2,P2=qr(A,Val{true})

(
[-0.447179 -0.123088 … 0.125025 -0.269239; -0.27312 -0.186846 … 0.37424 -0.424215; … ; -0.21305 -0.527484 … -0.34513 0.482118; -0.432168 0.245084 … -0.256085 0.0911318],

[-1.81458 -0.966364 … -0.93705 -1.15402; 0.0 -1.24801 … -0.661377 -0.553902; … ; 0.0 0.0 … 0.42051 0.0451863; 0.0 0.0 … 0.0 0.266095],

[5,2,3,4,1])

In [23]:
R2

5×5 Array{Float64,2}:
 -1.81458  -0.966364  -1.14372   -0.93705    -1.15402  
  0.0      -1.24801   -0.30872   -0.661377   -0.553902 
  0.0       0.0       -0.822937  -0.0702066  -0.0442304
  0.0       0.0        0.0        0.42051     0.0451863
  0.0       0.0        0.0        0.0         0.266095 

In [24]:
Q2*R2-A[:,P2]

8×5 Array{Float64,2}:
 -1.11022e-16  -2.22045e-16  -3.88578e-16  -1.11022e-16  -3.88578e-16
  0.0          -1.11022e-16  -2.22045e-16  -4.44089e-16  -2.22045e-16
  1.11022e-16   5.55112e-17   0.0           1.66533e-16   0.0        
  5.55112e-17   0.0           0.0           0.0          -5.55112e-17
  1.11022e-16  -1.11022e-16  -1.66533e-16  -5.55112e-17  -1.11022e-16
  0.0           0.0          -2.77556e-17  -2.22045e-16  -5.55112e-17
  5.55112e-17  -2.22045e-16  -5.55112e-17  -2.22045e-16  -1.11022e-16
  0.0          -5.55112e-17  -1.66533e-16   0.0          -1.66533e-16

## Brzina

Broj računskih operacija potrebnih za računanje QR rastava matrice $n\times n$ je $O\big(\frac{4}{3}n^3\big)$ za računanje matrice $R$ i  $O\big(\frac{4}{3}n^3\big)$ za računanje matrice $Q$. 


In [25]:
n=512
A=rand(n,n)

512×512 Array{Float64,2}:
 0.453802   0.674054   0.0220466  …  0.184324   0.173802    0.497125  
 0.800241   0.159      0.0451496     0.732352   0.254026    0.449051  
 0.536598   0.464412   0.102621      0.245442   0.397952    0.383429  
 0.705603   0.947807   0.119884      0.209144   0.00364402  0.733519  
 0.480435   0.275804   0.521935      0.354324   0.134086    0.509033  
 0.962245   0.90179    0.887146   …  0.445587   0.900599    0.438229  
 0.722913   0.0059534  0.592116      0.457943   0.666078    0.714337  
 0.13147    0.958035   0.401333      0.507052   0.913107    0.0983071 
 0.999538   0.346287   0.552161      0.608316   0.08645     0.420911  
 0.48867    0.13508    0.262626      0.613926   0.702089    0.825859  
 0.990997   0.92944    0.943248   …  0.131223   0.563115    0.631748  
 0.589585   0.479292   0.912786      0.283351   0.754085    0.120206  
 0.66349    0.701969   0.264666      0.172826   0.365798    0.00865603
 ⋮                                ⋱             ⋮  

In [26]:
@time qr(A);

  0.054252 seconds (1.06 k allocations: 8.319 MB, 14.29% gc time)


In [27]:
@time qr(A,Val{true});

  0.097326 seconds (557 allocations: 6.307 MB, 5.86% gc time)


In [28]:
@time myHouseholderQR(A);

  1.386769 seconds (29.02 k allocations: 3.358 GB, 6.76% gc time)


## Točnost

Za matrice $\hat Q$ i $\hat R$ izračunate Householder-ovom metodom vrijedi: 

\begin{align*}
\hat Q^T\hat Q& =I+E, \qquad \|E \|_2\approx \varepsilon,\\ 
\| A-\hat Q\hat R\|_2& \approx \varepsilon\|A\|_2.
\end{align*}

Također, postoji egzaktna ortogonalna matrica $Q$ za koju je 

$$\| A- Q\hat R\|_2\approx \varepsilon\|A\|_2.
$$